### ISSUE TITLE
Posts Query Filter Design ?

### ISSUE THREAD

**Issue by DrMohamedGamal** [dudaster/ele-custom-skin#1]
Can you boost this plugin by adding filtring design ability ?

I mean if I create a posts grid for many categories , posts types with many meta values 

Need to filter posts according to 
- CPT 
- Terms 
- Meta values that displayed as
    * Check boxes
    * Sliding bar
    * Dropdown

**Comment by dudaster** [comment]
Sorry this plugin is just a skin not a widget.
You need to add extra options on query tab for Posts Widget.

**Comment by imdyakov** [comment]
However, that would be really nice to have filters as @DrMohamedGamal suggested.
