### ISSUE TITLE
Dynamic Anywhere Custom Post Loop in custom post

### ISSUE THREAD

**Issue by bryanb** [dudaster/ele-custom-skin#100]
I'm wondering if this is possible- I haven't been able to make it work yet.  Here's the situation:

I have a custom post.  It's a type "Guide", and it has custom fields.  One of them is age (guide_age is the stub for the cf) - stored as text.
On this guide page, I run a custom loop.  This loop goes over custom posts called "dance classes".   

I'm wondering if it's possible for me to insert in the stored text content of the Dance Classes cpt a holder of {{guide_age}} and have it change in the returned loop based on the custom field of the page the loop is running on? For example, if it's a page for 4 yr old dance classes, and the 'guide_age' custom field= 4, it would replace the {{guide_age}} with '4' in all occurrences in the looped items?

If not, is there some way to add the 'age_guide' cf to a custom variable and have it work? 

Thanks,

Bryan

**Comment by dudaster** [comment]
With Pro version you should be able to do this.
