### ISSUE TITLE
Wired styling behaviour

### ISSUE THREAD

**Issue by imdyakov** [dudaster/ele-custom-skin#101]
Hi,
After some update of Elementor loop templates started to look wired. As you can see in the editor (https://yadi.sk/i/D9N6GKQc4b6UqQ) everything looks nice and tidy (top and bottom blocks are taking 100% of the width). But when you go to the front end the image is a bit narrower than the bottom block (https://yadi.sk/i/e14Xlg6O6O4gug). After I readjust the column margins to zero and resave the loop it shows up correctly on the front end for the first time. But as soon as I clean up the cache or refresh it everything goes wrong again. I noticed that in all my loops and cannot figure out what causes it. Here are the links for showing the issue:
https://megasport.center/sport-school/figure-skating/
https://megasport.center/afisha-meropriyatiy/

**Comment by dudaster** [comment]
It will be fixed in the next update. Thanks!
