### ISSUE TITLE
Layout settings loop not consistent

### ISSUE THREAD

**Issue by iMiek** [dudaster/ele-custom-skin#102]
First time after saving a loop template it works, archive page with the loop looks fine.
But after a refresh of the archives page layout adjustments like padding are gone for the loop part.

Post-3060.css (the loop id) is loaded with (among others) padding:0px.

What I see when I inspect in my browser:

.elementor-column-gap-default>.elementor-row>.elementor-column>.elementor-element-populated {padding: 10px;}

Before refresh; post-3060 overrules the above .elementor……. setting
After refresh: the above .elementor……. setting overrules the padding setting 0px in my loop template.

![before-refesh](https://user-images.githubusercontent.com/42237516/69015551-53448d00-0995-11ea-9ae4-a233ead556a7.jpeg)

![After-refresh](https://user-images.githubusercontent.com/42237516/69015569-67888a00-0995-11ea-92af-e6d0efe3a7db.jpeg)

**Comment by dudaster** [comment]
Select no gap in the section layout. This would solve the issue.

**Comment by dudaster** [comment]
The problem will be solved with the next update.
