### ISSUE TITLE
Problem with styling settings since upgrade Wordpress 5.3

### ISSUE THREAD

**Issue by GertjanTanghe-KoomBanaBay** [dudaster/ele-custom-skin#103]
We are having some styling issues with the loop templates since updating to wordpress 5.3.
Fonts settings not working correctly and adding padding to each loop item when used in the Post custom widget.

**Comment by dudaster** [comment]
New version is up. Please update and let me know if it fixes the problem.

**Comment by GertjanTanghe-KoomBanaBay** [comment]
Thanks for the quick update! Does not seem to solve the issue. When editing the post widget itself with Elementor it does show the correct styling settings. When loading the website frontend a first time after editing the styling seems ok, but when hitting refresh the added style is gone.

**Comment by dudaster** [comment]
can you provide an url?

**Comment by GertjanTanghe-KoomBanaBay** [comment]
https://realtravel.be/ 
see screenshots https://imgur.com/a/EHJHGXW

_or_ 

https://cruisemarkt.eu/

**Comment by dudaster** [comment]
Go to Dashboard>Settings>Generelar and make sure you have https in there. The css is not loading because it's not secure.

**Comment by GertjanTanghe-KoomBanaBay** [comment]
Thank you for this! The update worked for cruise market website and the "https" worked for real travel.
