### ISSUE TITLE
ele custom skin front background picture not showing featured image

### ISSUE THREAD

**Issue by jp70m** [dudaster/ele-custom-skin#104]
tanks dudaster for the ele custom skin.

i have come across an issue.  for a project i need the featured image of the post to be shown center center cover. 

as skin to loop i use flip box. there i set 'front background' image featured image center center cover.

when i call the loop on the page the background images are identical, instead of being as content image.

thank you for looking into this.

![flip_background](https://user-images.githubusercontent.com/52929578/69529243-2c2b2400-0f70-11ea-8358-8f50bbc14abf.PNG)
![Loop_Post](https://user-images.githubusercontent.com/52929578/69529244-2cc3ba80-0f70-11ea-90a0-40d29a11190f.PNG)
![filp_Front](https://user-images.githubusercontent.com/52929578/69529245-2cc3ba80-0f70-11ea-80cc-ff47062ec486.PNG)

**Comment by dudaster** [comment]
Please send me a link to take a look. Also make sure Loop template doesn't have a condition.

**Comment by jp70m** [comment]
Hi dudaThank you for coming back! 
Here is the link. 
Team – lernoase-bellaria.ch
I can give you access to the website if u want. 
ThanksJp
  
|  
|   
|   
|   |    |

   |

  |
|  
|   |  
Team – lernoase-bellaria.ch
 

  |   |

  |

  |

  


Gesendet von Yahoo Mail auf Android 
 
  Am Di., Nov. 26, 2019 at 12:40 schrieb Liviu Duda<notifications@github.com>:   
Please send me a link to take a look. Also make sure Loop template doesn't have a condition.

**Comment by Pulmunen** [comment]
I have the identical problem.  I don’t have a URL right now, but I can generate one for you within 24 hours if it would help.  I’m using Elementor, Elementor Pro and Ele Custom Skins only and trying to use featured image as the background image for the front of the flip box. The loop template doesn’t have a condition.

**Comment by DODMax** [comment]
I have a similar problem involving featured images and flip boxes.
The featured image is not updated when looping and only the featured image of the first element is applied.

I added a featured image widget just under my flipbox widget to demo the issue. You can see that the 2nd flipbox's featured image is not correct:
![image](https://user-images.githubusercontent.com/1137276/69777681-ef5f6700-11d3-11ea-8fe0-16f9f361257e.png)

Link to the page: https://web.lexiconthai.dev/services/web-design-agency-bangkok-thailand/

**Comment by dudaster** [comment]
I’m on it.

**Comment by dudaster** [comment]
Fixed. Update!
