### ISSUE TITLE
Duplicating content from dynamic fields

### ISSUE THREAD

**Issue by holocene7** [dudaster/ele-custom-skin#105]
I'm using Ele custom skin with dynamic fields to have custom archive pages. But the fields are not being "dynamic" and are duplicating the content from the first post. I've checked the other archive pages and it's duplicating everywhere. Any ideas why it's duplicating and not showing the correct content?

I've doubled checked in the elementor editor that the dynamic fields are set properly in the loop template. I've also double checked that the individual posts have unique content.
![78407591_10162799754525486_1621096875723587584_n](https://user-images.githubusercontent.com/12396650/69648183-ab992000-1062-11ea-9cca-b18ea26f7140.jpg)

**Comment by dudaster** [comment]
What are you using for  custom fields ?

**Comment by holocene7** [comment]
I'm using JetEngine

**Comment by dudaster** [comment]
I don’t have jetengine yet but I had complains about it.

While I’m looking for a fix you have three choices: open an issue on jetengine, change ECS, change jetengine.

**Comment by holocene7** [comment]
I just tried custom fields with ACF instead and it's working properly. No longer duplicating. Must be an issue with JetEngine and not Ele custom skin.

Thanks for creating such a great plugin!
