### ISSUE TITLE
Custom Post Types with Dynamic Content Not Functioning Properly

### ISSUE THREAD

**Issue by sheaoliver** [dudaster/ele-custom-skin#106]
Hello Dudaster Team,

I got really excited when I found Elementor Custom Skin, but it is not working as expected. 

Here are the details:

 I am using Crocoblocks' JetEngine to create a custom post type called "Books" and create meta fields in that custom post type. Then I created two sample posts for "Books"

I used Elementor Custom Skin to create a Loop that would display:
  * The custom post type "Books" Title
  * A dynamic image from a meta field (using a URL) in the custom post type "Books"
  * A dynamic text field from a meta field in the custom post type "Books"

When I designed the loop "First Book Loop" and inserted the standard Elementor widget "Post Title," it displayed the Title of the Loop. I added the two dynamic fields and this was the result:

![Screen Shot 2019-11-26 at 11 22 01 AM](https://user-images.githubusercontent.com/58081556/69661268-4f70d480-103f-11ea-87a3-ea8cbfdce187.png)

Then I created a page, and added the standard Elementor widget "Posts" and selected my new Loop "First Book Loop." The Titles for the two books are correct. However, the image and description are duplicating from the first custom Book post that I created. Here is the view from the editor:

![Screen Shot 2019-11-26 at 11 30 23 AM](https://user-images.githubusercontent.com/58081556/69661734-2997ff80-1040-11ea-8ae4-950f01628ccc.png)

So, I thought we were pretty close to a great solution until I saved the page and viewed it. Only the Titles from the custom post type "books" appeared. The dynamic image and dynamic text field did not appear. Here is what it looked like:

![Screen Shot 2019-11-26 at 11 32 28 AM](https://user-images.githubusercontent.com/58081556/69661885-724fb880-1040-11ea-9141-11d9d05f6404.png)

Is this an issue that can be resolved? I am really excited about this plug and will be purchasing the pro version if it can support custom post types and dynamic content.

Thanks!!!

**Comment by dudaster** [comment]
It should have worked.  Try to save the loop template without a condition. Let me know if it solved the issue.

**Comment by sheaoliver** [comment]
Wow! That was a fast reply! Thank you!

I did remove the Condition on the loop template, and below is the result. The post "Title" is missing and the content is duplicating from the first post.

![Screen Shot 2019-11-26 at 11 50 44 AM](https://user-images.githubusercontent.com/58081556/69663305-38cc7c80-1043-11ea-951b-74db21a9815d.png)

**Comment by dudaster** [comment]
Can you provide me with an URL to take a look?

**Comment by sheaoliver** [comment]
Here is the URL for that page: http://bestbookmonkey.com/stagingsite04/testing-0001/

**Comment by dudaster** [comment]
I want you to duplicate  the post widget and the second one add it with classic skin.

It seems you have something called jet listings that messes up with the ECS

**Comment by dudaster** [comment]
For Title because you selected hide Page title h1.entry-title is set to display none so if you use Post Title Widget it has h1.entry-title so it is going to be hidden.

To avoid this please Heading Widget with dynamic value.

**Comment by sheaoliver** [comment]
I duplicated the Post widget and selected the classic skin. I do not have featured images or a description in the custom post type "book," so only the Title appears.

![Screen Shot 2019-11-26 at 12 09 05 PM](https://user-images.githubusercontent.com/58081556/69664513-c4470d00-1045-11ea-8df8-b8179a8ab0f2.png)

**Comment by dudaster** [comment]
can you add distinct images to the books and change please the Post Title Widget with Heading Widget?

**Comment by dudaster** [comment]
In Loop Template

**Comment by dudaster** [comment]
Also remind me to add a fix to the issue:

Another way to fix this is to select Post Widget>Advanced> Custom CSS
add
```
selector h1.entry-title{
    display:block;
}
```

**Comment by sheaoliver** [comment]
Changing to the Heading widget worked, both of the books have unique images and content. Here are the single pages:

![Screen Shot 2019-11-26 at 12 27 46 PM](https://user-images.githubusercontent.com/58081556/69665754-459f9f00-1048-11ea-99fa-64fd4fae0d70.png)
![Screen Shot 2019-11-26 at 12 27 39 PM](https://user-images.githubusercontent.com/58081556/69665769-4afce980-1048-11ea-8c5d-bc08412187f1.png)

**Comment by dudaster** [comment]
Let me install Crocoblocks myself... because with ACF there is no issue

**Comment by dudaster** [comment]
Sorry I can find it in wordpress repository.... where should I look for it?

**Comment by sheaoliver** [comment]
Their website is: https://crocoblock.com/

**Comment by sheaoliver** [comment]
While I do think it would be awesome if you could work with crocoblocks. Their listing functionality works as a replacement to skins and appears to be what my site needs. Thank you for all your help today. I did make a donation to your plugin.

**Comment by dudaster** [comment]
Thanks for pointing it out. And thanks for the donation!
