### ISSUE TITLE
Can't modify posts widget anymore

### ISSUE THREAD

**Issue by Jorigamix** [dudaster/ele-custom-skin#107]
Hi there!

I am experiencing issues with Ele Custom Skin since Elementor's last update. I have a template in Elementor where I have a posts widget with custom skin. It is supposed to display one of my custom post content (testimonial) but right now the posts widget is not editable anymore (nothing shows up in Elementor's left panel on editing mode). 
<img width="682" alt="2019-11-28_13h09_35" src="https://user-images.githubusercontent.com/58294966/69805142-5aaf3600-11e0-11ea-973d-3cc13d098732.png">

<img width="188" alt="2019-11-28_12h56_53" src="https://user-images.githubusercontent.com/58294966/69804320-921ce300-11de-11ea-94ee-c2351c6bed0e.png">

I tried disabling Ele Custom Skin and the posts widget becomes editable again.
<img width="187" alt="2019-11-28_12h59_03" src="https://user-images.githubusercontent.com/58294966/69804515-0c4d6780-11df-11ea-96df-877624280763.png">

However posts widgets already set up on other similar template pages are still working fine on the front-end (content shows up but is not editable in editing mode). I just can't set up a new one (or edit previous ones).

Any thoughts on this ?

I am using Elementor Version 2.8.0-beta2 + Jupiter X theme v1.0.0-beta1

Thanks !

**Comment by dudaster** [comment]
This issue is solved and the update will be available today.

**Comment by Jorigamix** [comment]
Perfect! Thanks for the quick answer :)
