### ISSUE TITLE
I have Pro Licence But I Am Asked to Unlock Pro Although Licence Is Active

### ISSUE THREAD

**Issue by hoohum** [dudaster/ele-custom-skin#108]
Hi, I developed a site on one domain then used Duplicator Pro to move it to it's final destination domain. I bought Ele Custom Skin Pro and added it to the test site. After cloning on the final domain, the license shows as being active. I've even deactivated and reactivated it. Still in an elementor EDIT POSTS window I cannot use Pro features. I see 'Unlock Pro Features' and the main feature I am using is 'Same Height' and all the post featured images in the gallery are not the same height )unlike the test site). So can you help please. 

<img width="297" alt="Screenshot 2019-11-28 at 19 38 21" src="https://user-images.githubusercontent.com/25119637/69829147-d4faad00-1216-11ea-8bfa-56eb612d4d3e.png">

**Comment by dudaster** [comment]
For the ECS Pro to work it is not mandatory for the license to be activated. Please make sure the ECS pro plugin is active and you have the latest version of ECS . Also make sure you have both of them active.

Let me know if it solves the issue.

**Comment by hoohum** [comment]
Hi,

Thank you for a quick response.

Yes both plugins are installed and activated. Here are screenshots. Please let me know if I can gibe you any more information.

Many thanks,
Barry.

Licence


Both plug ins installed and activated.



On 28 Nov 2019, at 20:32, Liviu Duda <notifications@github.com> wrote:

For the ECS Pro to work it is not mandatory for the license to be activated. Please make sure the ECS pro plugin is active and you have the latest version of ECS . Also make sure you have both of them active.

Let me know if it solves the issue.

**Comment by dudaster** [comment]
This is the first time I hear of this. Can you delete ECS pro and install it again? Maybe there are some file missing from it.

**Comment by hoohum** [comment]
Well I will have to find a good time to do that as it’s a live site now. Your plug in is very important for the home page and all the gallery pages so I’ll have to try remember what settings I used and how to recreate them. 

To be honest, your plug in is the best thing I’ve ever used with Elementor so hopefully I will find it works ok after doing as you say. Perhaps I’ll try on the test site first to see what happens.

Many thanks,
Barry.

On 28 Nov 2019, at 20:45, Liviu Duda <notifications@github.com> wrote:

This is the first time I hear of this. Can you delete ECS pro and install it again? Maybe there are some file missing from it.

**Comment by dudaster** [comment]
You said ECS Pro is not working. So is no harm in removing only ECS pro and install it back again. And also no settings would be lost.

At least in my experience.

**Comment by hoohum** [comment]
I’ve disabled, deleted, downloaded and re-installed the pro plugin and all is perfect now so thank you for your support.
Many thanks,
Barry.



On 28 Nov 2019, at 20:53, Liviu Duda <notifications@github.com> wrote:

You said ECS Pro is not working. So is no harm in removing only ECS pro and install it back again. And also no settings would be lost.

At least in my experience.

**Comment by dudaster** [comment]
You’re welcome!
