### ISSUE TITLE
Make column clickable conflict

### ISSUE THREAD

**Issue by ajlcomputers** [dudaster/ele-custom-skin#109]
Hi

When I create a custom loop skin and make the whole column clickable using this plugin

https://wordpress.org/plugins/make-column-clickable-elementor/

I get the following error in the first post item. All other post items in the grid work perfectly and are clickable as they should be

Warning
: Illegal string offset 'url' in
/home/whichgre/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php
on line
1176

**Comment by dudaster** [comment]
Use {{permalink}} keyword and it would solve the problem.

**Comment by florianace** [comment]
> Use {{permalink}} keyword and it would solve the problem.
Can you explain what do you mean by that?
I am having the same issue and I am using dynamic linking to post url.

**Comment by dudaster** [comment]
Can you provide an link to your website?

**Comment by florianace** [comment]
https://houseofdebt.org/

**Comment by florianace** [comment]
> Can you provide an link to your website?

https://houseofdebt.org/

**Comment by florianace** [comment]
Warning
: Illegal string offset 'url' in
/home/house628/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php
on line
1205

**Comment by florianace** [comment]
> Can you provide an link to your website?

This is happening when I set it up dynamically. If I put # or the website link, everything is fine. And I tried it with different plugins that add the link to column and same result.

**Comment by Albert99** [comment]
Hi, i have the same problem, ACF URL dont work with Elem Custom Skin and Make column clickable or Wrapper Link, etc...

Error: /wp-content/plugins/elementor/includes/base/controls-stack.php on line 1184 

And whats the solution to "Use {{permalink}} keyword and it would solve the problem."??

Any solution?

Thanks.

<a href="https://ibb.co/sPFvpyQ"><img src="https://i.ibb.co/dcQ0sG6/Captura-de-pantalla-2020-12-02-a-las-15-28-08.png" alt="Captura-de-pantalla-2020-12-02-a-las-15-28-08" border="0"></a>

**Comment by Albert99** [comment]
Temporal Solution (from: @TarunNarula);
https://github.com/dudaster/ele-custom-skin/issues/118

in:  wp-content\plugins\elementor\includes\base\controls-stack.php

Changing:
if ( $dynamic_property ) ) {
to
if ( $dynamic_property && isset($settings[ $control_name ][ $dynamic_property ]) ) {
