### ISSUE TITLE
Custom Skins Do not pull through translations - PolyLang

### ISSUE THREAD

**Issue by madbradj** [dudaster/ele-custom-skin#11]
![ele custom skins translations](https://user-images.githubusercontent.com/45303969/50546170-2ff8de00-0c1b-11e9-9ca7-26eb00bb8f58.JPG)

Let's say I have 2 loops:

Loop 1 (English) & Loop 1 (Portuguese) - Translated using Polylang. 

In the attached image, this is a "translated" loop -  Loop 1 (Portuguese). (using Polylang) in green is the dynamic content. (Content that was previously translated with Polylang in the WP Backend)

In red, is content that I manually added to the loop.  (Loop 1 (Portuguese))

On the front end the english version displays without any problems. But the Portuguese version also pulls through the english version. You can have a look at the attachments
![ele custom skins translations english](https://user-images.githubusercontent.com/45303969/50546245-71d65400-0c1c-11e9-87df-bbd689d80b61.JPG)
![ele custom skins translations portuguese](https://user-images.githubusercontent.com/45303969/50546246-71d65400-0c1c-11e9-8d8d-cd6809efd282.JPG)

.

**Comment by dudaster** [comment]
I know this is a issue but you can work around it by adding ele-conditions plugin and check and add this to your function.php theme:
```
add_filter( "eleconditions_vars",function($custom_vars){
	global $post;
	if (function_exists("pll_get_post_language")) $custom_vars["language"] = pll_get_post_language($post->ID, 'slug');
	return $custom_vars;
});
```

And after installing the Ele Conditions plugin you will be able to go to style tab of the widget and add a condition like:
`language == en`
and it will be sown only if the condition is met.

**Comment by madbradj** [comment]
Happy new Year

Thanks for the response.

I have added the code you sent to the functions.php file.

Added the condition to the template. both in EN template and PT template.

The english displays in the english but the Portuguese does not show at
all.

The condition for english is
language == en

The condition for Portuguese is
language == pt
