### ISSUE TITLE
Where is the problem

### ISSUE THREAD

**Issue by wulugod** [dudaster/ele-custom-skin#111]
I created a category field as a loop. I never had problems. If I took a look on my pages the category window is empty and there is just the post field without content.

Can you help me?

Best

**Comment by dudaster** [comment]
Can you please rephrase that? I don’t know what you mean by category field as loop.

Can you give me an example?

**Comment by wulugod** [comment]
Just created with Elementor and this app a loop.

I published the loop at many sites with elementor post widget.

It’s not displaying the content anymore.

**Comment by dudaster** [comment]
Can you provide me a link? Or some screenshots?

**Comment by wulugod** [comment]
Sure. 
<img width="560" alt="1" src="https://user-images.githubusercontent.com/58441815/70059195-a1d26800-15e0-11ea-84fd-d75cc1d4918b.png">
<img width="585" alt="2" src="https://user-images.githubusercontent.com/58441815/70059196-a1d26800-15e0-11ea-9578-fdb799c376ba.png">
<img width="1439" alt="3" src="https://user-images.githubusercontent.com/58441815/70059197-a1d26800-15e0-11ea-87bd-907ca9cdfcce.png">

**Comment by dudaster** [comment]
What should I do to reproduce this bug?
