### ISSUE TITLE
Feature Request: Custom Loop to select posts only from current logged in user

### ISSUE THREAD

**Issue by MartyFly** [dudaster/ele-custom-skin#112]
Hi, Would it be possible to query only the current logged in user when creating a template with a custom loop?

**Comment by dudaster** [comment]
Only the posts created by the current user?
Take a look here:
https://developers.elementor.com/custom-query-filter/

**Comment by MartyFly** [comment]
Thank you - I will take a look

**Comment by MartyFly** [comment]
Looks like just thing, their examples work. But I have no idea how to write
the query required to show only the posts for the current logged in user.

**Comment by dudaster** [comment]
check this out this link:
https://stackoverflow.com/questions/46930686/wordpress-get-current-logged-in-users-post-or-posts-with-edit-link

**Comment by MartyFly** [comment]
Thank you for being so helpful. I have examined the link for clues and
tried a few things, to no avail. The problem is, I am not a developer and
don't know what I am doing. I have a feeling that it's quite a simple
solution - I just can't get anywhere close. Can you help me with the code?

**Comment by MartyFly** [comment]
Hi - All sorted - all quite simple once unpicked!
I used:

add_action( 'elementor/query/my_custom_filter', function( $query ) {
// Get the user ID
        $author_id = get_current_user_id();
// Show per author
$query->set( 'author', $author_id );
} );

Thanks again for your help with this
Martin

**Comment by dudaster** [comment]
Super, I knew you can do it!

Bravo!
