### ISSUE TITLE
Image size problem with ACF fields

### ISSUE THREAD

**Issue by Infestix** [dudaster/ele-custom-skin#116]
Hello!

I have this interesting issue. While creating the loop template i have defined picture size as 448x448. At first the Posts widget with the loop it still decided to load full size pictures.

I eventually found out that i have to define picture ACF field as array not image URL. But when i use the same ACF field to to refer to Fullsize image download, it wont do a thing.

Q: Is there a way, where i could use the same ACF field for both displaying the picture in smaller size and directing to fullsize download?

![Screenshot (1)](https://user-images.githubusercontent.com/1818312/70506254-857b8180-1b32-11ea-9b0c-02d6db1a04da.png)
![Product image](https://user-images.githubusercontent.com/1818312/70506151-5238f280-1b32-11ea-8e88-fdc5b429204c.png)

**Comment by dudaster** [comment]
Ok. Is it working on single template for example?

**Comment by dudaster** [comment]
I think I found the problem. Set the ACF to return the id of the image instead of the url.

Let me know if solves your issue!

**Comment by Infestix** [comment]
Hello. ID of the image return error page with links. Anyway, i think i found temporary solution with separate ACF url fields.
