### ISSUE TITLE
Slider doesn't slide :)

### ISSUE THREAD

**Issue by ianandersonmedia** [dudaster/ele-custom-skin#120]
Hi,
Not sure what I'm doing wrong, but I have "Show in Slider" enabled. I have 5 posts and set "Slides to Show" to 5 so they all show. I have "Slides to scroll" set to 1.
In mobile mode, I have "Slides to Show" set to 1. But nothing happens when I click the arrow buttons on my mobile.
Even when I change "Slides to show" to 4 in desktop mode, the slider doesn't move.
I have "Columns" set to 1, but this doesn't seem to do anything when I change this number.
You can see the slider here: https://tcchurch.com.au/#about
Am I missing something?
Thanks
Ian

**Comment by dudaster** [comment]
I’ll check it out!

**Comment by dudaster** [comment]
Try to add infinite loop and also Try change the skin and test it a little bit.

**Comment by dudaster** [comment]
Any luck?

**Comment by ianandersonmedia** [comment]
Hi,
Changing to infinite loop doesn't do anything. And when I change the skin to a default one like Cards, I lose the slider options. If I try a different custom template, it still doesn't slide.
Thanks for your help.
Ian

**Comment by dudaster** [comment]
How many slides to scroll are selected?

**Comment by ianandersonmedia** [comment]
Slides to scroll is set to 1. 

Thanks

**Comment by dudaster** [comment]
Can you go and use the chat on dudaster.com ?

**Comment by ianandersonmedia** [comment]
Sorry, I’m not at my computer at the moment.

**Comment by dudaster** [comment]
I'm unable to reproduce it on my side... I need your coop to solve this. It seems that even when you switch to tablet/mobile view both navigation buttons have disabled attribute on them which it shouldn't happen.

**Comment by dudaster** [comment]
After taking a look at your example still couldn't figured why this happen.
I created a new Post Widget and styled it exactly as yours and it works perfectly. But if I copy style from the not working one to the working one the latter stops working too.

If I clear style (right click on the Post widget)  from the not working one it starts working. I seriously cannot put my finger on what turns into not working.

Let me know if you're still having issues with it.
