### ISSUE TITLE
2 column layout - odd number of rows results in split content

### ISSUE THREAD

**Issue by nuphunk** [dudaster/ele-custom-skin#124]
When viewed in safari the the content is split in half when there is an odd number of rows. (see image).
The elementor post widget is set to 1 column 
The columns are created  in the custom css (see below). The reason for this css is so the content will flow in across two columns like this:
1  3
2 4
...and not the default
1 2
3 4

test page [here](https://123.park-studio.com/test/)

@media screen and (min-width: 600px) {.price-column{
	-moz-column-count: 2;
	  -moz-column-gap: 30px;
	  -moz-column-rule: none;

	  -webkit-column-count: 2;
	  -webkit-column-gap: 30px;
		-webkit-column-rule: none;

	column-count: 2;
	column-gap: 30px;
	column-rule: none;

	}
<img width="1348" alt="Screenshot 2019-12-18 at 14 00 19" src="https://user-images.githubusercontent.com/5713405/71096053-90bf5480-21a5-11ea-8a98-b853c1ca0173.png">

**Comment by dudaster** [comment]
add this to the custom css to see if it works:

`selector .elementor-grid{ display:block; }`

**Comment by nuphunk** [comment]
Thanks! Sorted
