### ISSUE TITLE
Image Loading with Slider (Ele Custom Skin Pro)

### ISSUE THREAD

**Issue by clement-menard** [dudaster/ele-custom-skin#125]
Hello,

When i use "Show in slider" option for display posts, the first slides correctly display templates images, but when we click on the arrow, images are not displayed immediately... 

https://cutt.ly/mrwoqyP

**Comment by dudaster** [comment]
Indeed it seems to be an issue with lazy load. Are those images background? Can you try make them just images?

**Comment by dudaster** [comment]
hm... I think the issue here is entrance animation.  Can you get rid of it? It seems swiper.js is not fully compatible with animation.css

**Comment by clement-menard** [comment]
It works ! I disabled the "fade in" effect on the image, and it's good :)
Thanks for your feedback !
