### ISSUE TITLE
Tablet Version looks wonky

### ISSUE THREAD

**Issue by mrpiano** [dudaster/ele-custom-skin#126]
Hi there, I created a looped piece of content and then, using the Elementor Pro "post" widget, inserted the custom looped content into a page.  It looks exactly how I want on Desktop and Mobile, but, curiously, it goes to a 2 column layout on a tablet, which looks horrible.  On the "post" widget settings I have the post set to only display 1 column at a time, with a maximum of 4 posts on the page, so I want the posts to appear underneath each other, which they do, except on tablets.  Any idea how to get this to show up 1 column, 4 rows on tablet?  Not sure why's it's switching to a 2 column layout for tablet view.  See screenshots and thank you.  The first pic shows the tablet view, which forces the content to get very skinny and run really long down the page.  The second pic is mobile, which adheres to the 1 column, 4 row format.

Great plugin and I'm considering going pro today!

<img width="710" alt="Screen Shot 2019-12-19 at 7 43 46 AM" src="https://user-images.githubusercontent.com/11279313/71174605-9fece380-2233-11ea-95e9-356161d8e59c.png">
<img width="294" alt="Screen Shot 2019-12-19 at 7 43 29 AM" src="https://user-images.githubusercontent.com/11279313/71174606-9fece380-2233-11ea-8545-d491836e93db.png">

**Comment by dudaster** [comment]
Make sure Loop Template looks the way you want in Tablet/Mobile mode also.

**Comment by mrpiano** [comment]
ok, i'll start there...thank you and I'll be back with my findings!

**Comment by mrpiano** [comment]
yes, it looks correct in tablet mode as a single loop template.  works perfect until i embed the loop into a page with 4 posts.  Tablet view of the single template below.  

<img width="722" alt="Screen Shot 2019-12-19 at 7 50 25 AM" src="https://user-images.githubusercontent.com/11279313/71174971-61a3f400-2234-11ea-94ed-9f507baa2ba4.png">

**Comment by dudaster** [comment]
can you provide me a link?

**Comment by mrpiano** [comment]
yes, but I will have to add you as a user since the site is in maintenance mode.  is there a place where I can send that?

**Comment by dudaster** [comment]
dudaster.com through the messaging

**Comment by dudaster** [comment]
The issue that you have to select 1 column for tablet mode also
