### ISSUE TITLE
keywords not displaying in live mode

### ISSUE THREAD

**Issue by adriansn526** [dudaster/ele-custom-skin#127]
Hi, 
I bought the ele custom skin pro, i tried to display the {{index}} in a loop but is not displaying in live mode, is displaying just in the elementor editor.
![image](https://user-images.githubusercontent.com/54845178/71312920-e6139400-2439-11ea-8fef-708216bde131.png)

**elementor editor:**

![image](https://user-images.githubusercontent.com/54845178/71312934-2ffc7a00-243a-11ea-8b5e-b4b52cb7c25d.png)

**Live:**
![image](https://user-images.githubusercontent.com/54845178/71312959-633f0900-243a-11ea-85fe-bedf2e03c8f6.png)

**Comment by dudaster** [comment]
Ok I’ll take a look

**Comment by dudaster** [comment]
I'm unable to reproduce this behavior on my side. Can you provide a link to take a look?

**Comment by adriansn526** [comment]
Hi,i'm sorry, it was my mistake, I didn't realize that where I saw in live it was another page. The plugin works great but I wasn't able to reply to you. Thank you! Happy holidays!

**Comment by dudaster** [comment]
Glad to hear.

Sarbatori fericite!
