### ISSUE TITLE
how to set number of columns

### ISSUE THREAD

**Issue by Jacc4488** [dudaster/ele-custom-skin#131]
Hi , sorry i must be missing something... but after choosing the  custom skin loop template  i  seem unable to set the number of columns to display in the post grid.  it seems set a 3.  

please advise how to control the culumn number ?

**Comment by dudaster** [comment]
You should see a field columns right before the query section

**Comment by dudaster** [comment]
![Screen Shot 2019-12-28 at 8 11 05 AM](https://user-images.githubusercontent.com/8319178/71539752-c3a5dd00-2949-11ea-9de8-1a61c8032bb1.png)
