### ISSUE TITLE
1 column show slider on desktop does not work in pro :(

### ISSUE THREAD

**Issue by mirarosen** [dudaster/ele-custom-skin#132]
I just got pro because I saw you had the function slider on it. Sadly is when I try it now I cant set 1 column on it. See screenshot. 

Thats tha main pint of why got pro and now tried redo it many times in different ways but still for show in slider on desktop id does not work with one column. 

See screenshot https://drive.google.com/file/d/1OahD5nbLi0k_NZHqps2QjSJx9VAVUGI_/edit

It is a bug or something I did wrong? 

Please help,

Miranda

**Comment by dudaster** [comment]
You need to select slides to show
