### ISSUE TITLE
No loop tab visible after activation

### ISSUE THREAD

**Issue by sigersmit** [dudaster/ele-custom-skin#133]
Hi,
I bought the Unlimited pro version (some time ago) but when I install the plugin and activate it, there is no loop tab in the Elementor theme builder anymore. Any toughts on why this is happening?
Thank you!

**Comment by dudaster** [comment]
In order for the ECS pro to work you need to have the free one installed and activated as well.

**Comment by sigersmit** [comment]
Ah, missed that! Thanks for the very quick reply!
