### ISSUE TITLE
Filter Posts

### ISSUE THREAD

**Issue by fabioSarcona** [dudaster/ele-custom-skin#140]
I created a custom widget (loop) for my products using your plugin that I used in a page with search filters created with the Smart Filters plugin (By CrocoBlock).

What I can't understand is why the search filters don't work, changing the filter value doesn't change the result.

The test page is this: http://testcamperis.zensrl.it/offerta-nuovo/

I also created an Archive Page with the same filters but it seems that the Ajax call doesn't give any results.

It seems an incompatibility with Ele Custom Skin but I'm not sure.

do you know if there are compatibility issues with Smart Filters?

**Comment by dudaster** [comment]
Does it work with regular posts widget with classic skin?

**Comment by fabioSarcona** [comment]
Yes work: http://testcamperis.zensrl.it/test-page/

**Comment by dudaster** [comment]
Hm... I need to solve this issue. But first I need to buy a license.

**Comment by fabioSarcona** [comment]
I already have an active PRO license :)

**Comment by dudaster** [comment]
I already purchased it. Thanks!

**Comment by fabioSarcona** [comment]
I can provide the creds to access the backend. Where can I send the creds?

**Comment by dudaster** [comment]
hm... for me works... with post date

**Comment by dudaster** [comment]
If I select "Marca" (brand) filter, it works... isn't for you? If I select something else like "Sede" I get an js error.

**Comment by fabioSarcona** [comment]
on my side it doesn't work. Can you give me your email? I'll send you the creds.

**Comment by dudaster** [comment]
Go to dudaster.com and leave them in chat window!

**Comment by fabioSarcona** [comment]
done ;)

**Comment by fabioSarcona** [comment]
Problem solved. The fade in animation conflicted with the Ajax call and therefore this showed the results.

Thank you very much for your support
