### ISSUE TITLE
Columns number not apply

### ISSUE THREAD

**Issue by bislamovic** [dudaster/ele-custom-skin#141]
Hi,

I am using Show in Slider options and trying to have 6 columns but nothing happening while I'am changing numbers of columns:

![image](https://user-images.githubusercontent.com/21058182/73118220-9b61cc00-3f51-11ea-929a-7fcde8c873ca.png)

what I wanted to do is to have 6 columns without gap between:
![image](https://user-images.githubusercontent.com/21058182/73118237-d6fc9600-3f51-11ea-9640-269def252fb1.png)

**Comment by dudaster** [comment]
Your changing the wrong settings check out slide settings
