### ISSUE TITLE
overflow between slider and grid option

### ISSUE THREAD

**Issue by 1101blueli** [dudaster/ele-custom-skin#145]
Hello, I created a loop with a shadow and negative margin element
It work fine on Grid.
But when switch to slider, all those thing all crop. is it possible to be fixed by some simple css?
here is the link 
https://bit.ly/2HdSFZz

thanks

![Screenshot 2020-02-09 at 6 41 40 PM](https://user-images.githubusercontent.com/55223003/74100712-d0cf0200-4b6c-11ea-9b0f-9dc4ae1f9ab8.png)
![Screenshot 2020-02-09 at 6 43 31 PM](https://user-images.githubusercontent.com/55223003/74100713-d298c580-4b6c-11ea-846f-2ce7873ce74a.png)
![Screenshot 2020-02-09 at 6 05 33 PM](https://user-images.githubusercontent.com/55223003/74100711-cd3b7b00-4b6c-11ea-9c4b-45eb20858ee6.png)

**Comment by dudaster** [comment]
add some margins to the main section in Loop Template
