### ISSUE TITLE
ACF Color Picker not sticking to actual post

### ISSUE THREAD

**Issue by TheFoxGraphics** [dudaster/ele-custom-skin#148]
Hello,

I am using ACF color picker to change the background color of the overlay as seen here:
![Screen Shot 2020-02-17 at 10 14 53 AM](https://user-images.githubusercontent.com/34687058/74670435-c74a2900-516e-11ea-8aab-1940aa3ec5f9.png)

Each post has a different color selected to it. But when I place it as a grouped post widget and use the ele-custom-skin, it is choosing the latest color for the background and not the one for the actual post.
![Screen Shot 2020-02-17 at 10 15 12 AM](https://user-images.githubusercontent.com/34687058/74670510-f365aa00-516e-11ea-9ec6-2c139f96768d.png)

Any help would greatly be appreciated.

Thanks,
The Fox

**Comment by TheFoxGraphics** [comment]
I figured out a different solution. I created a new ACF field asking for a Unique ID. From there, I use the dynamic button to plug in that ID as the class field. Then within the custom css, I use the ACF shortcode to pull my code and place a period in front of it making it a class field. Definite work-around, but it accomplished what I was hoping to do.

Thanks,
The Fox

**Comment by dudaster** [comment]
Or with dynamic everywhere. But that’s a pro feature.
