### ISSUE TITLE
Can't get a loop to play as a slider using "Show in Slides" toggle

### ISSUE THREAD

**Issue by mrpiano** [dudaster/ele-custom-skin#150]
If you look at this page http://vipastra.websavvy.biz/ you will see three images right under the header

That is a loop, where I created ACF custom fields for the content, then did a loop template designing that element using dynamic tags to generate the content from the custom post type.

Then, I used the "posts" widget and selected "custom" for the content type.  I queried my custom post type and told it to show the content, in this case, I'm showing a maximum of 3 posts on the page.

What i want to do is show 1 post on the page at a time, and using the "show in slider" toggle button from your plugin, I want to scroll the content one post at a time like a slider element.

The problem is when I turn on the slider, 1 slide shows up, and then the next two are totally blank.  I think I'm doing this right, but not getting the result I was expecting.  Hoping to get some feedback on what I might try.  Thank you!

**Comment by dudaster** [comment]
You need to select slides to show to 1. Here columns don’t work. In the future releases when slider is checked I’ll disable columns.

Also when you’re using slider don’t use entrance animation. It does not behave properly that’s why you could see empty content because the entrance animation didn’t work.

**Comment by mrpiano** [comment]
Animations are off.  Still the same issue.  I have selected to show only 1
slide.  I get the first slide to work, then 2 blank ones still.  This was
kinda the reason we bought this plugin.  Anything else I can try?  Thanks!

**Comment by dudaster** [comment]
The issue seems to be because of the Stretch Section turned on. It's javascript conflicts with the slider's javascript.
