### ISSUE TITLE
Dynamic column background in loop template not working

### ISSUE THREAD

**Issue by chrisflink** [dudaster/ele-custom-skin#152]
Hi there,

I just bought the pro version of the template and am happy with the way things work, thanks!
There is however 1 issue that I cannot resolve.

If I use the featured image as column background in a loop template, then in the loop the first items image (or maybe just a random image?) is used for all items.

You can see what I mean on this page: https://nolost.nl/test-page/ (http access = nolost / 2020)
The php error log shows no errors or notifications.

Any idea how to fix this?

Kind regards,
Chris.

**Comment by dudaster** [comment]
are they made with ECS? the code source looks off.

**Comment by chrisflink** [comment]
Code might have looked different because powerpack posts widget was used. Now switched to normal elementor pro posts widget with custom loop template by ECS.
You can also check the "live" version on the bottom of this page which uses a carousel function: https://nolost.nl/analyses/strategisch-advies/
this (for now) has both background and image on top of each other.

**Comment by dudaster** [comment]
add a spacer inside the empty column.

**Comment by chrisflink** [comment]
This seems to work on the test page, but not on the final page (https://nolost.nl/producten/verzuimanalyse/) 
Any other thoughts?

**Comment by dudaster** [comment]
can you switch it to normal so I can take a look?

**Comment by chrisflink** [comment]
It is a grid now, thanks for checking

**Comment by dudaster** [comment]
This should be fixed with the ECS 1.4.0
