### ISSUE TITLE
Dynamic background not working if added from advanced tab

### ISSUE THREAD

**Issue by DODMax** [dudaster/ele-custom-skin#155]
If I selected featured image as dynamic background from the advanced tab, all the images are the same instead of being dynamic

![image](https://user-images.githubusercontent.com/1137276/75430894-947a0f00-597e-11ea-9b2d-ff8e5cb5fe0e.png)

**Comment by dudaster** [comment]
I'll take a look.

**Comment by dudaster** [comment]
Can I ask is it a widget or element?

**Comment by DODMax** [comment]
It's on a spacer.

**Comment by chrisflink** [comment]
It might be related to #152 
But that issues is also still open.

**Comment by dudaster** [comment]
The new update should fix it.
