### ISSUE TITLE
Elements and IDs duplicated when using Carousel

### ISSUE THREAD

**Issue by formulaclick** [dudaster/ele-custom-skin#156]
Hi! I'm PRO user and I have a posts slider with Carousel option activated, like this:
https://pasteboard.co/IWBDBr7.png

Apparently it works great, but I have a problem. Generated code cause me Accesibility errors because each post is duplicated on source code (I guess this is normal behaviour when using carousel) but also IDs are duplicated, and this is not a good practice at all and causes errors on Accesibility tests, which is important in some cases. See here:
https://pasteboard.co/IWBCjT4.png

Can this be solved? Thanks

**Comment by dudaster** [comment]
If you select infinite scroll the swiper javascript dublicates some posts to be able to scroll seamlessly.
The solution would be either to remove the infinite or feed more products to it.

**Comment by formulaclick** [comment]
Oh, that's true. Didn't know that option was enabled. Maybe it should be set to false by default? Thanks!

**Comment by dudaster** [comment]
I'll keep it in mind.
