### ISSUE TITLE
FOUC - content flashing when using EleSkin

### ISSUE THREAD

**Issue by mhage3** [dudaster/ele-custom-skin#16]
I am experiencing flickers or flash of unstyled content when using the Eleskin. I am using it to create a top blog post in an archive in one design and then another design for the remaining blog posts below. 

They both load simultaneously causing these flickers. 

Is there a way to control this with Eleskin. I tried loading the tempaltes CSS early with an action in the functions.php, but then the posts image disappears. 

Thanks for any help to avoid this issue.

**Comment by dudaster** [comment]
You are experiencing this issue still?

**Comment by mhage3** [comment]
Hi,

Yes - We minimized it with fast hosting and by enqueuing scripts - but without it still hampens. 

We have also had trouble related to WPML as a button string does not translate on the Frontend - even after having been translated in the backend. WPML are also looking into this. 

I do love the opportunity to work with loops and eleementor so besides this it is great. 

Martin

**Comment by dudaster** [comment]
Try using autoptimize plugin!

**Comment by mhage3** [comment]
We are, but it is only on the element created with eleskin, which is why I think it comes from there. 
Any clues as to why?

**Comment by dudaster** [comment]
With the WPML I’ll handle it in the future.

**Comment by dudaster** [comment]
Let me see your url. I’ll take a look when I have a little spare time.

**Comment by mhage3** [comment]
Hi Liviu, 

Thanks. I have been informed that WPML is trying to get in contact with you, as they probably have a fix. 

The link for the page is: https://momentum-gruppen.com/news/ <https://bowtie.mailbutler.io/tracking/hit/b4ef3caa-cbbf-473e-9118-c2719ac53fa0/36b2f71b-a4a2-4de1-bd9d-fefafe9a8bcc>

You will not experience it now, since we fixed it, but you can see the page. 

Have a nice day,

Martin

**Comment by dudaster** [comment]
Next week will be the next release hopefully WPML would be fixed then.

**Comment by mhage3** [comment]
Hi Liviu, 

That sounds great, thanks. 

One other thing I have been wondering: 

I wish to create a simple list og table view of posts that has a few custom fields created with Pods. So it would be something like title, custom field one, custom field two, link. But I would like to alternate the background color as it is often seen in tables. 
As I can see - this would demand two designs for the loop. How would you solve this? 

If it was just Wordpress posts, I guess you could use css class even / odd and then style the background, but I don’t think this is added to custom post types. 

Med venlig hilsen / best regards,

Digital Markedsføring ApS

**Comment by dudaster** [comment]
With ECS Pro you have alternating templates. If you don’t wanna a spend money you can try with Ele conditions and the global var $ecs_index.
