### ISSUE TITLE
Slider Posts Carousel always in 2 cols

### ISSUE THREAD

**Issue by formulaclick** [dudaster/ele-custom-skin#161]
Hi

After updating Elementor from 2.9.3 to 2.9.5 posts slider shows always in 2 cols instead of 4 or value you enter. See here: https://pasteboard.co/IYrC3gJ.png

If I try to set 4 columns, nothing changes in editor neither frontend. It happens to me on many sites.

Maybe is related to swipper library update?

2.9.4 – 2020-03-04
Tweak: Updated Swiper.js library to v5.3.6

Thanks

**Comment by dudaster** [comment]
You mean slides to show right?

**Comment by formulaclick** [comment]
Yes, sorry. The field you see on screenshot

**Comment by pippyn** [comment]
I have this too. Happens on all my sites.

**Comment by dudaster** [comment]
On my side too. Thanks for pointing it out! I'll work on a fix.

**Comment by dudaster** [comment]
Solved! The update would be available tomorrow.

**Comment by dudaster** [comment]
Update is out.
