### ISSUE TITLE
Number of columns for mobile not working in slider

### ISSUE THREAD

**Issue by chrisflink** [dudaster/ele-custom-skin#165]
We have a posts widget that slides through posts using ELE Custom Skin Pro.

The setting for number of columns on mobile doesn't work. We have set this to be 1, but it shows three columns. The tablet setting (also 1 column) is working.

You can see it in practice on this page:
https://nolost.nl/klantverhalen/samen-gelukkig-gezond-en-gedreven-bij-de-gemeente/

Scroll to the green section with "Activiteiten".

**Comment by dudaster** [comment]
Please update!

**Comment by garylevansjr** [comment]
I am having same issue. I'm using:

WP: 5.7.1
EL: Version 3.2.1
ECS: Version 3.0.0
ECSP: Version 3.0.0

Slider count when set to 1 on mobile, shows 3 columns.
