### ISSUE TITLE
issue with the order of my loop archives 

### ISSUE THREAD

**Issue by Emmilemmi** [dudaster/ele-custom-skin#167]
Hi, I have an issue concerning the order of my loop archives. I want them to be shown exactly in the same order like they are placed in my menue. But it doesn't work!  

http://2020.thetawaves-hamburg.de/wp-admin/post.php?post=17&action=elementor
and 
http://2020.thetawaves-hamburg.de/seminare/grundausbildung/

hope you can help!

Mareike

**Comment by dudaster** [comment]
This is an elementor issue per say but you can choose to use an plugin like Post Types Order. Just tried it and it works.
