### ISSUE TITLE
Post Content Widget Not Found in Your Template

### ISSUE THREAD

**Issue by mcmullencasey** [dudaster/ele-custom-skin#168]
When I active plugin, create a loop, then try to open any other page in my site, I get the error noted in the title: https://prnt.sc/rj433u

The only way to access a page is to disable Ele Custom Skin plugin.

I've tried disabling all other plugins (except Elementor and Elementor Pro) but I still get the error.

Can you help?

Thanks!

**Comment by dudaster** [comment]
do you have any Loop Templates created?

**Comment by mcmullencasey** [comment]
Thank you for your quick reply! Yes I do.

**Comment by dudaster** [comment]
If you delete it you still have this problem?

**Comment by mcmullencasey** [comment]
If I trash the loop then the other page loads, and the weird thing is - now the loop is showing.

**Comment by dudaster** [comment]
Does the loop have Any conditions?

**Comment by mcmullencasey** [comment]
The standard display condition "entire site". I removed it and that seemed to work.

**Comment by mcmullencasey** [comment]
I looked at other sites in which I've used Ele Custom Skin - loops on those sites have the default conditions set, but I don't get the error. Here's another site I just did, no errors: https://prnt.sc/rj639p

Wonder why the error was unique to this site?

Thanks for your help!

**Comment by dudaster** [comment]
It depends on the content, sometimes it gets in a infinite loop if you set it as archive and it calls itself. I’ll try to find a solution for this issues, meanwhile the best practice is to have no conditions. I know is frustrating that you need to select every time you save it but I’m on it.

**Comment by mcmullencasey** [comment]
No worries! If it is as simple as ensuring there are no conditions, I can definitely handle that! thank you again for your prompt support, and a great plugin!
