### ISSUE TITLE
 In the mobile version and the version for the tablet the layout and lack of breaks

### ISSUE THREAD

**Issue by ghost** [dudaster/ele-custom-skin#169]
in the mobile version and the version for the tablet the layout and lack of breaks, how to fix it?
![image](https://user-images.githubusercontent.com/46539627/77226184-065d0700-6b7f-11ea-9e6f-023cbaaf2b7b.png)
![image](https://user-images.githubusercontent.com/46539627/77226192-27bdf300-6b7f-11ea-8a51-f47d0b022a63.png)
![image](https://user-images.githubusercontent.com/46539627/77226199-30162e00-6b7f-11ea-86ca-e9df4c182f70.png)
14 pixels to the right - canceled

**Comment by dudaster** [comment]
Can you provide an URL?

**Comment by ghost** [comment]
> Can you provide an URL?
[Test](https://duit.orlov.studio/)

**Comment by dudaster** [comment]
Ca you point out what is missing? Like drive arrows on an image? Because I don’t see anything out of place.

**Comment by ghost** [comment]
Ok, video for you. In mobile version margins not work correctly.
[test.zip](https://github.com/dudaster/ele-custom-skin/files/4362860/test.zip)

**Comment by dudaster** [comment]
You are right. I’ll take a look to see if I can reproduce it. If you find a solution before me please let me know!

**Comment by ghost** [comment]
Unfortunately, I have not been able to fix this. I really hope for your help, since this is very important.

**Comment by ghost** [comment]
do you still have no ideas for this?

**Comment by dudaster** [comment]
try this: instead of adding margin to the column add padding to the section. This fixes it for me.

**Comment by dudaster** [comment]
The issue seems to be from the swiper.js library it happens with Image Carousel Widget from Elementor also.

**Comment by ghost** [comment]
@dudaster the problem is still relevant for me, it breaks my whole design, I am very disappointed, is there any solution?

**Comment by ghost** [comment]
Fixed. Thank you!
