### ISSUE TITLE
Make items same height 

### ISSUE THREAD

**Issue by sigersmit** [dudaster/ele-custom-skin#17]
Hi,
Thanks for the nice plugin. Is it possible to maken all the items the same height, regardless the size of the content? I already set the height to stretch, but that doesn't seem to make a difference.
Thanks!

**Comment by Greatwhitepixel** [comment]
Yep, this!!... ^^

I have the same question.....I love the fact that this exists...great plugin with potential.....

**Comment by yoavshai** [comment]
Same question here. I've been trying to figure this out for the past couple of days.
Thanks!

**Comment by yoavshai** [comment]
Did anyone find a solution to this issue?

**Comment by dudaster** [comment]
add minim height property, use your imagination!

**Comment by formulaclick** [comment]
Same issue here. I've bought PRO version and I excepted to be solved. @dudaster I've tried minim height but this is not a perfect solution, will not work in some situations because loops contain dynamic content. Isn't there (or will be) any better solution? Thanks

**Comment by dudaster** [comment]
This would be a feature in pro in the near future.

**Comment by asleepfromday** [comment]
> This would be a feature in pro in the near future.

If this is available in Pro, I would happily buy this plugin right away!

**Comment by dudaster** [comment]
This feature made it to ECS Pro along with Masonry and Slider
