### ISSUE TITLE
Override Product Archive

### ISSUE THREAD

**Issue by bakedmellow** [dudaster/ele-custom-skin#175]
I would like to override Product Archive, which seems that doesn't work. Defeats the purpose of me using the plugin. I am aware you can add it to post archive, change to products, but I need the product filter and search for products.

Help please hehe, thanks in advance.

**Comment by dudaster** [comment]
Have you allready whatched this tutorial: https://www.youtube.com/watch?v=qUF7HLdcjlg&t=5s ?

**Comment by bakedmellow** [comment]
Yes, I checked out that tutorial. That only works for Post Archives, not Product Archives...

**Comment by dudaster** [comment]
Product archive widget or template?

**Comment by TChord22** [comment]
Template

**Comment by bakedmellow** [comment]
The Product Archive widget on Elementor. Trying to override woocommerce default shop layout

**Comment by dudaster** [comment]
Unfortunately the Elementor's Post Archive Widget is just a shortcode generator for woocommerce. So it doesn't at all work like Posts Widget.

I'll have in mind in the future to add more features for woocommerce archives. Please write here all the features you want included here and I'll try to include them.

**Comment by bakedmellow** [comment]
That is a bummer, however I am happy that you are looking to expand this plugin. Gives me great joy. The plugin works overall nice for blog pages, single product pages, however its just missing the woocommerce factor overall. Woocommerce has always been an issue on editing, giving a different look and feel, if you could possibly allow this plugin to override Woocommerce Product Archive Widget/Template that would be really nifty, would help out so many developers or designers in the future on elementor. 

Thank you for your responses and looking forward to the changes.
