### ISSUE TITLE
Have to Disable and Enable Plugin After Each Loop Update

### ISSUE THREAD

**Issue by andrewwpaction** [dudaster/ele-custom-skin#178]
Hi, 
Each time I do an update to a loop template I have to disable the Ele Skin Plugin, refresh the page then re activate the plugin to get the page to display. The plugin was working fine. 

The strange thing it appears to only happen on my home page and not other pages that are using a loop template. 

If I try to edit the page after doing an update to a loop template I get an error : "The Post widget was not found in your template".  If I disable the Ele Skin Plugin, refresh the page then re activate again, everything goes back to norman, of course until I edit a template again.

I am a pro user, just purchased today. Love the plugin just need to solve this issue please. The site is up and running at the moment.

Let me know what you need to look into is issue please.

Site: reefmarine.net
Page with issue: home page.

Reards Andrew Matsen.

**Comment by dudaster** [comment]
it is wierd please go on dudaster.com and use the chat there!

**Comment by dudaster** [comment]
Meanwhile make sure you don't have any display conditions on loop templates

**Comment by andrewwpaction** [comment]
Thanks for your help on Messenger. Problem solved.

**Comment by andrewwpaction** [comment]
Thanks heeps
