### ISSUE TITLE
Fatal error when disabling elementor pro

### ISSUE THREAD

**Issue by crazypsycho** [dudaster/ele-custom-skin#18]
Hello,

If you disable Elementor Pro, you get an fatal error and have to delete ele-custom-skin from server.

Fatal error: Class 'ElementorPro\Modules\Posts\Skins\Skin_Base' not found in D:\Projekte\myProject\wp-content\plugins\ele-custom-skin\skins\skin-custom.php on line 15

Thank you

**Comment by teoeugene** [comment]
I have this issue too with the latest version of Ele Custom Skin and Pro. There should be a check to ensure that Elementor Pro is enabled in case if it's disabled before disabling ECS first.

**Comment by dudaster** [comment]
Thanks for poiting this out. I'll release an update today.

**Comment by dudaster** [comment]
Fixed.
