### ISSUE TITLE
Post Excerpt widget does not work on Loop template

### ISSUE THREAD

**Issue by nullmem** [dudaster/ele-custom-skin#180]
Brand new install, hello-elementor theme and Post Excerpt widget does not work on Loop template. Post Content widget works fine.

**Comment by dudaster** [comment]
Does your post have an excerpt? You can use dynamic value post summary.

**Comment by nullmem** [comment]
Read more widget don’t work either. The archive shows excerpt with no Elementor template and just theme. Text widget won’t work for me.

**Comment by dudaster** [comment]
When you design a single template the excerpt is working?

**Comment by nullmem** [comment]
It seems both excerpt and read more don’t work on single as well. This is strange, I have no idea why they don’t work.

**Comment by dudaster** [comment]
excerpt is that separate field from content right?

If you want a shortened content you should use Post summary dynamic field.

**Comment by nullmem** [comment]
Yes. I ended up using post summary field of text widget like you suggested. The Post Excerpt widget is broken on single page template as well, so it seems to be a Elementor core issue.

**Comment by nullmem** [comment]
Apparently I am not the only one that thought Post Excerpt widget should work in the way I expected.

https://github.com/elementor/elementor/issues/10795

**Comment by nauticlab** [comment]
I have the same problem too. You solved?

**Comment by nauticlab** [comment]
Hello Elementor + Elementor + Elementor PRO

**Comment by dudaster** [comment]
This is not a issue or bug. Post excerpt is a field of a post if it is empty then It will not show. Is this the case?

What you need is post summary. That means you need to use a text widget with dynamic value as a post summary. The post summery
