### ISSUE TITLE
Support for Elementor Custom Skins in Atra theme?

### ISSUE THREAD

**Issue by tyrichins** [dudaster/ele-custom-skin#184]
I switched to Astra theme because is was touted for great support for Elementor. However, the loops I created previously, which worked in other themes, do not work in Astra theme.

I get the following error, and I can no longer edit the loop template with Elementor. 

"The Post Content Widget was not found in your template
You must include the Post Content Widget in your template (Loop), in order for Elementor to work on this page."

The loop is not recognized as a custom skin in Elementor blocks such as Posts. They worked great before Atra. Has anyone come across this issue before? Any workarounds?

**Comment by dudaster** [comment]
It will be fixed in the next version but you don’t want to wait make sure you don’t heva displaying conditions on any of loop templates.

**Comment by tyrichins** [comment]
Thank you. What do you mean by "displaying conditions on any of loop templates"? The loop template uses dynamic tags. the only time I specify a query is in the Post block - like only showing "featured" posts.

When do you hope to get the next version out?

**Comment by dudaster** [comment]
https://docs.elementor.com/article/311-conditions

**Comment by tyrichins** [comment]
Thank you. Removing the condition worked! Great support
