### ISSUE TITLE
Can't Create Loop Template: the_content function Not Found

### ISSUE THREAD

**Issue by emeraldsama** [dudaster/ele-custom-skin#187]
Hey there, this plugin is no longer working for me after version 2.X, and through the most recent version (2.0.2). I cannot create a loop template, and I get the following error. 

"you must call the_content function..."

<img width="413" alt="error ele custom skin" src="https://user-images.githubusercontent.com/4933651/80008174-5e946b00-8495-11ea-8c09-75dd6eed9a77.png">

I am running on the most recent version of Wordpress (5.4), and the only plugins active are Elementor, Elementor Pro, and Ele Custom Skin. It works fine if I roll Ele Custom Skin back to v 1.4.0. Not sure what my issue is?

Thanks!

**Comment by dudaster** [comment]
Please make sure you don’t have a single template that has the condition set for the entire site

**Comment by tyrichins** [comment]
I had the same problem. As dudaster suggested, I removed the condition for the loop template and it worked just fine.

**Comment by emeraldsama** [comment]
Ah - that was my problem. Seems to be working as expected now. Thanks for the quick reply!

**Comment by dudaster** [comment]
still having this issue?

**Comment by emeraldsama** [comment]
Nope you're good. Thanks!
