### ISSUE TITLE
Where had the slider option gone

### ISSUE THREAD

**Issue by Gingerandtall** [dudaster/ele-custom-skin#188]
I've created a custom skin, but cant see how to activate them as a slider? Has it moved in the 2.0 version?

**Comment by dudaster** [comment]
What version do you have?

**Comment by Gingerandtall** [comment]
Version 2.0.2

**Comment by dudaster** [comment]
And pro version ?

**Comment by Gingerandtall** [comment]
yeah

**Comment by Gingerandtall** [comment]
![Untitled-1](https://user-images.githubusercontent.com/64219037/80128044-0f316600-858d-11ea-8b42-0a3213dd2410.png)

**Comment by Gingerandtall** [comment]
its now back! pro just updated to 1.3.3
