### ISSUE TITLE
How to put Woocommerce Badges inside Ele Custom Skin Loop Product

### ISSUE THREAD

**Issue by Black443-IL** [dudaster/ele-custom-skin#189]
Hi

I'm trying to put on a loop elementor image a "woo badge", a plugin, not the woocommerce built in feature. is it Possible? 

The Elementor image is dynamic and set up to collect woocommerce image product.

it looks that it's not working on my end.

It's working on a single product and on Archive/Shop/Other Page 

I have the free version of Ele Custom Skin.

This is the loop page
https://myisraelbooks.com/hebrew-from-scratch/

This is the product page where the badge is working:
https://myisraelbooks.com/product/hebrew-from-scratch-part-a-sipur-ve-od-sipur/

This is the the product page where the badge is working:
https://myisraelbooks.com/product-category/magnes-academon/

Please advise

**Comment by dudaster** [comment]
You can do this first by creating a short code of a badge using the following code inside your child theme functions.php file:

`add_shortcode('ecswoobadge', 'woocommerce_show_product_sale_flash');`

After that go to the Loop Template and add a Shortcode Widget and use `[ecswoobadge]` shortcode.

From the Shortcode Widget go to Advanced > Postioning and set it to absolute. There you can try to tweak the values to put it where you want.

Also If you want to see the way it looks in **Loop Template** add to the main section the class .woocommerce (without the dot)

**Comment by Black443-IL** [comment]
Thank you.

The short code is not good - it gives me debug mode

_________________________________________________

There has been a critical error on your website.

Learn more about debugging in WordPress.

Uncaught Error: Call to a member function is_on_sale() on null in
/home/myiskfeg/domains/
myisraelbooks.com/public_html/wp-content/plugins/woocommerce/templates/single-product/sale-flash.php:25
Stack trace:
#0 /home/myiskfeg/domains/
myisraelbooks.com/public_html/wp-content/plugins/woocommerce/includes/wc-core-functions.php(251):
include()
#1 /home/myiskfeg/domains/
myisraelbooks.com/public_html/wp-content/plugins/woocommerce/includes/wc-template-functions.php(1565):
wc_get_template('single-product/...')
#2 /home/myiskfeg/domains/
myisraelbooks.com/public_html/wp-includes/shortcodes.php(343):
woocommerce_show_product_sale_flash('', '', 'ecswoobadge')
#3 [internal function]: do_shortcode_tag(Array)
#4 /home/myiskfeg/domains/
myisraelbooks.com/public_html/wp-includes/shortcodes.php(218):
preg_replace_callback('/\\[(\\[?)(ecswoo...', 'do_shortcode_ta...', '

_______________________________________________________________________

*תמר בלק*
*Tamar Black*
Graphic Design
052-8890219
www.tamarblack.com

**Comment by dudaster** [comment]
Try this instead, it works only with woo badges plugin:

```
function ecs_woo_badge(){
	global $product;
	if(!$product) return;
	$wobd_common_settings = get_option( 'wobd_common_settings' );
	$wobd_post_id = $wobd_common_settings[ 'wobd_default_sale_badge' ];
	if ( isset( $wobd_post_id ) && $wobd_post_id != 'none' ) {
		$wobd_option = get_post_meta( $wobd_post_id, 'wobd_option', true );
		include(WOBD_PATH . 'includes/frontend/badge-content.php');
	}

}
add_shortcode('ecswoobadge', 'ecs_woo_badge');
```

**Comment by Black443-IL** [comment]
Thank you.

Issue solved


*תמר בלק*
*Tamar Black*
Graphic Design
052-8890219
www.tamarblack.com

**Comment by dudaster** [comment]
the final code for the shortcode for woo badge widget is:
```
function ecs_woo_badge(){
	global $product;
	if(!$product) return;
	$post_id = $product -> get_id();
	$wobd_advance_option = get_post_meta( $post_id, 'wobd_advance_option', true );
	print_r($wobd_advance_option);
	$individual_badges = isset( $wobd_advance_option[ 'wobd_badge_each_position' ] ) ? esc_attr( $wobd_advance_option[ 'wobd_badge_each_position' ] ) : 'none';
	if ( $individual_badges != 'none' ) {
		$wobd_post_id = $wobd_advance_option[ 'wobd_badge_each_position' ];
		$wobd_option = get_post_meta( $wobd_post_id, 'wobd_option', true );
		include(WOBD_PATH . 'includes/frontend/badge-content.php');
	}
	include(WOBD_PATH . 'includes/frontend/custom-design.php');

}
add_shortcode('ecswoobadge', 'ecs_woo_badge');
```

**Comment by hunain521** [comment]
> 
> 
> the final code for the shortcode for woo badge widget is:
> 
> ```
> function ecs_woo_badge(){
> 	global $product;
> 	if(!$product) return;
> 	$post_id = $product -> get_id();
> 	$wobd_advance_option = get_post_meta( $post_id, 'wobd_advance_option', true );
> 	print_r($wobd_advance_option);
> 	$individual_badges = isset( $wobd_advance_option[ 'wobd_badge_each_position' ] ) ? esc_attr( $wobd_advance_option[ 'wobd_badge_each_position' ] ) : 'none';
> 	if ( $individual_badges != 'none' ) {
> 		$wobd_post_id = $wobd_advance_option[ 'wobd_badge_each_position' ];
> 		$wobd_option = get_post_meta( $wobd_post_id, 'wobd_option', true );
> 		include(WOBD_PATH . 'includes/frontend/badge-content.php');
> 	}
> 	include(WOBD_PATH . 'includes/frontend/custom-design.php');
> 
> }
> add_shortcode('ecswoobadge', 'ecs_woo_badge');
> ```

not working

**Comment by hunain521** [comment]
![Capture](https://user-images.githubusercontent.com/74041269/98363523-e7997b00-2050-11eb-838b-9475daf44103.PNG)
please resolve this issue
