### ISSUE TITLE
Same-height function not working

### ISSUE THREAD

**Issue by nine2uk** [dudaster/ele-custom-skin#190]
Hi Guys,

I'm using the same-height function on a custom skin and it appears not to be working on some 'almost random' columns.

Can you shed any light as to why that might be?

**Comment by dudaster** [comment]
I can see... It behaves strangely because of the height of the heading widget.

I'll check it out further.

**Comment by dudaster** [comment]
can you export please the template?

**Comment by nine2uk** [comment]
Of course, do you have an email I can send it over to?

**Comment by dudaster** [comment]
Attach it here please!

**Comment by ste70** [comment]
Hello
Same problem, on and off

![Screenshot (23)](https://user-images.githubusercontent.com/51832365/80421418-be977100-88dc-11ea-99b2-2ac566ae4b47.png)
![Screenshot (22)](https://user-images.githubusercontent.com/51832365/80421419-bfc89e00-88dc-11ea-876f-be9afa204f6a.png)

**Comment by dudaster** [comment]
You need to use only one main section not two

**Comment by ste70** [comment]
You are right, thank you

**Comment by nine2uk** [comment]
Attached here for you!

[dudaster-tests.zip](https://github.com/dudaster/ele-custom-skin/files/4542206/dudaster-tests.zip)

**Comment by dudaster** [comment]
For me works well: https://clean.ehot.ro/same-height-problem-page/
Must be a css that screws things up... I'll dig up a little more.

**Comment by nine2uk** [comment]
Hmm, how annoying! - Thank you I appreciate your help with this.

**Comment by dudaster** [comment]
I know it is a long shot, but can you change the font?

**Comment by nine2uk** [comment]
I've changed it to Ariel - same issue, unfortunately: http://thegarage.nine2demos.co.uk/shows/

**Comment by dudaster** [comment]
Yeah... Still digging.

**Comment by dudaster** [comment]
It will be helpfull if you can use the chat on dudaster.com

**Comment by dudaster** [comment]
I found the problem:

thegarage.nine2demos.co.uk/wp-content/themes/almighty-wp/style.css at line 38:
```
.elementor-section {
    padding-left: 20px !important;
    padding-right: 20px !important;
    margin: 10px 0;// <-this line causes the trouble
}
```
It seems Flex display and margin don't get well with each other.

**Comment by nine2uk** [comment]
Perfect!

**Comment by ghost** [comment]
Adding my issue here on same height not working on published site (while Elementor editor showing it correctly).

All items in the custom post were added in one section. Was wondering with anyone else facing this too?

**Comment by dudaster** [comment]
Post your url here and let’s take a look!

**Comment by ghost** [comment]
https://sportsnutritionistjames.com/articles/

**Comment by dudaster** [comment]
this is the issue:
Generate press adds this css:

.post {
    margin: 0 0 2em;
}

It seems Flex display and margin don't get well with each other.

Please make sure it has margin:0;
