### ISSUE TITLE
Ele Custom Skin 2.0.2 Breaks Elementor Form Submissions !!

### ISSUE THREAD

**Issue by kaelansmith** [dudaster/ele-custom-skin#192]
This is a significant bug: Any page that has a Posts widget with Ele Custom Skin enabled, and which also has a regular Elementor form, has a conflict that causes the form to not submit. Error shown upon submitting form: "There's something wrong. The form is invalid."

I've tested removing the Posts widget from the page (with Ele Custom Skin enabled), and the form then worked. I've tested deactivating Ele Custom Skin, and the form then worked. I've tested on two different websites, same issue. I've tested with the following versions of Ele Custom Skin and Elementor/Elementor Pro:

ECS v. 1.3.1 + Elementor v. 2.9.4 + Elementor Pro v. 2.8.4. .... and this combo worked!

As soon as I updated ECS to 2.0.2, the form broke. I've also tested ECS v. 2.0.2 with the latest versions of Elementor (2.9.7 + PRO 2.9.3) and the form submissions still don't work.. So I'm 100% sure the issue is with Ele Custom Skin 2.0.2. 

Please fix ASAP! I suspect there are tons of websites out there with broken forms, and they probably don't even know it!

**Comment by dudaster** [comment]
Thanks! I'll take a look.

**Comment by dudaster** [comment]
Found the problem. It is fixed. The update would be available tommorow.
