### ISSUE TITLE
Post Slider Problems

### ISSUE THREAD

**Issue by tibacreative** [dudaster/ele-custom-skin#195]
I have a problem when it comes tot he "Post-Slider".

DevTools says:

„DevTools failed to load SourceMap: Could not load content for **wp-content/plugins/elementor/assets/lib/swiper/swiper.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE"
 
On mobile-mode it adds a gap / padding under the slider, in the first page/slide  the second slide is fine.

**Comment by dudaster** [comment]
Can you provide an url so I can take a look?

**Comment by tibacreative** [comment]
Currently Staging Environment behind a login.

**Comment by dudaster** [comment]
I'll try then to reproduce it on my end then:

What theme are you using?
What versions of elementor and Ecs are you using?

**Comment by tibacreative** [comment]
I'm using "Hello Elementor" and everything is Up To Date. Next Slider Problem is: There's a Gap in Firefox. I can give you Login-Data via E-Mail if you like?

**Comment by dudaster** [comment]
Set column and row gap to 0

**Comment by tibacreative** [comment]
> Set column and row gap to 0

Not working

**Comment by dudaster** [comment]
Use the chat on dudaster.com to give the details for login.
