### ISSUE TITLE
Ajax issue with custom skin loop template

### ISSUE THREAD

**Issue by standiers** [dudaster/ele-custom-skin#198]
Hi, when I use the loop or skin I created with your plugin, nothing displays when filtering the posts using the Jet Smart Filters for Elementor Pro. 
It works fine when I use any of the Elementor skins, or if I use page reload method. So the issue appears when using Ajax or mixed method.

I don't have any animations on the loop template, nor on the page where applied.
Similar issue: https://github.com/dudaster/ele-custom-skin/issues/177
and: https://github.com/dudaster/ele-custom-skin/issues/159

**Comment by standiers** [comment]
Hi, I decided to try to rebuild my loop from scratch thinking maybe there is a glitch in the one I built. Turns out using the new loop with a different name solved all the Ajax issue I had.
So I went back to the original loop to see each element in details. I applied the same settings to my new skin 1 by 1, but never could reproduce the issue.

When I switched back to the old skin, everything works, no more Ajax issue.
It is a bit of a mystery, perhaps a glitch happened due to custom fields which could be resolved... To anyone having similar issue, I would suggest to rebuild a skin from scratch to see if it solves it. Avoid copy/paste styles.

**Comment by standiers** [comment]
Hi, turns out my problem reappeared. I think it is because I edited my loop/skin since then. It would be nice to get some support here...

**Comment by dudaster** [comment]
Did you update anything?

**Comment by standiers** [comment]
Elementor Pro is v.2.9.5, Elementor is v.2.9.11.
Ele Custom Skin is v.2.2.0 and Ele Custom Skin Pro is v.2.1.0
Jet Smart Filter is v.1.8.1.

When my Post block skin is set to any of the 3 default ones, the jet smart filters with Ajax work perfectly. When I use the custom skin I made, Ajax doesn't work and returns no different results (the grid of post remains the same). If I use "page reload" and the apply button, it works.

I tried giving the div attribute to my skin/loop as suggested in another thread, but no luck.

**Comment by dudaster** [comment]
Can you please write on their support also. Their Ajax returns an error. I’ll take a look myself in the meantime.

**Comment by dudaster** [comment]
If you downgrade ECS to 2.1.0 does it work again?

**Comment by standiers** [comment]
I am reaching out to Jet smart Filter support now.
What is the best way to downgrade to ECS 2.1.0 without loosing anything?

**Comment by dudaster** [comment]
Delete it and you won’t loose anything

**Comment by standiers** [comment]
ok, where can I find the version 2.1.0?
** sorry, just realise this is the version I have of ECS pro.

**Comment by dudaster** [comment]
https://wordpress.org/plugins/ele-custom-skin/advanced/

Go to the bottom of the page!

**Comment by standiers** [comment]
I deleted ECS 2.2.2 and installed 2.1.0
Now even the "on page reload" using the apply button doesn't work. Nothing happens..

**Comment by dudaster** [comment]
can you  provide an url?

**Comment by standiers** [comment]
On my local environment, I had a previous version which was working fine. It is worth noting that it is the same version of jet smart filter as now (which removes it as an issue).

It stopped working when I update ECS pro from 2.0.0 to 2.1.0
So I assume the issue is in the latest version of ECS pro.

(sorry the site is behind a coming soon)

**Comment by dudaster** [comment]
Can you disable ecs pro and see if it works?

**Comment by standiers** [comment]
no it doesn't.
Ok so the only thing that works is:
- ECS version 2.1.0
- or the combo ECS 2.1.0 and ECS pro 2.0.0

anything else doesn't work.

**Comment by dudaster** [comment]
Someone find the problem. So I'll implement soon the solution. Please check it out: #223

**Comment by dudaster** [comment]
Released 2.2.1 let me know if it works now.

**Comment by standiers** [comment]
I confirm the update to ECS 2.2.1 fixed the issue with Ajax and Jet Smart Filter. Thank you!
