### ISSUE TITLE
loop template not found

### ISSUE THREAD

**Issue by lemartinet** [dudaster/ele-custom-skin#2]
Hi,
Sorry for duplicate post on the wordpress plugin forum. I’ve created a new loop template and published it without any conditions. However when I add the posts widget and select custom skin, there is nothing there.
Any idea why?
Thanks

**Comment by dudaster** [comment]
Can you make me a screenshot please?

**Comment by lemartinet** [comment]
Hi,
thanks for your answer. Here is a screenshot. The "select template' is not
empty actually, it gives back the title of a single article in another
language (I use wmpl to manage french and english). Looking through your
code, I'm wondering if something is wrong in the wp query looking for the
loop template, but I am not too sure what to change.

Thanks for any feedback!

**Comment by dudaster** [comment]
Didn't see the screenshot but I think is because of wmpl.
Thanks I'll patch it up.

**Comment by dudaster** [comment]
done some tests with wpml and it works. Try to deactivate plugins one by one and let me know which one it's to blame so I can fix it.

Thanks!

**Comment by lemartinet** [comment]
![screen shot 2018-05-18 at 1 24 34 pm](https://user-images.githubusercontent.com/7539986/40317377-4d556490-5cef-11e8-9368-00876de87b9f.png)
Sorry for the screenshot.
I can't test deactivating wpml because it can mess up the database, sorry.

**Comment by dudaster** [comment]
is there a way you can give me access to your wp-admin so I can take a look?

**Comment by dudaster** [comment]
this is actually the code that searches for the loop posts : 

`$templates = $wpdb->get_results( 
					"SELECT $wpdb->term_relationships.object_id as ID, $wpdb->posts.post_title as post_title FROM $wpdb->term_relationships 
					INNER JOIN $wpdb->terms ON 
						$wpdb->term_relationships.term_taxonomy_id=$wpdb->terms.term_id AND $wpdb->terms.slug='loop'
					INNER JOIN $wpdb->posts ON
						$wpdb->term_relationships.object_id=$wpdb->posts.ID"
				);`

**Comment by lemartinet** [comment]
That's what I tought. The SQL request doesn't work, probably due to some
interactions with WPML... See the screenshot, same results as the
screenshot within elementor editor

Let me know if you have ideas to edit this SQL query

**Comment by lemartinet** [comment]
Ok just a little bit more research... It seems there is a pb with the term_id.
If I start from wp_post to search the skin post (called "simplemag loop"), here is what I get the ID 50586:
![screen shot 2018-05-22 at 1 19 56 pm](https://user-images.githubusercontent.com/7539986/40379191-87e63af6-5dc3-11e8-8f89-a1d9383d5a58.png)

Then if I search for this ID in the terms relationship I get the term_taxonomy_id 855:
![screen shot 2018-05-22 at 1 22 06 pm](https://user-images.githubusercontent.com/7539986/40379305-c56c248a-5dc3-11e8-9a15-e0dfefc63835.png)

However, there is no 855 in wp_terms. The only loop item is 849:
![screen shot 2018-05-22 at 1 14 54 pm](https://user-images.githubusercontent.com/7539986/40379501-41a13d1a-5dc4-11e8-8e73-911eabe0ddd0.png)

Let me know if you understand what I did and if you know how this disconnect could happen (difference in the IDs 849 vs 855)

**Comment by lemartinet** [comment]
Gotchat! There are no problems with the IDs, I think I figured the right SQL request:

SELECT wp_term_relationships.object_id as ID, wp_posts.post_title as post_title 
FROM wp_term_relationships
INNER JOIN wp_term_taxonomy ON wp_term_relationships.term_taxonomy_id=wp_term_taxonomy.term_taxonomy_id
INNER JOIN wp_terms ON wp_term_taxonomy.term_id=wp_terms.term_id AND wp_terms.slug='loop' 
INNER JOIN wp_posts ON wp_term_relationships.object_id=wp_posts.ID

I added an additional INNER JOIN to wp_term_taxonomy because that is where the relationship between 855 and 849 was encoded.
I tried added another loop item and then with my SQL query I can see both of them now.
![screen shot 2018-05-22 at 1 48 41 pm](https://user-images.githubusercontent.com/7539986/40380426-0aebe4e8-5dc7-11e8-84c9-da39b0910d2a.png)

Let me know if that makes sense and if so if you can update the plugin.
Thanks!

**Comment by dudaster** [comment]
Spot on! You are right. I think this is not because of a wpml problem, it seems the issues was that I supposed from the begining that `term_taxonomy_id = term_id` which is not the case. 

Thanks for the help!

**Comment by dudaster** [comment]
The new version is up.

Thanks for your help!
