### ISSUE TITLE
FB sharing unable to find the correct post featured image (no og:image)

### ISSUE THREAD

**Issue by karrolhk** [dudaster/ele-custom-skin#200]
Hi, I made a loop template using your plugin (Elementor Custom Skin).  In the template, I put social icons (e.g. FB) with a link (eg. https://www.facebook.com/sharer/sharer.php?u=http://example.com/) to share to FB.  I have checked about 8 of my posts with images, only 6 of the featured image are shared correctly, the other 2 featured images fail to find the right featured image.  I have cleared cache, put my link through FB debugger but the problem is still the same.   Sometimes a post featured image is shared correctly, sometimes it shares the image of another post.  

So, to find out what the problem is, I inspected the code of my page and could not find the og:image code.  I then ran a "Site Health" check of my site to check for plugin conflict by enabling only Elementor, Elementor pro and Elementor Custom skin plugins.  But the issue of not finding the right featured image persists and I also could not find the og:image code when I inspect the page.  So, I suspect your plugin may have a conflict or problem that does not allow me to share the social content?  Could you please check?

**Comment by dudaster** [comment]
I don't think is an Ele Custom Skin Related issue. Facebook does caching on pages and when you try to share it without an image it caches without an image or the wrong image.

Please take a look at this article: https://modernpics.net/clearing-the-facebook-image-cache-6e2ad6b93edb

**Comment by karrolhk** [comment]
Thanks for your reply.  As I said, I have already cleared FB cache using the FB debugger link.  But, it didn't work.  I just tried again to make sure and it wrongly displays the featured image of another post, saying: "Provided og:image URL was not valid because it did not meet the minimum size constraint of 200px by 200px."  But this is not true.  All my images are of the same size, 640 x 340 px.

The strange thing is the image is accurately shown for some posts, but not other posts.  It is inconsistent.  You can go to my site and try to share the posts with images.. 3 out of 8 times you will share the wrong image (it pulls the wrong image from another post).  

I have attached a screenshot of the error message from fb debugger.

**Comment by karrolhk** [comment]
![FB debugger](https://user-images.githubusercontent.com/64810663/81103413-fefb7e00-8ede-11ea-8c15-aeb3a4eacf09.jpg)
