### ISSUE TITLE
Fatal Error with elementor v2.94

### ISSUE THREAD

**Issue by mhines** [dudaster/ele-custom-skin#204]
Elementor released a patch today in version 2.9.4 But i'm getting a fatal error with ele custom skin pro 2.0. which also needs to be installed. is there a fix coming?

**Comment by dudaster** [comment]
What is the error you’re getting?

**Comment by mhines** [comment]
After further checking i've got i've got it all working now..my apologies. But thanks for reaching out so quickly.
