### ISSUE TITLE
Firefox slider alignment/cropping

### ISSUE THREAD

**Issue by Gingerandtall** [dudaster/ele-custom-skin#207]
Scroll down to the bottom 'But  don't  just  take  our word  for  it...' section.
https://printincclothing.gntweb.co.uk/

i've got a custom skin, set up to display in slider, displays fine in chrome, but client said is 'cutting off text' in firefox.
firefox screenshot below:
![screenshot](https://user-images.githubusercontent.com/64219037/81564043-0911f680-938f-11ea-8c44-263e55c9a683.jpg)

wordpress 5.4.1
Elementor - 2.9.8
Elementor Pro - 2.9.3
Ele Custom Skin - 2.1.0
Ele Custom Skin Pro - 1.3.3

**Comment by dudaster** [comment]
set column and row padding to 0

**Comment by Gingerandtall** [comment]
on the skin?

**Comment by dudaster** [comment]
![Screen Shot 2020-05-11 at 4 01 37 PM](https://user-images.githubusercontent.com/8319178/81564654-c22cfc80-93a0-11ea-9f34-4efb6e0bb093.png)

From Post /Archive widget

**Comment by Gingerandtall** [comment]
you are a genuis. thank you so much.
