### ISSUE TITLE
Custom Grid Layout breaks Layout to full width.

### ISSUE THREAD

**Issue by tibacreative** [dudaster/ele-custom-skin#208]
Hey Dudaster,

i'd like to use custom grid layout on a frontpage to loop posts in a custom loop. So far so good.
It's not working if section is boxed and contains columns. What happens is that the custom grid breaks the columns and makes the grid to full width.

I'm using:
WP 5.4.1
Theme: Hello Elementor: Current Version
Elementor + Pro: Current Version
Ele Custom Skin + Pro:  Current Version
Dynamic.ooo/Dynamic Content for Elementor: Current Version

If you need the website & login credentials let me know.

**Comment by dudaster** [comment]
Do you have "Stretch Section" option set to on?
![Screen Shot 2020-05-13 at 1 47 47 PM](https://user-images.githubusercontent.com/8319178/81803478-68ebd700-9520-11ea-9a33-a1f2d9215bb9.png)

**Comment by tibacreative** [comment]
No i dont. But i just tryed it anyways and nothing changed.  Tryed a few other things now it looks good in left column but right column breaks under the left column.

**Comment by tibacreative** [comment]
See the construction here:
https://ibb.co/YdKFXCr

**Comment by dudaster** [comment]
I need to see the css to see what is happening there...  can you save the template from custom grid and post it here?

**Comment by tibacreative** [comment]
Edit: When the Post Grid Layout contains only element: nothing breaks.

**Comment by tibacreative** [comment]
`{"version":"0.4","title":"CG Start","type":"custom_grid","content":[{"id":"572064","settings":{"content_width":{"unit":"px","size":1140,"sizes":[]},"structure":"20"},"elements":[{"id":"4486eaac","settings":{"_column_size":50,"_inline_size":null},"elements":[{"id":"15fd2f4e","settings":{"_element_custom_width":{"unit":"%","size":50,"sizes":[]}},"elements":[],"isInner":false,"widgetType":"ele-loop-item","elType":"widget"}],"isInner":false,"elType":"column"},{"id":"120966dd","settings":{"_column_size":50,"_inline_size":null},"elements":[{"id":"2e33eac8","settings":{"_element_custom_width":{"unit":"%","size":50,"sizes":[]}},"elements":[],"isInner":false,"widgetType":"ele-loop-item","elType":"widget"}],"isInner":false,"elType":"column"}],"isInner":false,"elType":"section"},{"id":"34454fe2","settings":{"content_width":{"unit":"px","size":1140,"sizes":[]},"structure":"20"},"elements":[{"id":"4ef2a784","settings":{"_column_size":50,"_inline_size":60},"elements":[{"id":"66a155da","settings":{"_element_custom_width":{"unit":"%","size":50,"sizes":[]}},"elements":[],"isInner":false,"widgetType":"ele-loop-item","elType":"widget"}],"isInner":false,"elType":"column"},{"id":"319feef2","settings":{"_column_size":50,"_inline_size":39.956000000000003},"elements":[{"id":"54e9104c","settings":{"_element_custom_width":{"unit":"%","size":50,"sizes":[]}},"elements":[],"isInner":false,"widgetType":"ele-loop-item","elType":"widget"}],"isInner":false,"elType":"column"}],"isInner":false,"elType":"section"},{"id":"d1af434","settings":{"content_width":{"unit":"px","size":1140,"sizes":[]}},"elements":[{"id":"48e1c5e2","settings":{"_column_size":100,"_inline_size":null},"elements":[{"id":"75b97202","settings":{"_element_custom_width":{"unit":"%","size":50,"sizes":[]}},"elements":[],"isInner":false,"widgetType":"ele-loop-item","elType":"widget"}],"isInner":false,"elType":"column"}],"isInner":false,"elType":"section"}]}`

**Comment by dudaster** [comment]
can't you attach it?

**Comment by tibacreative** [comment]
No sorry, dont have the option to upload file here.

**Comment by dudaster** [comment]
Click on the "Attach files by dragging..."
![Screen Shot 2020-05-13 at 3 03 26 PM](https://user-images.githubusercontent.com/8319178/81810078-ff24fa80-952a-11ea-9f0f-e5437e24bcb4.png)

**Comment by tibacreative** [comment]
[elementor-30613-2020-05-13 text.txt](https://github.com/dudaster/ele-custom-skin/files/4621821/elementor-30613-2020-05-13.text.txt)

**Comment by dudaster** [comment]
https://clean.ehot.ro/ how it looks at my side...

Can you please send me the loop template thar are you using also?

(please ignore the error message it is stuff I'm working on)

**Comment by tibacreative** [comment]
Sure.

[elementor-22755-2020-05-13text.txt](https://github.com/dudaster/ele-custom-skin/files/4621863/elementor-22755-2020-05-13text.txt)

**Comment by dudaster** [comment]
take a look again...

**Comment by dudaster** [comment]
If there is a way I can have access to your url so I can inspect element stuff there to see what's wrong I can help you more

**Comment by tibacreative** [comment]
just sent you a chat-msg via your website. thanks a lot.

**Comment by tibacreative** [comment]
amazing support. thanks!

**Comment by dudaster** [comment]
The problem was a but in ECS v2.1.0
