### ISSUE TITLE
Featured Image in Loop Template no longer showing

### ISSUE THREAD

**Issue by 1000camels** [dudaster/ele-custom-skin#211]
Hi, I wanted to reference this support request here (https://wordpress.org/support/topic/featured-image-is-not-displayed-in-the-last-version/). Your suggestion about the setting the fallback image does not help (unless I am misunderstanding).

Something changed in the last two weeks. I have tried to revert Ele Custom Skin and Ele Custom Skin Pro and Elementor and Elementor Pro. I am not able to get it back.

The behaviour is quite strange. The image element in the markup is not there, as if the feature image module is simply not outputting anything.

**Comment by dudaster** [comment]
Can you provide an URL ?

**Comment by 1000camels** [comment]
https://studio22.ca/2020/02/13/new-beginnings/

The six entries under The Artwork section

**Comment by dudaster** [comment]
Can you disable autoptimize? I cannot see what is going on there. And if you don't use dynamic image just a static image is it working?

**Comment by 1000camels** [comment]
Autoptimize is deactivated. No difference.
I have added a fallback image and that appears (although it is the same for each).
In the template, you can see it doesn't show.

I am happy to provide you access if it helps.

**Comment by dudaster** [comment]
Does your website chat work? I'm trying to contact you through it.

**Comment by 1000camels** [comment]
I saw. I do not manage the chat

**Comment by dudaster** [comment]
Use the chat on dudaster.com then!

**Comment by 1000camels** [comment]
This was an error on my server.
