### ISSUE TITLE
Masonry doesn't seem to work

### ISSUE THREAD

**Issue by tshwanom** [dudaster/ele-custom-skin#217]
Masonry doesn't seem to work please see the screenshot. the bottom row still remain on the straight line

![Annotation 2020-05-26 044231](https://user-images.githubusercontent.com/6187215/82859286-9d936180-9f16-11ea-9f21-09fa04c31fd1.jpg)

**Comment by dudaster** [comment]
Can you provide an Url?

**Comment by tshwanom** [comment]
Www.mycrib.africa

**Comment by dudaster** [comment]
Masonry doesn't work with custom grid. You need to disable the custom grid feature in order to work.

**Comment by tshwanom** [comment]
That link I was just trying to find a way around it... You can see it here
https://mycrib.africa/shop it is not custom grid yet it to still doesn't
work

**Comment by dudaster** [comment]
At this page looks like masonry is not selected. At least in code.

**Comment by tshwanom** [comment]
I removed the custom grid from  https://mycrib.africa/
 please recheck

Thanks for your patience
--
Regards

Benj Modimoeng   CEO
MLB Group
T: 010 035 2364
m: 0614574378
s: www.myplans.co.za e: benj@myplans.co.za
<https://www.facebook.com/myhouseplansa/>  <https://twitter.com/MyHouseplan>
  <https://za.linkedin.com/in/my-house-plans-south-africa-90b9b9103>
<https://www.instagram.com/myhouseplans/>

**Comment by dudaster** [comment]
It works for me.

**Comment by tshwanom** [comment]
> It works for me.

Manged to sort it out thanx for your time
