### ISSUE TITLE
WooCommerce Categories not work with Ele Custom Skin, or is it a Pro feature?

### ISSUE THREAD

**Issue by ToniTurnbeutel** [dudaster/ele-custom-skin#219]
Hi, I designed my product archive with Loop Templates (Ele Custom Skin). The problem I have is, if I make a Category Menu and searching for a specific category, the WooCommerce products do not get filtered anymore. Is their a possibility to fix this, is this feature may be a pro feature or is it not possible? Thank you for helping!

**Comment by dudaster** [comment]
It should work. Does it work with classic skin?

**Comment by ToniTurnbeutel** [comment]
thx for answering. you mean the classic woocommerce skin? Yes it work with it. But somehow not with the loop template. If I add product details to the design in the loop template, it shows me the categories I defined in WooCommerce, so their is a link between. But filtering with the woocommerce product menu did not work until now.

**Comment by dudaster** [comment]
I mean with post widget classic skin.

**Comment by dudaster** [comment]
You said it worked before? What changed?

**Comment by ToniTurnbeutel** [comment]
I meant with the standard product design from Woocommerce the filtering process worked. How I get this widget?

**Comment by dudaster** [comment]
That widget is basically a shortcode from woocommerce. But I need to know if it is a query issue or it is an ECS issue. Please select classic skin even if it doesn’t show all the details but I want to know if works with the query.

**Comment by ToniTurnbeutel** [comment]
I basically followed this video: https://www.youtube.com/watch?v=qUF7HLdcjlg&t=618s
I understand your question but as a beginner its to hard for me to follow.

**Comment by dudaster** [comment]
Just go to the place where you set the skin as custom and switch it to classic

**Comment by ToniTurnbeutel** [comment]
So I changed the skin to classic and the filtering does still not work.

![image](https://user-images.githubusercontent.com/66162436/83327991-5263b080-a280-11ea-9b27-d00ea36f2f61.png)

**Comment by Mrsnibs** [comment]
Ok, so that video only seems to show the way to set up an all products page, In the video at 11.38 he starts to change the source for the loop. If instead of using "products" you use "current query" the filtering of categories should work.

**Comment by dudaster** [comment]
Try it. And let me know if it works.

**Comment by ToniTurnbeutel** [comment]
Thank you guys! Your Information was Gold! It worked out:)
