### ISSUE TITLE
Custom Skin and Jet Smart Filter

### ISSUE THREAD

**Issue by Julsh2** [dudaster/ele-custom-skin#223]
Hi. I'm using Custom Skin to show a ACF Field in my Archieve page.

![image](https://user-images.githubusercontent.com/66392008/83695305-2aea4c00-a5d0-11ea-8fcc-ff1dc66eb570.png)

And, i'm using Jet Smart Filter too. But, it's only working when I use Classic Skin (and, not showing ACF Field).
![image](https://user-images.githubusercontent.com/66392008/83695491-84eb1180-a5d0-11ea-837f-fbeeae2fd39d.png)

Can I use Jet Smart Filter and Custom Skin?

Thanks for all :)

**Comment by dudaster** [comment]
Yes but at the moment not with Ajax keep you post it.

**Comment by pippyn** [comment]
Sollution for in the meantime:
If you comment out line 350 of `/plugins/ele-custom-skin/skins/skin-custom.php`, jetsmartfilters works fine for me.

**Comment by dudaster** [comment]
I’ll check it out

**Comment by dudaster** [comment]
Hi @pippyn change line 350 to:
`                'theme_id' => is_null($theme_document) ? '' : $theme_document->get_main_id(),`
Let me know if it works and I'll release a patch right now.

**Comment by pippyn** [comment]
Hey @dudaster, I can confirm this fix works! Tested on 3 of my sites and all is fine.

**Comment by dudaster** [comment]
I'll release it now.

**Comment by dudaster** [comment]
It is out.
