### ISSUE TITLE
blog-page crashes after update to ele-custom-skin v2.2.1

### ISSUE THREAD

**Issue by jm-hg** [dudaster/ele-custom-skin#227]
Hello,
after I upgraded ele-custom-skin from v2.1.0 to v2.2.1 my four WP blog-pages (e.g. [https://ennrwig20200.jumpr.eu/nrw-isst-gut-informiert/](url)) crashed and displayed this warning on frontend aside each post: 

```
Warning 
: Illegal string offset 'url' in /www/[...]/wp-content/plugins/elementor/includes/base/controls-stack.php on line 1201
```

Line 1201 in controls-stack.php says:

```
$settings[ $control_name ][ $dynamic_property ] = $parsed_value;
```

Only a downgrade to ele-custom-skin v2.1.0 solves the problem.

System specs:
- WP 5.4.1
- Elementor v2.9.11
- Elementor Pro v2.9.5
- ele-custom-ski-pro v2.1.0

and other Elementor Add-ons etc.

Any clues what causes this problem?

**Comment by dudaster** [comment]
Do you have make column clickable plugin installed?

**Comment by jm-hg** [comment]
Yes, Version 1.3.1

**Comment by dudaster** [comment]
That is what causing the problem. Use it the make post linkable from custom skin instead.

**Comment by jm-hg** [comment]
This is it! Thanks for the quick and simple solution!
Kind regards
