### ISSUE TITLE
infinite load: problems with encoding and "make entire post a link"

### ISSUE THREAD

**Issue by werkform** [dudaster/ele-custom-skin#231]
Love the new infinite load. Unfortunately I figured out 2 problems: 

1. the encoding in the titles of the dynamic loaded loop-items is not correct. F.e. I got "WordPress fÃ¼r GÃ¤rtner" but it must be "WordPress für Gärtner".

2. Marking the function "Make entire Post a link" seems not to work if infinite load is enabled.

**Comment by dudaster** [comment]
Can you provide an url? I don’t have this issues.

**Comment by werkform** [comment]
https://www.werkform.at/blog/ <https://www.werkform.at/blog/>

for the first issue

**Comment by dudaster** [comment]
It looks like it is not turned on.

**Comment by werkform** [comment]
see the issue in the 2 posts as marked in the screenshot?

it’s done with the latest chrome, but can reproduce it with firefox dev.

H.

**Comment by dudaster** [comment]
Please reply directly in github... I cannot see the attachments.

I'm inspecting element your page and I cannot see the html required for the make entire post link feature to be enabled. Please make sure you edit the proper (archive) template.

**Comment by werkform** [comment]
![screenshot_encoding](https://user-images.githubusercontent.com/1775348/84041170-cb12ed00-a9a3-11ea-9ae6-6f1e36460aef.jpg)

As you can see here: first line normal load, 2nd dynamic loaded.

**Comment by dudaster** [comment]
Ok I see the problem with encoding. How about the make the entire post a link issue?

**Comment by werkform** [comment]
I'v enabled the feature now, but this is a working site, I will disable it after your inspection in the matter of my visitors:

https://www.werkform.at/blog/

**Comment by dudaster** [comment]
can you please make a page with a post widget not available in any menu so you can share it with me... 

Now I'm working on a solution to provide the proper encoding.

**Comment by werkform** [comment]
https://www.werkform.at/4debug/

Here you can see the 2nd issue. All Links are shown correctly but onClick you see a redirect on the page itself.

**Comment by dudaster** [comment]
I fixed the charste issue it will be available in the next version of free ECS

**Comment by werkform** [comment]
> I fixed the charste issue it will be available in the next version of free ECS

Thank you for the superfast reaction!

**Comment by dudaster** [comment]
I Know it is counter intuitive first. But did you selected what the link you want to be?
Check this screen shot!
![Screen Shot 2020-05-23 at 7 59 48 AM](https://user-images.githubusercontent.com/8319178/84067162-ae8caa00-a9cf-11ea-8b40-bf7c3950c139.png)

**Comment by werkform** [comment]
No! I set the dynamic links in the loop-template! I forgot to set this link and the browser shows the correct Links on hover! So this is an UIX issue and not a bug.

**Comment by Zjadlbymcos** [comment]
> 1. the encoding in the titles of the dynamic loaded loop-items is not correct. F.e. I got "WordPress fÃ¼r GÃ¤rtner" but it must be "WordPress für Gärtner".

I can confirm that issue. 

First 5 loaded posts looks good: ![Zrzut ekranu z 2020-06-09 15-14-14](https://user-images.githubusercontent.com/11710437/84151812-2a383680-aa64-11ea-9b43-53a2996504ff.png)
"Infinity loaded" post with bad encoding: ![Zrzut ekranu z 2020-06-09 15-14-21](https://user-images.githubusercontent.com/11710437/84151809-299fa000-aa64-11ea-9d9b-e1d74153bea2.png)

**Comment by dudaster** [comment]
I know about the issue I'll try to release an update today. Tomorrow the latest.

**Comment by dudaster** [comment]
The update is out. Let me know if the issue is fixed.

**Comment by Zjadlbymcos** [comment]
Yep. Now works well :)

Thank you for quick support
