### ISSUE TITLE
loop not working on home page (but everywhere else)

### ISSUE THREAD

**Issue by timchorlton** [dudaster/ele-custom-skin#232]
Hi Guys,

Elementor, WooCommerce and Ele Skins Pro and Toolkit For Elementor.

My loop works fine on the product archive page - https://ratherlather.factorydev.co.uk/shop/

And works fine on the 'you might also like' on the product pages - https://ratherlather.factorydev.co.uk/shop/cedarwood-shaving-soap/

But not on the home page - https://ratherlather.factorydev.co.uk/

I have cleared the cache (I am using toolkit for elementor in themeless mode), I turned off and on the plugins and re built the CSS from withing the elementor tools section.

Still no joy - and ideas please?

**Comment by dudaster** [comment]
add woocommerce class to the post widget and let me know if it works!

**Comment by timchorlton** [comment]
sorry - how/where do I do that?

**Comment by dudaster** [comment]
In advanced tab class field

**Comment by timchorlton** [comment]
OK, thank you - and what do I need to put in there (sorry).

**Comment by dudaster** [comment]
![Screen Shot 2020-06-11 at 2 33 38 PM](https://user-images.githubusercontent.com/8319178/84380936-e58dd600-abf0-11ea-97fc-a4b28c7b271e.png)

**Comment by timchorlton** [comment]
WOW - immediate success!!! Is that because the home page isn't a standard Woo-Commerce page?

**Comment by dudaster** [comment]
something like that
