### ISSUE TITLE
All the loops are showing in the "Edit with Elementor" menu

### ISSUE THREAD

**Issue by DODMax** [dudaster/ele-custom-skin#233]
All the loops are showing on all the pages. It's been like this for about a month, after a plugin update.
Only happens on one of my website, other websites with similar configuration are fine.
![image](https://user-images.githubusercontent.com/1137276/84222266-55bd2e80-ab01-11ea-82e4-923682ba9fa5.png)

**Comment by dudaster** [comment]
What is the version of wp. What theme are you using?

**Comment by DODMax** [comment]
So the issue was that either my customer or "something" went on and added a display condition to all the loops:
![image](https://user-images.githubusercontent.com/1137276/84990755-d28a8100-b16f-11ea-830b-cc3b8be93934.png)

I doubt it was my customer though as the dropdown in display condition is empty which I don't think can be achieved using the UI. Anyway, going through all the loops and removing the display condition fixed it.
