### ISSUE TITLE
Empty space under each row of posts

### ISSUE THREAD

**Issue by bdubs262** [dudaster/ele-custom-skin#235]
Hi there,

Thank you for the great plugin, 

We have just added a new custom skin to our posts widget, but there's a space underneath each row. We've set the rows gap to 0.

![image](https://user-images.githubusercontent.com/66738898/84284668-ca618e80-ab3c-11ea-9712-6a1b8ddaa9ea.png)

Many thanks,

**Comment by dudaster** [comment]
Could be an css from the theme. To be sure an url would be helpful.

**Comment by bdubs262** [comment]
Here is the link: https://misspentsummers.com/store-misspent-summers/

**Comment by dudaster** [comment]
The issue is from blask theme you're using.
It has this css code:
```
.hentry {
    margin: 0 0 6em;
    max-width: 880px;
}
```
You need to override it with your own like this:

```
.ecs-post-loop .hentry {
    margin: 0;
}
```

**Comment by dudaster** [comment]
as I see it is fixed

**Comment by bdubs262** [comment]
Yes, thank you very much for your help! That's great.
