### ISSUE TITLE
Setting a section background with dynamic tag doesn't apply background properties

### ISSUE THREAD

**Issue by teoeugene** [dudaster/ele-custom-skin#236]
I added a background on a Section using Featured Image as the Dynamic Tag. However, none of the background properties such as position, repeat, and size are generated. A normal background image without Dynamic Tag doesn't have this issue. I'm using the latest version of the plugin for both free (2.2.2) and Pro (2.1.0)

**Comment by dudaster** [comment]
Please read common issues sticky issue!
