### ISSUE TITLE
jQuery is not defined errors

### ISSUE THREAD

**Issue by wrobeson** [dudaster/ele-custom-skin#237]
Hello;

We are getting a lot of errors 'jQuery' is not defined. They all refer to this file:
ele-custom-skin/assets/js/ecs_ajax_pagination.js?ver=2.2.1

JQMIGRATE: Migrate is installed, version 1.4.1

What can we do to resolve this?

Thanks

**Comment by dudaster** [comment]
Install v2.2.2

**Comment by wrobeson** [comment]
Where can I download v2.2.2?

**Comment by wrobeson** [comment]
Nevermind. Found it where it was supposed to be - and where I didn't look.

**Comment by dudaster** [comment]
did it fixed the problem?
