### ISSUE TITLE
Query by Tag

### ISSUE THREAD

**Issue by dwinpul** [dudaster/ele-custom-skin#240]
Hello, I'm using Elementor Pro and ECS Pro. I have different content post types. Some of these different types are to be shown in a slider on the homepage. These posts get a Tag "show on home page". How can I create a query based on a Tag? Thanks in advance, Daniel

**Comment by dudaster** [comment]
https://www.youtube.com/watch?v=TtHIDWY82Hg

**Comment by dwinpul** [comment]
Hi,

at this point i don't find what i'm looking for, or i am blind at the moment.

I am looking for a direct way to filter on a keyword, the posts are of different post types and they should be shown on the homepage with the appropriate keyword.

unfortunately you can only query for a keyword in one post type - not across all post types.

do you have an idea how to implement it?

**Comment by dudaster** [comment]
can this be of your help?

https://developers.elementor.com/custom-query-filter/

**Comment by dwinpul** [comment]
hello, this tip helped me a lot. It works. Thanks a lot.
