### ISSUE TITLE
Dynamic content on the Archive Template - is it possible?

### ISSUE THREAD

**Issue by alexschneiderru** [dudaster/ele-custom-skin#243]
Hi guys,

I’d like to know if it is possible to create an archive page for custom content type posts with dynamic layout for anonses. Specifically:

1) Some differences in design/layout of anonses accordingly with data in corresponding custom fields, e.g. https://c2n.me/47YyGds.png

2) Different size and content of anons – again, accordingly with state of some custom field, e.g. https://c2n.me/47YyIEV.png

Is it doable with Elementor Pro and Elementor Custom Skin Pro?

Thanks in advance.

**Comment by dudaster** [comment]
With free version
1. You can choose to use the background as dynamic value. or you can use dynamic class to set different look and feel of the post items
2. You can use custom grid template to create the desired template but it is based only on index (the order of the post items)

With Pro version
1. You'll have a choice to use the conditional display from the loop template but not using an acf only a tag
2. You cannot brake a grid by combining two columns right now.
