### ISSUE TITLE
The Content Area Was Not Found in Your Page

### ISSUE THREAD

**Issue by Webtica** [dudaster/ele-custom-skin#246]
Hi, 

I am on the latest version of ECS 2.2.2 & ECS Pro 2.1.0. 
When i try to edit a loop i get the error: The Content Area Was Not Found in Your Page
you must call the_content function. 

I also have the latest version of elementor and elementor pro. 
Any idea how i can fix this issue? 

Thanks

**Comment by dudaster** [comment]
Please read most common issues fixed!

**Comment by Webtica** [comment]
Fixed the issue. Thanks.
