### ISSUE TITLE
Where to find a How-To?

### ISSUE THREAD

**Issue by nickdesignz** [dudaster/ele-custom-skin#248]
Hi guys,

you made a lot of changes since I was using my Pro Version.

Where can I find a how to?

My problem is that I can't use a post excerpt with a max of words I want to display? There is no possibility anymore :( 

#
<img width="1598" alt="Screenshot 2020-06-23 12 23 28" src="https://user-images.githubusercontent.com/54137727/85392934-81ea9d80-b54c-11ea-902f-df7642fe2204.png">
<img width="1600" alt="Screenshot 2020-06-23 12 23 39" src="https://user-images.githubusercontent.com/54137727/85392961-89aa4200-b54c-11ea-8f6c-1fbfb7898bf1.png">
<img width="1607" alt="Screenshot 2020-06-23 12 23 54" src="https://user-images.githubusercontent.com/54137727/85392994-95960400-b54c-11ea-8859-09ff9c3f1e29.png">
<img width="1611" alt="Screenshot 2020-06-23 12 24 07" src="https://user-images.githubusercontent.com/54137727/85393038-a47cb680-b54c-11ea-9355-6a630dac98ee.png">
<img width="1612" alt="Screenshot 2020-06-23 12 24 16" src="https://user-images.githubusercontent.com/54137727/85393062-aba3c480-b54c-11ea-9038-e3cfa9d0b76c.png">

Thank you

**Comment by dudaster** [comment]
Use a text widget with post summary dynamic value. From the settings you can select the length of it

**Comment by nickdesignz** [comment]
> Use a text widget with post summary dynamic value. From the settings you can select the length of it

Thanks, that was really quick. It works.

Could you also give a quick responsive for how to create a slider and same heights elements?


Thank you so much.
<img width="1306" alt="Screenshot 2020-06-23 12 31 41" src="https://user-images.githubusercontent.com/54137727/85393599-90858480-b54d-11ea-9378-f974ffeb16f2.png">
<img width="1334" alt="Screenshot 2020-06-23 12 31 46" src="https://user-images.githubusercontent.com/54137727/85393616-98452900-b54d-11ea-9e32-92a91725c1e3.png">

**Comment by dudaster** [comment]
Check the same height feature that should do the trick. If not I need an
url because it could be a css conflict.

**Comment by nickdesignz** [comment]
Thanks a lot, it's perfect now :)
