### ISSUE TITLE
New Elementor interface for querying posts not working custom skin

### ISSUE THREAD

**Issue by collindavis** [dudaster/ele-custom-skin#26]
I believe the latest version of Elementor 2.5.x is creating problems with the query settings. They changed the interface for this, so now when I try to set the term to query by, it just hangs there trying to load my custom posts associated taxonomy. I can't get this to work at all. I also tried creating a new page and everything, but no luck.

**Comment by dudaster** [comment]
I’ll take a look! Thanks!

**Comment by collindavis** [comment]
Thanks - I've been testing some more and seeing it with other widgets so may not be specific to you. I will have to do a full, fresh install of WP, and weed out other plugins.

**Comment by sambbaron** [comment]
Is there any follow-up on this issue? I am also having a problem with querying a custom post type using the 'Posts' widget. In my case, the data returned in the custom skin is for the current queried object, not the queried CPT object. If I use one of the elementor built-in skins, it works correctly.

**Comment by sambbaron** [comment]
Okay, it's a problem with my custom shortcode that's using `get_queried_object()`. It's returning the page's current object, not the widget query current object.

**Comment by dudaster** [comment]
Check now!

**Comment by dudaster** [comment]
No answer
