### ISSUE TITLE
Slider alignment issue on Firefox

### ISSUE THREAD

**Issue by thomastalsma** [dudaster/ele-custom-skin#267]
I'm using an Elementor custom skin pro slider on my page, but on firefox the slides seem to be about 100px shifted over. It displays properly in other browsers.

It's the quote slider near the bottom of this page:
[https://www.livetiles.nyc/](https://www.livetiles.nyc/)

**Comment by dudaster** [comment]
Plecase set Columb and row padding to 0

**Comment by thomastalsma** [comment]
For future reference, Selecting the 'Posts' widget and going to the style tab and setting 'Columns Gap' & 'Row Gap' to 0, resolves this issue.
