### ISSUE TITLE
Posts Extra (NAMOGO Elementor Extras)

### ISSUE THREAD

**Issue by DirkCarstens** [dudaster/ele-custom-skin#27]
Posts Extra (NAMOGO Elementor Extras) and  ele-custom-skin don't work together.
I've created a loop and everything worked out fine with elementor pro posts - I can select the skin "Custom".
But with Posts Extra there is no "Custom".
Posts Extra has some nice features (infinite scroll). Is there a way to integrate ele-custom-skin into Posts Extra?
That would be really nice! 
Best regards
Dirk

**Comment by dudaster** [comment]
maybe in the future
