### ISSUE TITLE
tying to create dynamic links from pods in elementor using the dynamic options

### ISSUE THREAD

**Issue by bigfanta2** [dudaster/ele-custom-skin#278]
hi, hope you can help me out, i brought pro and Im having some difficulty. Im using pods and I've setup some fields for website URL and buy links. but i don't know how to pull this information into the skins so that its a link ?  

what im tiring to do: on the blog achieve page I'm creating a custom archive and on this i need a button which clicks to post which is fine..... but i need text links which link to other things.. but i can't seem to do this? how do i link or put in a URLs / link into skins as dynamic text? 

eg if I make a pod > filed which is Buy  link and I set this up as url  <<<< how do I now use dynamic options in elementor to pull this link onto the custom skin blog feed that im trying to create.

**Comment by dudaster** [comment]
If for example you would create a single page with this feature it will work?

**Comment by bigfanta2** [comment]
Thanks let me try to explains 

This is the loop page - https://www.elluminateme.com/department/

- issue 1) its putting a post div tase around the whole section so you can not click the second button 

When you click button 1 it takes you to https://www.elluminateme.com/department-store/the-fabricant/

When you click button 2 - it should take you to https://www.thefabricant.com/ but it takes you to the above 


Issue 2  - (on single and loop page )
https://www.elluminateme.com/department-store/the-fabricant/

I can't pull dynamic text so for example if I wanted a text link for a website its not pulling it as a link 

Also if I try to use either embed video or video Url in pods im unable to pull the content across

**Comment by bigfanta2** [comment]
any further help on this please?

**Comment by dudaster** [comment]
Sorry I’ve been sick for the past few days. Tomorrow We’ll solve it one way or another.

**Comment by dudaster** [comment]
1. For widgets you don't want to be affected by the make the entire post a link you can add this class to them: `ecs-ignore-link`
Let me know if it fixes the issue.

2. On the second issue where should I look ?

**Comment by bigfanta2** [comment]
Sorry where dob add the css?

I want to make the loop look like that attached

Thanks

**Comment by bigfanta2** [comment]
where to add this?  please advise or then provide refund please

thanks
Jatinder

**Comment by dudaster** [comment]
The class need to be added to the widget from the loop template that you need to be ignored by the javascript that makes the entire post clickable. 
![Capture](https://user-images.githubusercontent.com/8319178/91709153-03812c00-eb8b-11ea-818c-649f3b4a442d.PNG)

**Comment by bigfanta2** [comment]
Hi I tried this but its still not working


https://www.elluminateme.com/department/ <https://www.elluminateme.com/department/>

please advise

**Comment by bigfanta2** [comment]
we only need the buttons to link 

> https://www.elluminateme.com/department/ <https://www.elluminateme.com/department/>
not the rest of the post , how can we make this happen?

please advise

thanks
Jatinder

**Comment by dudaster** [comment]
In the Posts/Widget check for "Make entire post a link?" to be turned off
![Capture](https://user-images.githubusercontent.com/8319178/91710964-c5d1d280-eb8d-11ea-8224-2eb90c210f19.PNG)

**Comment by bigfanta2** [comment]
hi my business partner had to adjust some java code to get it to work 

you plugin is too expensive as there ia another one here too https://theplusaddons.com/elementor/pluslisting/custom-loop-skin-builder/ <https://theplusaddons.com/elementor/pluslisting/custom-loop-skin-builder/>

coud we have a partial refund as its not working out of the box and we had to do our own coding to get it to work 

kind regards
Jatinder

**Comment by dudaster** [comment]
You have 30days money back guaranteed. If you are eligible please complete the contact form with all the details.
