### ISSUE TITLE
Error : The site is experiencing technical difficulties.

### ISSUE THREAD

**Issue by zerealthib** [dudaster/ele-custom-skin#28]
As soon as I installed/activated the plugin this message comes up.

all is updated : 
wordpress version 5.2,
Elementor v2.5.15

No other plugin is enabled,
as soon as I deactivate it, everything works fine again.

**Comment by dudaster** [comment]
can you find out what the error is?

**Comment by jibberish666** [comment]
Hi all

I have possibly the same issue.  I get the same error message.  

When I look in the error log, I see this:

PHP Fatal error:  Class 'ElementorPro\\Modules\\Posts\\Skins\\Skin_Base' not found in /var/www/html/wp-content/plugins/ele-custom-skin/skins/skin-custom.php on line 15

Please can you help?

**Comment by dudaster** [comment]
@jibberish666 I know it is a dumb question but let’s get it out of the way: do you have elementor pro installed and activated?

**Comment by jibberish666** [comment]
Hi Dudaster.  Thanks for replying.  Yes, I do have Elementor installed and activated but not Elementor Pro  :-)

**Comment by dudaster** [comment]
I'm afraid you need EPro installed for this skin to work

**Comment by zerealthib** [comment]
indeed, as it was not clearly stated on the wordpress plugin page but it was mentioned on the official site : 
the plugin does not work without the PRO edition of Elementor.

Thanks.
