### ISSUE TITLE
Using WooCommerce hooks

### ISSUE THREAD

**Issue by boghy933** [dudaster/ele-custom-skin#280]
Hello,

Is it possible to make the woocommerce default hooks work with the plugin? => https://docs.woocommerce.com/wc-apidocs/hook-docs.html

I want to make some customization using the hooks but they're not triggered when i am inside the page created with custom skin.

Thank you

**Comment by dudaster** [comment]
You can try and create shortcodes and insert them inside the template

**Comment by boghy933** [comment]
Thank you @dudaster
