### ISSUE TITLE
ele-custom skins stopped working on sites

### ISSUE THREAD

**Issue by alliemay** [dudaster/ele-custom-skin#29]
The plugin was working wonderfully on several sites until yesterday or so. I don't know if it stopped with an elementor update of with the most recent WP update. On one site, keeping the plugin activated greyed out the entire elementor widget panel (or it hangs and won't load). On another, I created, but couldn't load a custom loop on an archive template. On another, the (ACF) custom fields in a loop template stopped displaying. 

I have been relying heavily on this plugin since I discovered it a couple of months ago, so I would hate to find it not usable any longer.  I think I am using GeneratePress Theme on two of the sites and Astra with one of them. Any hints to begin troubleshooting?

**Comment by dudaster** [comment]
I’ll try to recreate the problem. Meanwhile try to find if there is an error you can provide. Also you can try running the website on another computer it could be an server issue.

**Comment by alliemay** [comment]
I will see if I can find a definite error. I’ll see if I can replicate the issues on a different computer, but I only have Macs…I don’t know if any of this helps. I have the plugin installed on 5 or 6 sites, and it looks like a couple of them are working okay. (I can create and use custom loops with ACF.) (The first site is hosted on SiteGround, the second one is on Dreamhost)

On one of the sites, I am not able to choose the custom loop I created. The loop is there, but it won’t “stick.”  




On one other, the whole elementor bank of modules won’t load when the plugin is activated. (To be fair, it also hangs when I had the JetEngine plugin activated)


 

Thanks,

Allison
allison@cultiverse.com

**Comment by dudaster** [comment]
Any news?

**Comment by alliemay** [comment]
To be honest, I couldn’t get the custom skin template to appear on a couple of different sites, so I just found a different plugin that works the way I need it to.

Thanks for checking back.

Allison
allison@cultiverse.com

**Comment by dudaster** [comment]
I’m glad you found a way. Keep in touch!
