### ISSUE TITLE
The content not found on loop template 

### ISSUE THREAD

**Issue by markvale** [dudaster/ele-custom-skin#299]
Since updating Elementor to 2.9.14 and Pro 2.10.3 when i go to edit an existing or new loop template i get an error that tells me that the_content() is missing

Existing loops work and adding / editing other theme elements like archive, singles headers etc are all fine

Has anyone else seen this?

**Comment by dudaster** [comment]
Have you read this issue?

https://github.com/dudaster/ele-custom-skin/issues/201

**Comment by markvale** [comment]
Thanks, didn't see the paragraph
