### ISSUE TITLE
Question about custom fields in a loop.

### ISSUE THREAD

**Issue by zSeriesGuy** [dudaster/ele-custom-skin#3]
Can PODS custom fields from a CPT be used with the {{ }} in a ele-custom-skin loop template?
I can't seem to get it working and couldn't confirm from your doc if that was possible or if it just for use in eletheme.
Thanks.

**Comment by dudaster** [comment]
I'm afraid not. ele-custom-skin was made without eletheme in mind. But I'll try to add in future versions eletheme support also.

**Comment by dudaster** [comment]
Aaaand now you can. The new version is up.
