### ISSUE TITLE
Post Summary Length

### ISSUE THREAD

**Issue by stmalk** [dudaster/ele-custom-skin#30]
Is there any way to limit post summary length by letter amount, not by word amount? Regular excerpt limits don't work with "Post Excerpt", so "post summary" dynamic field is the only one to do it, but it only has word limit.

**Comment by dudaster** [comment]
You can create your own dynamic tags: take a look in the source coude of ECS plugin: ele-custom-skin/theme-builder/dynamic-tags/

**Comment by anyacamins** [comment]
Hello, I found the folder -  ECS plugin: ele-custom-skin/theme-builder/dynamic-tags/ and I'm wondering how to implement and create my own dynamic tags so shorten "Post Excerpt"  count. I'm very new to word press , thank you for your patience.
