### ISSUE TITLE
Ele Custom Skin plugin breaks Elementor Pro Beta2 Theme Builder

### ISSUE THREAD

**Issue by Daniel-Florian** [dudaster/ele-custom-skin#304]
Hey, Just wanted to give a heads up if nobody has come across this yet.
The Ele Custom Skin (free) appears to break the Elementor Pro Beta2 Theme Builder

With the plugin activated, I received the following error when trying to load the Theme Builder: _Error: Method get_site_editor_type does not exist._
This only occurred when using the Elementor Pro Beta2 version, but did not appear to affect the free Elementor Beta5 version

**Comment by dudaster** [comment]
Here is a beta of my own that will allow you to use it.
[ele-custom-skin.zip](https://github.com/dudaster/ele-custom-skin/files/5069085/ele-custom-skin.zip)

**Comment by Daniel-Florian** [comment]
Thanks mate, that fixed it
