### ISSUE TITLE
Plugin is causing catchable error in kses.php

### ISSUE THREAD

**Issue by alexhbryant** [dudaster/ele-custom-skin#31]
Love the functionality of the plugin from a design perspective. However, when I have it activated, I started get the following error message once trying to implement it.

Catchable fatal error: Object of class WP_Error could not be converted to string in wp-includes/kses.php on line 1585

Deactivating the plugin solves it. Reactivating the plugin brings it right back.

Any ideas on the issue or fix? I really like being able to style the loop as needed, but doesn't really matter if it takes down the whole site.

**Comment by dudaster** [comment]
try please to deactivate other plugins. Maybe you're using another that doesn't like to be used more than once.

**Comment by Dreamsreal7** [comment]
Hello, I actually just started encountering the exact same issue. I have a relatively clean WP setup (Elementor + Elemntor Pro, Astra + Astra Child Theme, CPT UI, ACF). Everything was fine until about an hour or so ago when I started getting the kses.php error on line 1585 as well. Deactivating Ele Plugin works but as soon as it's reactivated it breaks my pages and throws the error. Not sure what could be causing it. All my plugins/WP is up to date, this is essentially a brand new site I'm suing to test out a new design.

**Comment by Dreamsreal7** [comment]
I found solution for me, made error when creating custom taxonomies/post types

**Comment by alexhbryant** [comment]
@Dreamsreal7 So the solution is not to use it with custom taxonomies and post types? Or did you find a solution while still using custom tax/post?

**Comment by Dreamsreal7** [comment]
You can use it with Custom Taxonomies/Post Types, I unfortunately made
errors in rewording custom taxonomies and it messed up the structure.
Deactivating Ele did work but ultimately when viewing the actual custom
post type, it displayed same error even without Ele active meaning I had a
conflict with my Custom Taxonomies/Post types outside of Elementor and Ele.

**Comment by alexhbryant** [comment]
Okay, this makes a lot of sense, thanks. I'll play around with it, because custom taxonomies and post types is the common thread here.
