### ISSUE TITLE
posts clustering together

### ISSUE THREAD

**Issue by rotsburg** [dudaster/ele-custom-skin#313]
Hello Support,

After creating a custom loop and placing that loop into Elementor's Posts' widget, they all clustered together when I previewed it and did the same thing in the editor after refreshing the page. If anyone can let me know what is most likely causing this, that would be greatly appreciated.

Thank you,

Rotsburg

**Comment by dudaster** [comment]
Make sure you don’t have forced full width on the main section in loop template!

**Comment by rotsburg** [comment]
It seems to have worked. Thank you very much.
