### ISSUE TITLE
When using equal height columns option - possible to bottom vertical align button?

### ISSUE THREAD

**Issue by austinsparx** [dudaster/ele-custom-skin#314]
Great plugin thanks - one thing I'm trying to work out and can't... I'm using the Display Mode > Same Height option. 

In my Loop template I'm using a button with Advanced > Positioning > Fixed > Vertical Orientation = Bottom.

The template correctly has the same height background but the button shows after the content height. Any workarounds or way I can get this working with same height but bottom aligned buttons?

Top = Current
Bottom = Goal

![image](https://user-images.githubusercontent.com/36247049/91038787-b662fe80-e64e-11ea-8615-01ab0eb8e9f8.png)

**Comment by dudaster** [comment]
Just give it custom positioning and align it to the bottom

**Comment by austinsparx** [comment]
I did have this setup using custom positioning but the positioning wasn't working - looking at this now it must have been caching as I've now got this setup and working as expected. Thanks 👍
