### ISSUE TITLE
Infinite loop doesn't work corrtly

### ISSUE THREAD

**Issue by SharpTITAN** [dudaster/ele-custom-skin#315]
Unfortunately the Infinite loop does not work correctly. (Pro version was bought)
There are about 50 posts on the side and after every 5 posts they should be reloaded. Unfortunately the area remains empty after loading. But the loading bar appears.

Link to website
https://titan-platoon.de/das-platoon/mitglieder/platoon

**Comment by dudaster** [comment]
can you switch to a load more pagination so I can take a look?

**Comment by SharpTITAN** [comment]
thank you for the fast reply,

i changed it. Same result.

**Comment by dudaster** [comment]
I think the issue is with entrance animation. There is a unorthodox solution. I'll be back with a js code.

**Comment by SharpTITAN** [comment]
OK, I deleted the animation, no positiv effect

**Comment by dudaster** [comment]
See if you can add this js to your website
```
jQuery( document ).ready(function() {
  ECS_add_action("ajax", function(){ window.elementorFrontend.init() });
});
```

**Comment by SharpTITAN** [comment]
puh can i give you temp access to the side, i am note sure there the code insert

**Comment by dudaster** [comment]
try an find an plugin that let's you insert it. Found a one:
https://wordpress.org/plugins/header-and-footer-scripts/

**Comment by SharpTITAN** [comment]
Ok Thank you i will try it.

**Comment by SharpTITAN** [comment]
Perfect, it works. Thank you for your fast and competent helpf.
