### ISSUE TITLE
Update Fails and Causes Terminal Error on Site

### ISSUE THREAD

**Issue by MicheleS83** [dudaster/ele-custom-skin#316]
I apologize if this isn't overly technical (new to websites) but when activated the skin causes a terminal error on my site. I had to have WP support disable all plugs in and then went one by one. When I turn the skin on it fails. Is there a way around this? My entire site is based on this so missing a lot of content. It was working till a recent update failed. 

Thanks!

**Comment by dudaster** [comment]
What version of ECS and elementor pro are you using ?
