### ISSUE TITLE
Woocommerce Price element loses stying on homepage

### ISSUE THREAD

**Issue by Vasselgog** [dudaster/ele-custom-skin#318]
Hi,

I bought the pro version of the plugin. It works great, just one query. The styling on the price seems to be getting stripped everywhere except on the product archive pages.

http://ijw.flywheelsites.com/competitions/ - This is what it should look like

http://ijw.flywheelsites.com/competitions/ - This is where the styling is getting stripped.

Please could you suggest a solution.

Kind Regards,

Joe

**Comment by dudaster** [comment]
Please add woocommerce class to the post widget

**Comment by Vasselgog** [comment]
To the price widget? Just woocommerce? 

Thanks,

Joe

**Comment by dudaster** [comment]
to the widget where you selected the custom skin: Posts Archive Widget / Posts Widget

You need to select the widget and in advanced tab you can add class `woocommerce`

**Comment by Vasselgog** [comment]
Legend, that's worked perfectly. Thanks so much for the quick response! Brilliant plugin bought the crocoblocks one and it's nowhere near as good as this. It's brilliant that you can pull in custom fields, great work!

**Comment by dudaster** [comment]
Anytime!
