### ISSUE TITLE
Can't Input Custom Post Field.

### ISSUE THREAD

**Issue by digisavvy** [dudaster/ele-custom-skin#32]
I noticed that if I want to use Post Custom Field in the layout builder that I can neither select nor input a desired value.  (short video: http://take.ms/DgUX70)

**Comment by dudaster** [comment]
There aren't any issues with ACF AFAK. Please make sure the field is created and properly assign.

**Comment by rrodkin** [comment]
I think digisavvy means the native wordpress custom fields, not ACF.  I use PODs, and have had not issues.  I tried adding a native custom field to a post, and then tried to integrate it through Elementor, and had the same issue.

That said, if it's supposed to work at all, I'd think that's a larger Elementor issue, and not one for dudaster to fix.

**Comment by digisavvy** [comment]
Point well made. Thanks. Custom fields that belong to other post types (not generated by pods or ACF) do not appear to be supported at this time.

**Comment by imdyakov** [comment]
First of all, thank you very much for a great plugin. 

I do not know if talk about the same thing but I have a problem with outputting the content of Custom Post Type fields created through ACF and CPT UI to the loop. That would be nice to be able to output something on top of post title on hoover or constantly.
