### ISSUE TITLE
Won't update to v3.0 from 2.1.0

### ISSUE THREAD

**Issue by jonjo40** [dudaster/ele-custom-skin#321]
I get:-
Update Failed: The package could not be installed. PCLZIP_ERR_BAD_FORMAT (-10) : Unable to find End of Central Dir Record signature

I have my original PRO zip but, I'm scared I lose my settings. Can you please advise? Thanks a lot.

**Comment by dudaster** [comment]
It happens for some servers. I don't know why but if you want to upgrade please check for gumroad email and that link will download the latest version.
To update you need to delete and install the new one. You shouldn't loose anything if you don't edit any content during this procedure.
