### ISSUE TITLE
Alternating templates problem

### ISSUE THREAD

**Issue by samadesign** [dudaster/ele-custom-skin#323]
Hello,

Please check why this problem is happening
 this is how the widget is looking before i updated or refresh the page 
![image](https://user-images.githubusercontent.com/70537937/91764922-094d3080-ebd0-11ea-977b-ed49baa310a1.png)

and this is after the refresh
![image](https://user-images.githubusercontent.com/70537937/91765028-38fc3880-ebd0-11ea-8760-ccb22643308b.png)

To make it look good again i need to reorder the templates 
![image](https://user-images.githubusercontent.com/70537937/91765097-54ffda00-ebd0-11ea-854e-92b0493e495c.png)

Please help me fix this problem ASAP.

Thanks!

**Comment by dudaster** [comment]
The 1st post is redundant you can use the default one

**Comment by samadesign** [comment]
Hello,

The problem is still there even after removing the default template.


*Driss Tribech*


*Graphic DesignerTel: +212 66 511 0247E-mail: samasolutions@gmail.com
<samasolutions@gmail.com>*

**Comment by dudaster** [comment]
What version of ECS are you using?

**Comment by samadesign** [comment]
Last version

**Comment by samadesign** [comment]
Please i need to fix it ASAP today

thanks
*Driss Tribech*


*Graphic DesignerTel: +212 66 511 0247E-mail: samasolutions@gmail.com
<samasolutions@gmail.com>*

**Comment by dudaster** [comment]
Please go to dudaster.com an use the chat there

**Comment by dudaster** [comment]
Thanks for pointing it out. I've patched it and it will be available in the next (free) version.

**Comment by samadesign** [comment]
*Hello,*

*I had to use the plugin again and i faced the same problem as the first
time, could you please send  me the solution for that problem so i can
modify it on my side.*

*It's URGENT*

*Thanks!*
