### ISSUE TITLE
"Sorry, the Content Area was not found in your page" Error Message

### ISSUE THREAD

**Issue by taylorhlabs** [dudaster/ele-custom-skin#327]
I have reviewed the "Common Issues Solved" page and confirmed I have a Single Post template created with "All Singular" set for the display condition. I recently updated to the latest version of Elementor with the new Theme Builder. Could that be causing the issue?

Please feel free to contact me if you'd like to login to my site for troubleshooting. I'd be happy to give you admin access.

Thanks!

**Comment by taylorhlabs** [comment]
I'm also using the Hello theme from Elementor.

**Comment by dudaster** [comment]
what other plugins do you have installed?

**Comment by taylorhlabs** [comment]
![plugins](https://user-images.githubusercontent.com/70666590/92123326-bb941c00-edb9-11ea-965c-e3daf0caeee5.jpg)

**Comment by dudaster** [comment]
I've updated the FAQ page. Now Elementor 3 has 3 types of single templates: Single / Single Post / Single Page . 
Now you need to make sure that all of the template types don't have `All singular` display condition.

I'll try to fix this issue for the future somehow but until then please make sure you don't use that condition.

**Comment by taylorhlabs** [comment]
Thanks for the quick response and fix!
