### ISSUE TITLE
No content found issue with Elementor 3.0

### ISSUE THREAD

**Issue by Iconicdigitalw** [dudaster/ele-custom-skin#331]
I have found that the Ele custom skin plugin triggers an error shown in the screenshot below. This error occurs when Elementor Version 3.0.5 and Pro Version 3.0.3 is active. 
I downgraded Elementor pro to version 2 and it works.

Please fix ASAP.
![no-content-area](https://user-images.githubusercontent.com/51693274/92328158-c4d8ef00-f02c-11ea-8cf5-4fc099feb56a.jpg)

**Comment by dudaster** [comment]
https://github.com/dudaster/ele-custom-skin/issues/201
