### ISSUE TITLE
Product Archive Layout messed up

### ISSUE THREAD

**Issue by mrazizahmed** [dudaster/ele-custom-skin#332]
Trying to create a product archive loop but the layout is completely
![ele-custom-skin](https://user-images.githubusercontent.com/70862289/92335047-16b06200-f08b-11ea-992f-9dfc4574cc3b.png)
 messed up with displaying tiny columns with Martfury Theme.

**Comment by dudaster** [comment]
It seems you have an css conflict. Can you provide an url to take a look?

**Comment by hawkdog** [comment]
Not sure if this helps or is something else. I was having this exact same issue when creating a loop for an archive. I tried adding custom classes and changing the CSS and still no luck. It ended up being the cache. The cache plugin was Proxy Cache Purge. When I deactivated that everything was fixed.
