### ISSUE TITLE
My loop-design doesn´t display right on the live site

### ISSUE THREAD

**Issue by fasonera** [dudaster/ele-custom-skin#333]
Hi!

Thanks for a great plug-in. I have a question about a loop I created on this page https://movementrebels.com/movement-rebels/

I´ve created a post grid with your loop based on the flip-box widget. It looks great when I edit the page but on the live site I see a weird design of it. Any suggestions of what it could be?

Peter

**Comment by dudaster** [comment]
I’ll take a look

**Comment by fasonera** [comment]
> I’ll take a look

Any luck?

**Comment by dudaster** [comment]
Please add a fallback image to the dynamic background

**Comment by fasonera** [comment]
Thanks! It works now.
