### ISSUE TITLE
Ele custom skin blocks loading of the website on iOS devices (works on desktop at the same time)

### ISSUE THREAD

**Issue by outwork** [dudaster/ele-custom-skin#335]
Hi. The latest version of the plugin (even older version – v2.2.2) stops working on iOS devices. It works just fine on desktop and android phones. As soon as I disable the plugin on my iphone, the website loads, but if enable it, the loading of the website will hang for minutes and loads only partially. Everything is updated to the latest version (WP, Elementor, Elementor PRO, Ele custom skin).

Website URL: https://app-5efbb6d3c1ac181508281db1.closte.com/

**Comment by dudaster** [comment]
the issue is with heavy hover effects and not with the plugin.
