### ISSUE TITLE
How can I have 2 lines and one line in one Grid? 

### ISSUE THREAD

**Issue by simea-simea** [dudaster/ele-custom-skin#336]
I would like to build something like that: https://www.nau.ch/
But I can not manage to build it that on the top left there is one post and on the right there are two posts above each other. I always get this: 
![image](https://user-images.githubusercontent.com/48213023/92716148-b6594300-f35e-11ea-9635-ddead6c41294.png)

What am I doing wrong?

**Comment by dudaster** [comment]
you need to add 2 inner sections in one column for this to work.
