### ISSUE TITLE
Help at height

### ISSUE THREAD

**Issue by eliranyaakov** [dudaster/ele-custom-skin#339]
Hello, I have a problem, 
I created a post page designed using Ele Custom Skin Pro, and set it to Same Height.  The problem is that I want the price and the button in all the posts to be down.
I Would appreciate help.

https://pilots.vangus-c2.link/product-category/%d7%94%d7%96%d7%9e%d7%a0%d7%aa-%d7%98%d7%99%d7%a1%d7%94/

**Comment by dudaster** [comment]
Use absolute position and set it to bottom.

**Comment by eliranyaakov** [comment]
You can help me I did not really understand I would be happy to help

**Comment by dudaster** [comment]
https://www.youtube.com/watch?v=vJ851SD-6u0
