### ISSUE TITLE
Safari on Mac unable to "Select a template"

### ISSUE THREAD

**Issue by riderworks** [dudaster/ele-custom-skin#34]
I wasn't able to select my Template Loop in the Edit Posts -> Content -> Layout in Safari on Mac. It was visible in the PopUp, but it would never insert it into the "Select a template" field. 

I had to use Google Chrome to get it to work. Once it was saved in Chrome, Safari had the field populated.

**Comment by dudaster** [comment]
I’m afraid it is an elementor issue. I just used their control classes to generate the edit section.

**Comment by one-globe** [comment]
I experienced the same thing. Unless you contact with Elementor, they don't fix it.  Can you do it?

**Comment by riderworks** [comment]
I submitted a ticket to Elementor. I’ll let you know how they reply.
--
Doug Rider

**Comment by riderworks** [comment]
Hi,

This is the response from Elementor support regarding Ticket #34.
--
Doug Rider

> Begin forwarded message:
> 
> From: Elementor <support@elementor.com>
> Subject: Re: EL Edit Posts Module - In Safari on Mac, Custom Setting not working
> Date: August 23, 2019 at 11:53:37 AM PDT
> To: Doug Rider <support@riderworks.com>
> 
> Pepe replied
> Aug 23, 18:53
> Hi Doug,
> 
> Thank you for contacting us and I apologize for the delay in response since we are having a high volume of tickets.
> 
> I'm afraid that the posts widget only has the "Classic" and "Cards" skin as shown in the screenshot below:
> 
> 
> Elementor doesn't have a custom skin and it seems that you're using Ele custom skin third-party plugin for this, unfortunately, we cannot provide support for third-party plugins due to our support policy, I kindly suggest to report this issue to the third-party plugin developer, they'd be in a better position to address or provide you a quick fix for this.
> 
> We appreciate your understanding.
> 
> Kind regards,
> 
> 
> --
> Elementor Technical Support
> Facebook <https://www.facebook.com/elemntor/> | Twitter <https://twitter.com/elemntor> | YouTube <https://www.youtube.com/c/elementor> | Instagram <https://www.instagram.com/elemntor/>
> Join the conversation & learn from our Elementor Community <https://www.facebook.com/groups/Elementors/>
> 
> How would you rate my reply? 
> 
> Doug Rider sent a message
> Aug 22, 16:08
> Before you open a ticket, please type your issue in a few words:
> post module custom setting
> Name
> Doug Rider
> Email
> support@riderworks.com <mailto:support@riderworks.com>
> Subject
> Technical Support
> Have you tried to "deactivate all other plugins" and "switched to a default WP theme"?
> No, still haven't tried it
> Summary
> EL Edit Posts Module - In Safari on Mac, Custom Setting not working
> Message
> Hi, I'm not able to select and activate the Custom setting in the EL Edit Posts Module in Safari on Mac. I have to go to Chrome or Firefox to activate the Custom setting. I'm using the latest versions of EL and Ele Custom Skin (which places the loop).
> 
> Thanks,
> Doug
> URL
> https://riderworks.com/test-page/ <https://riderworks.com/test-page/>
> Upload System Info
> system-info-riderworks.com-22-08-2019.txt <https://my.elementor.com/index.php?gf-download=2019%2F08%2Fsystem-info-riderworks.com-22-08-2019.txt&form-id=2&field-id=13&hash=449333aec499c89b1f59c3e26723d1eca1caa88de378df8df6f231ee5b5f503e>
> Screenshot-of-Safari-8-22-19-9-04-09-AM.png <https://my.elementor.com/index.php?gf-download=2019%2F08%2FScreenshot-of-Safari-8-22-19-9-04-09-AM.png&form-id=2&field-id=13&hash=f162b3dc7141530608290fea7835a97beb6fb57f0b2eb2b14956efa43409f2a4>
> ---
> 
> IP: 73.11.29.45
> 
> Date: 22/08/2019
> 
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.2 Safari/605.1.15
> 
> {#HS:936134130-729016#}

**Comment by dudaster** [comment]
Can you provide me a video with this happening? I have Version 12.1.2 (13607.3.10) on MacOs and I don't have this issue you describe.

**Comment by riderworks** [comment]
Hi,

I just checked again. So both EL and your plugin have been updated and I’m not experiencing the issue anymore in Safari.
--
Doug Rider

**Comment by one-globe** [comment]
Hello.  I confirmed that it is working under Safari.  Thank you.

**Comment by dudaster** [comment]
I managed to reproduce this problem. I oppened a ticket to elementor https://github.com/elementor/elementor/issues/8944

**Comment by dudaster** [comment]
Fixed with latest ECS
