### ISSUE TITLE
Plugin Bugs My Website & Crashes It

### ISSUE THREAD

**Issue by infinitymusc** [dudaster/ele-custom-skin#340]
Whenever the plugin is installed I cannot access my website and this message pops up. 

Fatal error: Uncaught Error: Class 'ElementorPro\Core\Utils' not found in /var/www/wp-content/plugins/ele-custom-skin/theme-builder/conditions/loop.php:39 Stack trace: #0 /var/www/wp-content/plugins/elementor-pro/modules/theme-builder/conditions/condition-base.php(66): ECS_Loop_Conditions->register_sub_conditions() #1 /var/www/wp-content/plugins/ele-custom-skin/theme-builder/conditions/loop.php(67): ElementorPro\Modules\ThemeBuilder\Conditions\Condition_Base->__construct() #2 /var/www/wp-includes/class-wp-hook.php(287): {closure}(Object(ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager)) #3 /var/www/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array) #4 /var/www/wp-includes/plugin.php(478): WP_Hook->do_action(Array) #5 /var/www/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(239): do_action('elementor/theme...', Object(ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager)) #6 /var/www/wp-includes/class-wp-hook.php(287): ElementorPro\Modules\ThemeBu in /var/www/wp-content/plugins/ele-custom-skin/theme-builder/conditions/loop.php on line 39

Please Help.

**Comment by dudaster** [comment]
This errors occurs because you have an older version of Elementor if you can't upgrade use an older version of ECS that you can find in the wordpress repository advanced section of the plugin page.
