### ISSUE TITLE
The heights of all the carousel items have suddenly increased

### ISSUE THREAD

**Issue by ashkan-ahmadi** [dudaster/ele-custom-skin#343]
Hi

Starting from a couple of days ago, all the carousels on our website suddenly have become much longer going on top of the sections below them and I can't figure out why. I tried with other skins and the problem continues.

This is how it looks now: https://prnt.sc/ul4gqq
You can see it live here: https://www.studentfy.com/trips

This is how it should look: https://prnt.sc/ul4ie1

Can you please check what the issue is? This has affected all the carousels with different post types on our website. Thanks

**Comment by dudaster** [comment]
Set Column Gap to 0
