### ISSUE TITLE
Can't get equal height to work

### ISSUE THREAD

**Issue by dpdodson** [dudaster/ele-custom-skin#344]
Purchased the Pro version just for the equal height feature and it doesn't work. I've rebuilt the Loop template twice, it's very simple. It just won't work.

Site is password protected. I can send credentials privately.

**Comment by dudaster** [comment]
Try give it a background color to the main section in loop template. Also please make sure you have only one main section.

Also use absolute positioning for the widgets you want to stick to the bottom.

**Comment by dpdodson** [comment]
I have a background color and a border.
<img width="1279" alt="Screen Shot 2020-09-21 at 12 18 05 PM" src="https://user-images.githubusercontent.com/6026170/93793395-c4cc1800-fc04-11ea-8e7d-764819304f20.png">

**Comment by dudaster** [comment]
Now go to the button widget and set its position to absolute in advanced tab and align it to bottom.

Also give some padding to the bottom to the widget that displays the post summary not to overlap to your button.

**Comment by dpdodson** [comment]
Thanks. The buttons are bottom aligned, but the boxes are still unequal.

<img width="1279" alt="Screen Shot 2020-09-21 at 1 02 09 PM" src="https://user-images.githubusercontent.com/6026170/93797841-c13b8f80-fc0a-11ea-93bc-369df38d6472.png">

**Comment by dudaster** [comment]
Make sure the main section doesn’t have any padding or margin

**Comment by dpdodson** [comment]
Everything is on Default. Should it be set to zero?

**Comment by dpdodson** [comment]
That would make everything look really bad.

**Comment by dudaster** [comment]
Go to the chat on dudaate and provide me the url to check the css

**Comment by dudaster** [comment]
The main section doesn need to have any margin its css
