### ISSUE TITLE
Pagination and URL

### ISSUE THREAD

**Issue by pako69** [dudaster/ele-custom-skin#347]
Hi

When I use the load more (button or infinite) the URL of the page change to https://www.mysite.com/my-slug/page/2/

I don't what this /**page/2/** to be visible as Google would be able to scroll it!

If you are using Ajax, it should not change the URL and keep the same...

And worst, and a user hit the back button of his browser he will go from /**page/3/** to /**page/2/** then from /**page/2/** to **/**  

Thanks

**Comment by strijant** [comment]
I have the same request here. Would be great to have clean url instead of the pagination.

Will appreciate if you fix that.

Thanks :)

**Comment by dudaster** [comment]
It will be fixed with the next version where you have an option to do it or not

**Comment by dudaster** [comment]
if you want a quick fix go to /plugins/ele-custom-skin/assets/js/ecs_ajax_pagination.js and comment this line at the end of the file:

`// ECS_add_action("ajax", function(args){EleCustomSkinChangeUrlPage(args)});`

**Comment by pako69** [comment]
Hi @dudaster 

This quick fix work BUT in not in the source code we still have a pagination that make a 301 redirection and that's not good for SEO...

```
<a href="https://www.mydomainecom/my-slug/?page=2" class="elementor-button-link elementor-button " role="button">
<span>Afficher +</span>
</a>

```

**Comment by elias1435** [comment]
Hello,
i have followed @dudaster but still same when press back button from single post page its showing "It looks like nothing was found at this location."

would you help me to fix it

Thanks
