### ISSUE TITLE
Woocommerce visibility by role

### ISSUE THREAD

**Issue by Jcsolvi** [dudaster/ele-custom-skin#348]
Hi,

I can't manage to make product visibility by role.
The plugin is not complicated a check box to hide or not a category

Nothing change on archive page made with ele custom skin and custom loop.
Is it because we use the post and query the product instead of using the woocommerce short code for archive or shop page ? 

Thanks a lot for your help

**Comment by dudaster** [comment]
Try using current query. Also you can try using other conditional display plugins.
Let me know what you found!

**Comment by Jcsolvi** [comment]
Thanks 
The WooCommerce plugin only work with woo shop page
So we change for the plugin republic one and it works
