### ISSUE TITLE
Support for Query filters for custom post types

### ISSUE THREAD

**Issue by austinsparx** [dudaster/ele-custom-skin#349]
Hello, I'm using Ele Custom Skin for a posts grid for a custom post type 'Properties' which is working well.

Only issue is this post type has a custom status field (current, sold). I want to limit the query to only properties that are current, but in the query options here this isn't an option.

Is this possible with this plugin?

**Comment by austinsparx** [comment]
Can I use the custom query instructions here to apply to Ele Custom Skin?
https://developers.elementor.com/custom-query-filter/

**Comment by dudaster** [comment]
Yes it is supported

**Comment by austinsparx** [comment]
Great thanks 👍
