### ISSUE TITLE
blank home page error

### ISSUE THREAD

**Issue by mohamedmanas23** [dudaster/ele-custom-skin#35]
after moving my site to new server, having the plugin enabled is causing my home page to go blank, while all the other pages are working fine. if i deactivate the plugin the home page is loading and showing content. so when the plugin is activated the home page goes blank and every other pages shows up fine. please help on this

**Comment by dudaster** [comment]
You need to turn wp_debug true in wp-config and the give me the error it shows. I cannot help you otherwise.

Also I need you to mention what versions of elementor you are using and what version of ECS.

**Comment by mohamedmanas23** [comment]
Hi,

Thank you so much for the prompt reply,

turning on wp_debug is not showing any error.
ECS version is: 1.0.9
Elementor version is: 2.4.7


all the other pages that uses the plugins template to display is working
fine. just the home page. when I remove the particular section on the
homepage that uses the plugin to show a template then the homepage also
shows up fine.

I have tried almost everything, could you please see if you could help on
this?

thank you so much

best regards,
Mike

**Comment by dudaster** [comment]
What is the Elementor Pro version?

**Comment by mohamedmanas23** [comment]
Elementor pro version: 2.4.6

**Comment by dudaster** [comment]
is there an error.log file on the webpage folder? Does it have an error?

**Comment by mohamedmanas23** [comment]
that's the thing, there is no error at all, even when the wp_debug is set to true..
everything was working fine on the old server which was (nginx) now the new server is apache...

**Comment by mohamedmanas23** [comment]
I thought may be it's the script timeout and even set up php.ini as below, but still didn't help: 

memory_limit = 256M
upload_max_size = 256M
post_max_size = 256M
upload_max_filesize = 256M
max_execution_time = 500
max_input_time = 3000

**Comment by dudaster** [comment]
It is feasible to update to the latest version?

**Comment by mohamedmanas23** [comment]
latest version of the plugin?

**Comment by dudaster** [comment]
yes 

E - 2.5.16
EPRO -  2.5.9
ECS - 1.1.2

**Comment by mohamedmanas23** [comment]
updated all 3 of them. still the same issue....

**Comment by dudaster** [comment]
send me an email with the login data to your website to take a look

**Comment by mohamedmanas23** [comment]
I have emailed you the credentials,  please take a look. thank you so much!

**Comment by dudaster** [comment]
As far as I see you have a memory issue. I know you set it up to 256M but you only get around 120M.
Check out this issue here for more info: 
https://stackoverflow.com/questions/13955914/php-out-of-memory-error-even-though-memory-limit-not-reached

Hopefully when this issued would be solved the plugin would work properly.

**Comment by mohamedmanas23** [comment]
Hi Dudaster,

thank you for the swift reply, thanks for the clue, so changes made on
php.ini is not having any impact on the memory increase and I will have to
increase the memory on the server level, let me try this and get back to
you.

thank you so much once again!
