### ISSUE TITLE
Same height not working in tablet

### ISSUE THREAD

**Issue by mellymine** [dudaster/ele-custom-skin#356]
Hello! Same Height isn't working for me in tablet, but it is working great in desktop view.  My settings are the same for desktop and tablet. Can you help? Ty!
<img width="1012" alt="tablet" src="https://user-images.githubusercontent.com/48569270/95029268-9de1fd00-066c-11eb-88f7-06e8819f16a3.png">
<img width="1208" alt="desktop" src="https://user-images.githubusercontent.com/48569270/95029269-9e7a9380-066c-11eb-9ead-dae5ec6600a3.png">

**Comment by dudaster** [comment]
Please make sure the article doesn’t have any padding on tablet view. This might be the issue.

**Comment by mellymine** [comment]
I verified that there is no padding in tablet view on the article or its column / container.  They are all set to "0".
