### ISSUE TITLE
Adding "Menu_Order" Sort  Custom Skin Loop

### ISSUE THREAD

**Issue by ageekonabike** [dudaster/ele-custom-skin#36]
I have created custom post types for an art gallery website.In the customskn loop, I've added conditions that will display alternating sections in the custom loop based on the custom post's Menu Order. But I also need to specify the menu order sorting in the Elementor Pro's Archive Posts widget.

Is there a way to add sort ordering with "Menu_Order" to the Elementor Archive Posts widget UI when selecting a custom Skin?

Website: 
![Elementor - AGOAB – Portfolio - ageekonabike com](https://user-images.githubusercontent.com/47322772/60908137-6487cb00-a238-11e9-926d-7d2b1715ab6a.png)
https://ageekonabike.com/art_portfolio/

**Comment by dudaster** [comment]
The plugin is just a skin... Maybe in the future I'll release a plugin that does just that.
