### ISSUE TITLE
plug-in files Ele custom skin pro

### ISSUE THREAD

**Issue by wouterdeboeck** [dudaster/ele-custom-skin#361]
Where can i download the plugin files fo elementor custom skin pro? I have a licence key, but no plugin files and can't find a download link.

**Comment by dudaster** [comment]
Currently you should look from emails from gumroad and you'll find the link there. If you are having problems finding the email, please use the chat on dudaster.com and I'll resend you the email.

**Comment by bartistiek** [comment]
> Currently you should look from emails from gumroad and you'll find the link there. If you are having problems finding the email, please use the chat on dudaster.com and I'll resend you the email.

I also think it would be convenient to have a customer login instead of using the e-mail. I was looking for it today as well (since  I always forget it is not available)

**Comment by dudaster** [comment]
I know, and it is in the works.
