### ISSUE TITLE
ACF Text Area and WYSIWYG editor fields not displaying

### ISSUE THREAD

**Issue by willcitizen** [dudaster/ele-custom-skin#37]
Busy updating a site on an offline backup that I haven't worked on for a while. After updating to the latest versions of ACF, Elementor and Custom Skin dynamic fields inside the loop using text area and wysiwyg editor fields are no longer being displayed.

I have verified that this is the issue by editing the loop skin and setting a simple text type field from the same table to be displayed and this works.  The field is correctly displayed in the Elementor Editor

This is the live page, where it is still working - the dynamic field is the team member bio displayed when hovering over the profile pictures (the reveal is a simple css font color trick so there is no issue there either).

http://www.dogzathome.co.za/our-team/

*update* Apologies on closer examination I remembered that I had enabled beta testing on my local site - rolling back to the current stable Elementor releases resolved the issue, so this is a bug introduced in the 2.6 betas

**Comment by dudaster** [comment]
Fixed with the new version
