### ISSUE TITLE
Missing Posts Inside Slider

### ISSUE THREAD

**Issue by alexanderramsey** [dudaster/ele-custom-skin#379]
I have ECS Pro and am having an issue with posts not showing up in the slider on my website. There are empty gaps where a post should be displayed. Do I need to reinstall the plugin?

You can see an example of what I mean at the bottom of this page: https://alexander-ramsey.com/services/branding/

Love your plugin!

**Comment by dudaster** [comment]
Usually this happens if you have entrance animations. Those don’t work well horizontally

**Comment by alexanderramsey** [comment]
That was it! Thanks for the help and super fast reply!
