### ISSUE TITLE
I have issue to clear the cache after upgrading WP and Plugins.

### ISSUE THREAD

**Issue by robert1112** [dudaster/ele-custom-skin#380]
Hi I got problem to clear the cache after upgrading WP and Plugins. I clear the browser and CDN cache, and all plugin cache but it still stuck here. I have tried many including disable ele-custom-skin plugin and enable it. If i create a staging site then, it displayed correctly.

Where can you send you the link to the page? Thank you so much.

**Comment by dudaster** [comment]
you can use the chat on dudaster.com

**Comment by robert1112** [comment]
Thank you.
