### ISSUE TITLE
Cannot edit or create new loops after updating

### ISSUE THREAD

**Issue by EmerKelly** [dudaster/ele-custom-skin#385]
Hello,

I discovered this issue on my site today, and am assuming it has to do with the updates I ran a couple of days ago. When I try to edit a loop template, or create a new one, I get the below error notice. Does anybody know how to solve this?

<img width="516" alt="Screen Shot 2020-11-13 at 4 05 03 PM" src="https://user-images.githubusercontent.com/15749524/99121742-f640de80-25ca-11eb-97f9-b65c8ede2ce0.png">

**Comment by eiPisti** [comment]
Hi, I had the same issue and I solved reading the FAQs section, it's the second most common issue.

https://github.com/dudaster/ele-custom-skin/issues/201

I hope it can be helpful to you too!
