### ISSUE TITLE
FacetWP + ACF (advanced custom fields) lose custom fields after filter applied

### ISSUE THREAD

**Issue by designworksinteractive** [dudaster/ele-custom-skin#39]
The plugin is a fantastic Idea and very well Implemented and love using the elementor builder to create a loop but have run into issue with using FacetWP + ACF (advanced custom fields) as they lose custom fields on the cards after filter applied they are working perfectly before filter is applied.

Any help would be greatly appreciated :)

UPDATE - data is shown with manual page refresh

UNFILTERED CARDS
![unfiltered](https://user-images.githubusercontent.com/5876894/61596354-21dfce80-abfa-11e9-8183-9cb41e46b5ba.png)

FILTERED CARDS
![filtered](https://user-images.githubusercontent.com/5876894/61596352-21dfce80-abfa-11e9-98b7-abbb8d02bf93.png)

FILTERED CARDS + REFRESH
![filtered+page refresh](https://user-images.githubusercontent.com/5876894/61596353-21dfce80-abfa-11e9-8d92-b45acf791564.png)

**Comment by dudaster** [comment]
A new version is up. Let me know if it’s working properly.

**Comment by designworksinteractive** [comment]
Hello so much for you work but afraid my issue still persists, think it is an issue with refresh after filter

[http://www.c435f0b12ad4d4fd7380e362b-42075.sites.k-hosting.co.uk/codeworksv2/archive/](url)

**Comment by dudaster** [comment]
Check if you have issues with php memory.

**Comment by dudaster** [comment]
Hmm, I’ll study it tomorrow, could be an Ajax issue.

**Comment by designworksinteractive** [comment]
> Check if you have issues with php memory.

thank you will do

**Comment by designworksinteractive** [comment]
> Hmm, I’ll study it tomorrow, could be an Ajax issue.

can give you admin access to site

**Comment by designworksinteractive** [comment]
**ISSUE FIXED**

1) install http://api.facetwp.com/addons/custom-hooks.zip

2) plugins/edit plugin

3) select "custom-hooks"

4) edit php file adding below code

> <?php
/*
Plugin Name: Custom Hooks
Plugin URI: https://facetwp.com/
Description: A container for custom hooks
Version: 1.0
Author: FacetWP, LLC
*/

add_action( 'wp_head', function() {
?>
<script>
(function($) {
    $(document).on('facetwp-refresh', function() {
        if (FWP.loaded) { // after the initial pageload
            FWP.parse_facets(); // load the values
            FWP.set_hash(); // set the new URL
            location.reload();
            return false;
        }
     });
})(jQuery);
</script>
<?php
}, 100 );

**Comment by geowebnerd** [comment]
I'm having trouble with FacetWP filters working on this page: https://www.thefrenchhistorypodcast.com/podcast/

I've tried the fix above, cleared all caches, and filters are still not working. Thanks for any help you can provide.
