### ISSUE TITLE
Background overlay not showing on site even though updated on the loop on theme builder.

### ISSUE THREAD

**Issue by NoDishrespect** [dudaster/ele-custom-skin#393]
We've updated our home page layout using elementor custom skins pro plugin. We're really happy with the look, but for some reason the background overlay doesn't show on our live site. Sometimes when refreshing the page it will appear correctly, but then disappears shortly after reloading the page again, which is annoying because we need the overlay so that our meta is readable. Everything looks correct when we look at the backend of the page (editing with elementor), but doesn't show when live. I've tried regenerating the CSS on elementor, as well as clearing the wordpress & browser cache, but this hasn't worked. I've attached some photographs to help explain what I'm talking about.

Another thing is that one of our recipe titles (Chilli Chicken) doesn't show on the post tile on our reel, even though the title is written on the post's metadata & SEO details. Also, the featured posts banner on top of our page overlaps with our header when scrolling down - we want the banner to be static and not do this. Again I've attached more photos to show what I mean.

We have refreshed our caching settings on our hummingbird plugin as well as the main sites caching and the browser cache. That hasn't seemed to do anything. When we update the loop and go straight on the home page it seems work of a minute then goes back to what we have shown you in the pictures below.

<img width="1440" alt="Banner overlapping header (1)" src="https://user-images.githubusercontent.com/75060757/100314487-dcf85300-300a-11eb-932e-f0b46fc8f073.png">
<img width="387" alt="Title not showing on post (1)" src="https://user-images.githubusercontent.com/75060757/100314493-dec21680-300a-11eb-80b7-8227b28c44c0.png">
<img width="1440" alt="How it looks on the live site 2 (1)" src="https://user-images.githubusercontent.com/75060757/100314500-e2ee3400-300a-11eb-811a-21fbf4650776.png">
<img width="1440" alt="How it looks on the live site (1)" src="https://user-images.githubusercontent.com/75060757/100314502-e4b7f780-300a-11eb-888a-5b72db469fae.png">
<img width="1440" alt="How it should look (1)" src="https://user-images.githubusercontent.com/75060757/100314507-e681bb00-300a-11eb-8c21-b9326705d9e3.png">

**Comment by dudaster** [comment]
Is there a way I can access nodishrespect.com?

**Comment by dudaster** [comment]
NVM. The second try worked.

**Comment by dudaster** [comment]
Can you give ma an example of how it should work?

**Comment by NoDishrespect** [comment]
Hi Liviu,

I've attached two screenshots for example: one showing how the site should look with the background overlay; the other showing the error.

________________________________

**Comment by dudaster** [comment]
Please attach them on github... don't reply them trough email because it doesn't work.

**Comment by NoDishrespect** [comment]
<img width="1440" alt="How it should look (1)" src="https://user-images.githubusercontent.com/75060757/100326533-3158fe00-301e-11eb-8a83-80baa1b33478.png">
This is how it should look

**Comment by NoDishrespect** [comment]
This is how it looks 
<img width="1440" alt="How it looks on the live site (1)" src="https://user-images.githubusercontent.com/75060757/100326681-5ea5ac00-301e-11eb-8e5c-7dab02b0938a.png">

**Comment by NoDishrespect** [comment]
Sometimes it appears, and then you will refresh the page and its missing again. The same thing is happening on to separate loops. We have cleared the caching settings on our hummingbird plugin as well as the main sites caching and the browser cache.

**Comment by NoDishrespect** [comment]
Hi Liviu,

I'm still waiting for a response from you. I've sent the images over on github already.
________________________________

**Comment by dudaster** [comment]
Sorry for the late response....

It is definatly a css issue. Please can you go on elementor tools and regenerate the css!

**Comment by NoDishrespect** [comment]
I’ve already tried doing that.

I regenerated the css twice before contacting you, as well as clearing the Wordpress & browser cache, which only temporarily fixes the problem. It goes back to doing the same thing shortly after.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by NoDishrespect** [comment]
Hi Liviu,

I still haven't heard any responses from you. This is taking a rather long time to resolve and I'd really appreciate some help with this issue as soon as possible.

I've sent you a reply on Wednesday explaining that I've already tried regenerating the css on Elementor twice, and since your message I have done so a third time, but to no avail. Regenerating the cache also has not solved the problem, and the background overlay continues not to show up.

This is becoming very frustrating for me as I feel like I'm going in circles with whoever I approach with this issue, and as of present no real solution has come to surface at all. This problem has persisted for over two weeks now.

I hope you understand my frustration.
________________________________

**Comment by dudaster** [comment]
I don’t see the problem at my end. Please use the chat on dudaster.com maybe we can solve this issue quicker

**Comment by dudaster** [comment]
The issue doesn't have to do anything with Ele Custom Skin. Is an issue with your css minifying plugin. After debugging your css code I found out that this css rule

`background-image: linear-gradient(180deg, #00000000 18%, #000000FC 60%);` 

after minified gets to:

`background-image: linear-gradient(180deg,#00000 18%,#000FC 60%);`
