### ISSUE TITLE
Feature Request: Custom Skin support for Post Slider / Carousel

### ISSUE THREAD

**Issue by collindavis** [dudaster/ele-custom-skin#4]
Any chance of making your custom skin plugin support custom skins for post carousel or sliders? Or just making your own post slider/carousel widget that could take advantage of custom skin? Would really love a way to create a custom loop and then use it with my custom skin within a post slider or carousel. Thanks!

**Comment by dudaster** [comment]
I'll look in the future for a well established free widget that does this already and I'll make it  work for it.

**Comment by dudaster** [comment]
The slider feature is in ECS Pro now.
