### ISSUE TITLE
Ele Custom Skin not compatible with UAE Modal Popup

### ISSUE THREAD

**Issue by sommarzan** [dudaster/ele-custom-skin#40]
https://www.pocoapoco.se/instruments-dynamically/

I am working on a music instrument-page. The image, title, text and url of the button gets fetched dynamically. I use PODS and Ele Custom Skin.

**Problem:** if you click on the first button (violin) you see the violin-video. 
BUT if you click on the viola-button (or cello or any other instrument) you also see the violin-video.

I am using the "Modal Popup" from "Ultimade addons for Elementor". I have been in contact with their support, and they say "_We print the Modal Popup content through a shortcode. This is the case that the Elementor Custom Skin plugin is duplicating the skin with different results resulting in printing the same HTML. Hence, as of now, it is not possible to use the Modal Popup dynamic field feature with the Elementor Custom Skin plugin._"

Is there somehow you can help?

**Comment by dudaster** [comment]
I don't know how they work but if you say that it works with shorcode, you can make a custom field with the shortcode for each post and assign it to the skin template.

**Comment by sommarzan** [comment]
This is too difficult for me. I don't understand. Is it possible for you to make a video?

**Comment by dudaster** [comment]
Make me an user on your website and let me see what I can do. I don't have UAE Pro (I make my own stuff) so I cannot make you a video of any kind.

**Comment by sommarzan** [comment]
Sure thing! 
I have sent you login details on Facebook via PM.

**Comment by dudaster** [comment]
UAE Modal Popup not compatible with ECS, use other plugins/widgets!
