### ISSUE TITLE
Unable to create / edit Template

### ISSUE THREAD

**Issue by wpfantomaster** [dudaster/ele-custom-skin#410]
Hi,

I purchased ECS Pro a while ago and did not use it much up to now.
I remember it worked fine (approx. a year ago), but now it seems broken.
When trying to create / edit a template Elementor tries to load but shows "Try safe mode" after ~30s.
By clicking on Safe Mode I get thrown back to the posts overview dashboard.

WP 5.6
EL 3.0.15
EL Pro 3.0.9
ECS Pro 3.0.0
Theme Astra 2.6.2

max_execution_time | 30
memory_limit | 256M

I have turned on debugging but dont' get any errors.

Thanks for your help in advance!

**Comment by dudaster** [comment]
do you have issues only with pro version or it works ok with only the free versions?

**Comment by wpfantomaster** [comment]
In both versions - but I already switched to another tool (dynamic.ooo) since there was no time for further investigation.
