### ISSUE TITLE
Activated License not working

### ISSUE THREAD

**Issue by rastaprime20** [dudaster/ele-custom-skin#411]
Hi,

Hope you are well.

I would like to inform that even if we entered a valid license code for the Pro version of the plugin, it doesn't seem to unlock the features of the pro version from Elementor's page builder.

Kindly let me know what information you need so someone can check it please.

Regards,
Tyrone F.

**Comment by dudaster** [comment]
Hi,

Make sure you have the pro version along the free version installed.

The pro version you can download it from the link you received with the purchase.

**Comment by rastaprime20** [comment]
Hi,

Many thanks for your quick response.

Both the free version and pro version are installed and activated.

Please see screenshot below:

![Screenshot from 2021-01-05 16-16-43](https://user-images.githubusercontent.com/4940101/103622426-aef32080-4f71-11eb-8983-0356039d44b3.png)

![Screenshot from 2021-01-05 16-19-40](https://user-images.githubusercontent.com/4940101/103622541-d813b100-4f71-11eb-897f-87230411b67d.png)


Regards,
Tyrone F.

**Comment by dudaster** [comment]
![ecs-license-page](https://user-images.githubusercontent.com/8319178/103631462-ac7dd000-4f4b-11eb-854b-41d232b59828.PNG)

Do you see this page (Ele Custom Skin Pro License) in Settings Menu?

**Comment by rastaprime20** [comment]
Hi,

This is to confirm that I can see the menu item under the Settings Menu in the WP Admin

Kindly see screenshot below

![Screenshot from 2021-01-05 18-02-34](https://user-images.githubusercontent.com/4940101/103633180-570fe600-4f80-11eb-841f-017827df4d31.png)


Regards,
Tyrone F.

**Comment by rastaprime20** [comment]
Hi, 

Do you need more info to check on this? 

Let me know if you need more info about this.

Regards,
Tyrone F.

**Comment by dudaster** [comment]
I see you use multisite wordpress. Can you enable the the pro version on all the websites?

**Comment by rastaprime20** [comment]
Hi,

Many thanks.

That worked! 

Regards,
Tyrone
