### ISSUE TITLE
More than one loop template in Custom Grid

### ISSUE THREAD

**Issue by hmeerend** [dudaster/ele-custom-skin#417]
Is it possible to use more than one Post Loop Template in a Custom Grid?
See attached screenshot.
![More than one post loop template in Custom Grid](https://user-images.githubusercontent.com/71458278/104026288-fe318f00-51c5-11eb-998e-271f1a02512f.png)

I would like to build a similar page using Ele Custom Skin with the Custom Grid feature.

**Comment by dudaster** [comment]
you can with the pro version

**Comment by hmeerend** [comment]
Thanks for your reply.
I have solved the problem myself by switching Minification of CSS and JS
files in Cloudways' Breeze plugin OFF.

Regards,
Hans van Meerendonk
