### ISSUE TITLE
The content area was not found

### ISSUE THREAD

**Issue by e1e1e1** [dudaster/ele-custom-skin#421]
Got this message when create a loop template. Other template is working 
![Screen Shot 2021-01-12 at 5 58 55 AM 12 January 2021](https://user-images.githubusercontent.com/226406/104213970-c6636980-549b-11eb-994f-a1c988dcb183.png)

**Comment by dudaster** [comment]
didi you check this: https://github.com/dudaster/ele-custom-skin/issues/201?
