### ISSUE TITLE
License key 

### ISSUE THREAD

**Issue by hristo-laskov** [dudaster/ele-custom-skin#422]
Hello!

I purchased Ele Custom Skin Pro (great work, by the way), but somehow my session on gumroad.com was terminated and now I can't see my license key anywhere. Please be so kind to help me out. Thanks!

**Comment by dudaster** [comment]
Do you still have the email from gumroad?

**Comment by hristo-laskov** [comment]
Yes, issue is solved. Thanks for the fast reply.
