### ISSUE TITLE
Error Every Time I Install

### ISSUE THREAD

**Issue by juscuizon** [dudaster/ele-custom-skin#424]
I get this error every time I try to install the plugin "There has been a critical error on your website". I have to delete the plugin folder on my cpanel to regain access to my dashboard. Is there a proper way to install this? I installed it via the WordPress plugin search.

**Comment by dudaster** [comment]
Make sure you have the latest elementor if not try older versions of Ele
Custom Skin

**Comment by juscuizon** [comment]
found the fix changing the path to ElementorPro\Classes\Utils
