### ISSUE TITLE
Same Height not working

### ISSUE THREAD

**Issue by 10XiD** [dudaster/ele-custom-skin#425]
Hello guys,
I have paid for this plugin to use the same height, but it not works :(

**Comment by dudaster** [comment]
Make sure you have one section in loop template and give it a colored background and make a screenshot to take a look

**Comment by bradleybacon** [comment]
I'm having the same issue. I have a Loop that contains a single section with a CTA. 

I'm attempting to display two of the CTAs using the same height: https://knownestle.com/

**Comment by dudaster** [comment]
if you added the background to the column make sure the column position is set to stretched.
