### ISSUE TITLE
PRO Slider columns not working

### ISSUE THREAD

**Issue by studio84** [dudaster/ele-custom-skin#426]
Dear,

I made this site over a month ago and all was working well. When I recently visited the site all custom skin sliders had different columns than setup before. I didn't make any changes myself.
https://media.studio84.be/ApuGZ2w9
http://dev.nuflow.be

I tried to recreate the post widget from scratch but I face the same problem.

Thanks for helping me out.

**Comment by dudaster** [comment]
What version of ECS Pro do you have?

**Comment by studio84** [comment]
3.0.0
https://media.studio84.be/Koulg2wZ

**Comment by dudaster** [comment]
Thanks for pointing it out! I'll check it out.

**Comment by studio84** [comment]
Thanks for the fast follow up Liviu. I encounter the same problem with the
news slider below it:
https://media.studio84.be/OAuWke6D

**Comment by dudaster** [comment]
I think it is an issue that needs to be solved because of the changes made in elementor 3.1. You can reverse to the v3.0(stable version) if it is in production

**Comment by studio84** [comment]
Hey Liviu, bringing back the elementor version solved the problem!
