### ISSUE TITLE
Elementor Custom Skin Pro Features

### ISSUE THREAD

**Issue by sambbaron** [dudaster/ele-custom-skin#43]
Hello, I'm curious what are the additional features with Elementor Custom Skin Pro. From the website, I only see alternating templates. Is that the only feature? Would you share what other features you are planning? Thanks!!

**Comment by dudaster** [comment]
Hi, currently only alternating templates. Second to be able to add dynamic content in the all the widgets field by inserting keyword like {{_price}} to create a price list with price list widget for example.

The second feature is set to be release next week.

After that I plan to do some cosmetic stuff like post slider, and other ways you can display the grid.

And many other things. Sky is the limit.

**Comment by sambbaron** [comment]
That's great, thank you for sharing your plan! The alternating templates are not that interesting to me, but the dynamic content and post slider are definitely something I would use.
