### ISSUE TITLE
Link = post url is not working get redirected to page the customer is already on.

### ISSUE THREAD

**Issue by takemeoutevents** [dudaster/ele-custom-skin#430]
Hi there,

I have created a loop using your plugin.
I have set the link to be the post url:

![image](https://user-images.githubusercontent.com/45421671/106582401-3d909880-6544-11eb-9c01-f3a1c355b33b.png)

unfortunately this setting does not work. 

When the button is pressed i can see in the bottom left corner that the link is correct.

Unfortunately when i press the button in stead of following the link the page get refreshed.

Could you please help me understand what is going on here?

Second question do i need both ele custom skin AND elle custom skin pro to be active or is the regular plugin not nessecary anymore?

This is a link to a page which has lots of loops:

https://dominict3.sg-host.com/alle-activiteiten/

This is a video to show you what is happening:

https://www.loom.com/share/178cab507f5f4e98875cf9017995d771

Let me know what to do :)

Kind regards,

Dominic

**Comment by dudaster** [comment]
I think you are using make the entire posts a link and that's why you have this issues.
You need ecs and ecs pro installed.
