### ISSUE TITLE
Custom grid error when putting another post loop with custom skin inside it

### ISSUE THREAD

**Issue by RaudelWeb** [dudaster/ele-custom-skin#432]
I'm trying to create a loop that contains a custom grid that splits the first post and the latter 3 posts into two rows. Then the first post has a full-width template and the second, third and fourth post have the same template. All good here until I put the fourth post in the custom grid itself (because this post is a fixed post and needs to be there), the whole loop inherits the other custom loop from the sticky loop.

How it looks:
![image](https://user-images.githubusercontent.com/33099992/106611660-e6ed8380-6570-11eb-91f5-485db5808423.png)

How it should look:

![image](https://user-images.githubusercontent.com/33099992/106611757-05537f00-6571-11eb-94ac-e245e0746a11.png)

**Comment by dudaster** [comment]
My advice is to use 2 posts widgets because custom grid is a repetitive skin
