### ISSUE TITLE
Trim words / max words intro tekst postitem. For when Excerpt emty

### ISSUE THREAD

**Issue by BertSchipperijn** [dudaster/ele-custom-skin#435]
Hello, Nice add for Elementor, we bought the lifetime version.
We have 1 question.
We can place insite the template the Excerpt  feeld, but when that is empty, it will not auto take the intro words of the post item.
When we take post content in the loop template we can not do max words.

Inside the standard version elementor it is possible, but after select custom and this plugin, it is not. Or looks like it.
How can we manage the empty Excerpt and still have intro tekst below title?

Thanks for your time!

**Comment by dudaster** [comment]
You can use the Text Widget with Summary dynamic valei

**Comment by BertSchipperijn** [comment]
Hello, thanks for the feedback. 
Do you have a link to "Text Widget with Summary dynamic value"?
If I google on it its not yet clear for me

**Comment by BertSchipperijn** [comment]
I got it! Thank

Text widget elementor > Length value at Post Summery (dynamic content)
