### ISSUE TITLE
Ele Skin Pro: Pre-purchase Question

### ISSUE THREAD

**Issue by rrodkin** [dudaster/ele-custom-skin#44]
Hi -

I noticed that when viewing the "alternating sides" examples on mobile, that the "alternate" image (on the right side) gets positioned below the excerpt rather than above, which is a bit odd. Is there a way to control that through the editor, or would I have to apply custom CSS?

Thanks!

![eleSkin-Screenshot-mobile](https://user-images.githubusercontent.com/5130906/63216007-9f650480-c0fc-11e9-9fd4-f6903a514bbd.png)

**Comment by dudaster** [comment]
Thanks for pointing that out. I fixed it by Edit section > Advanced > Responsive > Reverse Columns (Mobile) > On

**Comment by rrodkin** [comment]
Awesome, thanks!  I think you win the "fastest fix-and-response time" award!  And on a Saturday, no less!

Cheers!
