### ISSUE TITLE
Height Issue and unable to get through it

### ISSUE THREAD

**Issue by wpelance** [dudaster/ele-custom-skin#443]
Hi,

I have tried using the suggestion of height using absolute position and bottom align but this is not working. Can you help me to overcome this issue?

![image](https://user-images.githubusercontent.com/62963503/107884026-8703bf00-6f18-11eb-9495-ffc70d808ffd.png)

URL: https://page3.wordpressfreelance.net/elixir-ultime/ still working on the site

Please let me know how to overcome this issue really need to submit it tomorrow to the client for review and I am stuck here.

THanks
Srinivas

**Comment by dudaster** [comment]
You need to set the button position to absolute and set it to the bottom. Also make sure the previews widget has enough bottom padding not to overlap with the button.

**Comment by wpelance** [comment]
Thank you Sir, you have been very helpful. I understood where I was wrong.
