### ISSUE TITLE
Display Slider Page Numbers in Loop

### ISSUE THREAD

**Issue by alexanderramsey** [dudaster/ele-custom-skin#444]
Hi there,
I would like to display the page/slide number for my custom loop template on the corresponding loop post. Is this possible using the pagination feature? I have tried to look through your past issues but can't find one similar. Please see screenshot attached with red highlight box.
Thank you,
Alexander
<img width="1331" alt="Screen Shot 2021-02-15 at 2 48 40 PM" src="https://user-images.githubusercontent.com/61996326/107991912-35514800-6f9d-11eb-8e2b-275845e69a76.png">

**Comment by dudaster** [comment]
Sorry not yet
