### ISSUE TITLE
No Excerpt with Elementor excerpt widget on loop

### ISSUE THREAD

**Issue by ThomasS4b** [dudaster/ele-custom-skin#446]
Latest version of ele-custom-skin PRO and Elementor PRO installed.

Created a loop and used in it the Elementor Excerpt widget. There is no control for the excerpt length. So, I tried (a) Advanced Excerpt plugin and (b) editing functions.php.

In both cases, the excerpt length will be correctly shown with (a) and (b) i.e. in an normal archive page BUT NOT in the loop with Ele Custom Skin. There will be the full excerpt noted in the post.

How can I solve this? 

![Unbenannt-3](https://user-images.githubusercontent.com/39570982/108554751-d5d49e80-72f4-11eb-8748-08e43820f13b.jpg)

**Comment by dudaster** [comment]
Use Post Summary Dynamic value!
