### ISSUE TITLE
the loop only show 2 item ignoring page limit is 25

### ISSUE THREAD

**Issue by nrome-n** [dudaster/ele-custom-skin#459]
I used a plugin "Elementor Custom Skin" to created a customize product archive every think is working fine but it is only showing 2 items. ignoring the page limit is 25.

note: I am using Elementor pro it would help.

**Comment by dudaster** [comment]
read this:
https://www.wpbeginner.com/beginners-guide/how-to-change-the-number-of-posts-displayed-on-your-blog-page/

If you're using woocommerce read this:

https://wpexplorer-themes.com/total/docs/woo-products-per-page/
