### ISSUE TITLE
Load More button not working - conflict with FacetWP

### ISSUE THREAD

**Issue by 8persap** [dudaster/ele-custom-skin#462]
Hi there, hope all is good. 

The load more button isn't working https://carless-adams.co.uk/news . Could be the same problem I had on https://bunked.co.uk/student-accommodation-portsmouth , where there was a conflict with FacetWP. The client has just flagged it again. It would be hugely appreciated if you could take a look, please?

Thanks

Mark.

**Comment by dudaster** [comment]
see #463
