### ISSUE TITLE
Load More button issue - Conflict with WPFacet : YOUR FIX to include in future release...

### ISSUE THREAD

**Issue by 8persap** [dudaster/ele-custom-skin#463]
Hi there. 

Here's the fix you made to address the 'Load More' button issue - Conflict with WPFacet...

-----------------

Dudaster.com sent 20 November 2020
I made it work

Dudaster.com sent 20 November 2020
but for this I had to change the class

Dudaster.com sent 20 November 2020
of elementor-pagination to elementor-pagination-ecs

Dudaster.com sent 20 November 2020
so in this way facetep would not know to mess with the loadmore button

Dudaster.com sent 20 November 2020
but you need to add some custom css

Dudaster.com sent 20 November 2020
for example to center it

Dudaster.com sent 20 November 2020
I've changed skin.php from ele-custom-skin plugin

You sent 20 November 2020
Thanks 
￼
 for making it work.

￼
Dudaster.com sent 20 November 2020
sorry for the delay

Dudaster.com sent 20 November 2020
and thank you for your patience!

You sent 20 November 2020
Are you going to code this into the plugin so it doesn’t get lost when updated?

￼
Dudaster.com sent 20 November 2020
I will see what I can do maybe I'll find a js fix

Dudaster.com sent 20 November 2020
to overwrite what facewp is doing with their js

You sent 20 November 2020
Ok. So what shall I don in the meantime if the plugin needs updating (I’m assuming you’ve made these changes directly in your plugin?)

￼
Dudaster.com sent 20 November 2020
yeah

Dudaster.com sent 20 November 2020
if not

Dudaster.com sent 20 November 2020
I'm hjere

Dudaster.com sent 20 November 2020
to remind me

You sent 20 November 2020
Ok. It would be better if I didn’t have to bother you each time the plugin needs updating.

￼
Dudaster.com sent 20 November 2020
Of course

You sent 20 November 2020
Do you think you’ll release a proper conflict fix soon?

￼
Dudaster.com sent 20 November 2020
Did you open a GitHub issue?

You sent 20 November 2020
I don’t think so?

￼
Dudaster.com sent 20 November 2020
Please do

Dudaster.com sent 20 November 2020
So I can see it

You sent 20 November 2020
Ok. Do you have please?

￼
Dudaster.com sent 20 November 2020
Go to dudaster.com
￼
dudaster – Elementor Custom Plugins
dudaster.com

￼
Dudaster.com sent 20 November 2020
And go to support page

-----------------

Thanks

Mark.

**Comment by dudaster** [comment]
You need to use the pagination from the filtering plugin because it doesn't send the new query to ECS
