### ISSUE TITLE
Elementor Custom skin plugin is not working with latest version of Wordpress

### ISSUE THREAD

**Issue by graffictetd** [dudaster/ele-custom-skin#475]
the loop not working in wordpress new update 5.7
the loop not working in home page in the inside pages it is on and off sometimes work sometimes not.

in home page there is a post list with the loop but it is showing nothing- blank.
https://smartfinance.co.il/
in the services page the post list loop is working
https://smartfinance.co.il/services/

etc.
help- pls make an update 🙂 it used to work great.

**Comment by dudaster** [comment]
The update is out
