### ISSUE TITLE
Ele Custom Skin 3.1.0 - Beta 2

### ISSUE THREAD

**Issue by dudaster** [dudaster/ele-custom-skin#476]
Ele Custom Skin 3.1.0 - Beta 2

== Changelog ==

= 3.1.0 =
* Tweak: Ajax Pagination URL change is optional
* Tweak: Experimental reinitilization of elementor JavaScript after an Ajax Request
* Fixed issues with some ACF dynamic values
* Fixed CSS issues with Ocean WP
* Added support for the latest Wordpress 
* Added support for the latest version of Elementor

Let me know if you have any problems.

[ele-custom-skin.zip](https://github.com/dudaster/ele-custom-skin/files/6348982/ele-custom-skin.zip)

**Comment by graffictetd** [comment]
for pro to? or the regular? i need to upload them? or it will show in updates panel? thanks!

**Comment by dudaster** [comment]
Regular one

**Comment by graffictetd** [comment]
i did it still the skin not showing in home page but inside pages does. :(

**Comment by graffictetd** [comment]
Look on the home page in the middle an empty frame (YouTube video suppose to be there) 
https://smartfinance.co.il/
but here you can see the video loop
https://smartfinance.co.il/reviews_categories/%d7%94%d7%9e%d7%9c%d7%a6%d7%95%d7%aa-%d7%a0%d7%aa%d7%99-%d7%9c%d7%95%d7%99%d7%98-%d7%95%d7%99%d7%93%d7%90%d7%95/

**Comment by dudaster** [comment]
Could it be a query issue?

**Comment by graffictetd** [comment]
? meaning? i know i have only with your plugin problems due to the empty frames
also i am using their an acf for url for YouTube links. 
the content i did not changes at all and all of this happened after updating WordPress before it worked great.

**Comment by dudaster** [comment]
Can you please use the chat in the dudaster.com websites? Maybe we could get at the bottom of this faster.

**Comment by graffictetd** [comment]
where? it is not clear in the website it takes me here - in the chat? in the website?

**Comment by dudaster** [comment]
This issue is related to https://github.com/dudaster/ele-custom-skin/issues/453 it will be fixed after this release

**Comment by davidofchatham** [comment]
> Tweak: Ajax Pagination URL change is optional

Excited to see this! Having trouble with returning to a directory from a sub-page and being stuck on page 2 or 3 without a way to reload the previous pages of the directory....
