### ISSUE TITLE
Error when updating to 1.1.1

### ISSUE THREAD

**Issue by sommarzan** [dudaster/ele-custom-skin#48]
I get "_Update Failed: Download failed. cURL error 18: transfer closed with outstanding read data remaining_".

Asset CleanUp: Page Speed Booster - 1.3.3.8 | By Gabriel Livan | 
Classic Editor - 1.5 | By WordPress Contributors |  
Duplicate Post - 3.2.3 | By Enrico Battocchi |  
Ele Custom Skin - 1.2.1 | By Dudaster.com |  
Ele Custom Skin Pro - 1.1.0 | By Dudaster.com |  
Elementor - 2.6.8 | By Elementor.com |  
Elementor Extras - 2.1.8 | By Namogo |  
Elementor Pro - 2.6.4
Elementor SuperCat - 2.2.4 | By Nicola Cavallazzi
Google Analytics Dashboard for WP (GADWP) - 5.3.9 | By ExactMetrics |  
Granular Controls Elementor - 1.0.5 | By Zulfikar Nore |  
H5P - 1.14.1 | By Joubel |  
Pods - Custom Content Types and Fields - 2.7.14 | By Pods Framework Team |  
Swift Performance - 2.1.1 | By SWTE |  
Ultimate Addons for Elementor - 1.16.0 | By Brainstorm Force |  
Unlimited Elements for Elementor - 1.4.5 | By Unlimited Elements |  
WP Dashboard Notes - 1.0.9

**Comment by dudaster** [comment]
Thank for reporting I’ll solve it ASAP.

**Comment by dudaster** [comment]
Solved
