### ISSUE TITLE
"LOAD MORE" error with WPML

### ISSUE THREAD

**Issue by marco68new** [dudaster/ele-custom-skin#484]
Hi, 
I developed a site in Italian and translated it with WPML into English.
Later I used English as my main language, and at that moment the "load more" loads articles in English when I look at the site in Italian.
I see the first articles in Italian, then I click on "load more" and the new ones are loaded in English.
If I put Italian back as my main language everything works correctly, what did I do wrong?
Thank you for your help.

**Comment by dudaster** [comment]
I'll investigate

**Comment by marco68new** [comment]
Okay, I think I solved, thank you, it went away when I took off maintenance mode. Can you investigate this?
