### ISSUE TITLE
Tag Archive Widget

### ISSUE THREAD

**Issue by amit-kumar-patel** [dudaster/ele-custom-skin#49]
Hi,

I have an archive page setup with the archive posts widget, and this is enabled for all archive pages. For the tag archive links, nothing shows up on the page for the widget. It works fine for the post type archive page.

Thanks,
Amit

**Comment by dudaster** [comment]
Is it working with classic/cards skin?

**Comment by amit-kumar-patel** [comment]
No, doesn't seem to work with that either

**Comment by dudaster** [comment]
ECS is only a skin, the query is done by the elementor widget. Try run Elementor in safe mode and see if it is working. If not please open a ticket here: https://github.com/elementor/elementor/issues/new/choose

**Comment by amit-kumar-patel** [comment]
Found the solution. Had to add the following to my functions.php file.

function my_cptui_add_post_types_to_archives( $query ) {
	// We do not want unintended consequences.
	if ( is_admin() || ! $query->is_main_query() ) {
		return;    
	}

	if ( is_category() || is_tag() && empty( $query->query_vars['suppress_filters'] ) ) {
		$cptui_post_types = cptui_get_post_type_slugs();

		$query->set(
			'post_type',
			array_merge(
				array( 'post' ),
				$cptui_post_types
			)
		);
	}
}
add_filter( 'pre_get_posts', 'my_cptui_add_post_types_to_archives' );
