### ISSUE TITLE
Display Mode - Same Height -Not working when published

### ISSUE THREAD

**Issue by Brett-0** [dudaster/ele-custom-skin#491]
I am using pro, Everything was working fine before the last election-custom-skin update. When I am editing in Elementor with Same Height turned on the page look correct with images the same height. As soon as I preview the page or look at it live the images are different heights. Its as if it is not recognising the pro plugin.
Regards
Brett
![Screen Shot 2021-05-04 at 10 30 48 am](https://user-images.githubusercontent.com/83618147/116948819-d8278180-acc3-11eb-82f5-cfa4e8fdf050.png)
![Screen Shot 2021-05-04 at 10 30 28 am](https://user-images.githubusercontent.com/83618147/116948834-de1d6280-acc3-11eb-8c9a-592313627216.png)

**Comment by dudaster** [comment]
Could be a CSS conflict. This could be from the theme you're using or another plugin.

Also make sure you are using only one main section in the Loop Template.

To tell you the exact issue I need the URL of the website to inspect element it.

**Comment by Brett-0** [comment]
This is the site that is playing up
https://www.denwol.com.au/residential/ <https://www.denwol.com.au/residential/>

Thanks
Brett

On 4 May 2021, at 4:35 pm, Liviu Duda ***@***.***> wrote:


Could be a CSS conflict. This could be from the theme you're using or another plugin.

Also make sure you are using only one main section in the Loop Template.

To tell you the exact issue I need the URL of the website to inspect element it.

**Comment by askwpgirl** [comment]
I am also having same height not working after update. This is not a CSS issue. It was working before update. Also posts are not pulling in correct content in loop, e.g. featured images are wrong and inserting into HTML incorrectly. Will report under separate issue. Several bugs in this update.

**Comment by Brett-0** [comment]
I managed to fix the problem by deleting both Ele Custom Skin & Ele Custom Skin Pro, then in Elementor Tools / Regenerate CSS and then Purged the cache (SiteGround Plugin).

**Comment by ursula-webeolia** [comment]
Hi,

I have also a problem with the same height option. It doesn't work at all here on this page : https://microsailing.ablop.com/ I can't say if it was working before because i just started to use the pro version of this plugin. And i took the pro version because of that option. 

I'm using elementor pro and the Hello theme.

What can i do for resolving this problem ?

Thanks for your help !

**Comment by kingfisher64** [comment]
hello, I just purchased pro for this feature (mainly) however equal heights for all elements within the custom post aren't aligning.
The columns are equal height however for example the title is 2 rows on 1 product 1 on another and looks poor :)

https://prnt.sc/200bbqc

The site is under development so is private so can't give out url.

Is there a way to make it so the elements within the custom post can all be equal height too as well as the column? Eg the titles.

Thanks
