### ISSUE TITLE
I cannot edit the template I created with ECS

### ISSUE THREAD

**Issue by waw8655** [dudaster/ele-custom-skin#498]
I have created two templates with ECS and both work and look great.

Unfortunately, when trying to edit the second of these two, I get an error message. This does not occur on the first of my two templates. It does not use any non-Elementor widgets or plugins but does use some Custom CSS.

I've posted a screenshot of the error message. In case it does not appear, the message says:

Sorry, the content area was not found in your page.
You must call 'the_content' function in the current template, in order for Elementor to work on this page.

The loop continues to work on my site. [www.financialanimal.com](url) where it is the second section from the top with a blue box overlaying an image.

Any ideas?

![ECS Error Message](https://user-images.githubusercontent.com/84284432/118405262-fdfa4200-b644-11eb-920e-760067b75872.png)

**Comment by waw8655** [comment]
I need to edit it because I did not make the title field a clickable link.

**Comment by dudaster** [comment]
Please read: https://github.com/dudaster/ele-custom-skin/issues/201

**Comment by ruchipareek5** [comment]
> Please read: #201

worked for me.
Thanks
