### ISSUE TITLE
Dynamic background image not work

### ISSUE THREAD

**Issue by erzawansyah** [dudaster/ele-custom-skin#5]
Hi
I want to use dynamic background image on section or column. But, it doesnt work. My archive post skin is just like this.

in loop editor
![screenshot from 2018-08-31 21-58-32](https://user-images.githubusercontent.com/18085790/44920019-175de180-ad69-11e8-96bd-589b5602536a.png)

in archive template editor
![screenshot from 2018-08-31 22-00-32](https://user-images.githubusercontent.com/18085790/44920134-4ecc8e00-ad69-11e8-9e93-c73a2d3adb44.png)

**Comment by dudaster** [comment]
Yeah I know, since EP 2.1 they moved the background-image from inline to header and that's why is not working anymore. I'll look for a fix, but you must find a workaround meanwhile.

**Comment by danielporto** [comment]
I have the same problem and I was about to report it.
unfortunately using an image make an ugly border to show up.
:-(

**Comment by dudaster** [comment]
I'm aware of this issue. Unfortunatly after Elementor PRO 2.1 they decided to add the background inside head tag, before was inline.

You can workaround this by using css similar to the portfolio widget.

If Elementor PRO 2.2 would not fix it I would make it possible to be able to add a background, but I wanted to keep the plugin clear and render the loop as Elementor intended, this way it would be easier to mantain.

You can help with this also: either open a issue in elementor asking to return to inline style of the elements, or contribute with ideas how we should fix this issue, the code is open source after all.

Meanwhile I would try to add a css code that accomplishes a similar efect as Portfolio widget.

**Comment by danielhoegel** [comment]
I have the same problem but I am not 100 % sure, what you mean with moving the background from inline to the header. So if you could create an issue in Elementor with the technical explanation, I would support this.

**Comment by dudaster** [comment]
before the background of the section was set inline:

<div id="section1234" style="background:url(image1.jpg)">....</div>

ECS uses the specific code and repeats it inside posts articles where you can add it in columns as you see fit:
<article><div id="section1234" style="background:url(image1.jpg)">....</div></article>
<article><div id="section1234" style="background:url(image2.jpg)">....</div></article>
<article><div id="section1234" style="background:url(image3.jpg)">....</div></article>

After an elementor update, they decided to move it in head of the html, the code looking like this:

<head>
<style>
#sectiun1234{
   background:url(image1.jpg);
}
</style>
</head>
<body>
......
<article><div id="section1234" >....</div></article>
<article><div id="section1234" >....</div></article>
<article><div id="section1234" >....</div></article>
.....
</body>

So you can see why the background is not working anymore.

Why is hard to fix this? Let's say I find a way to fix it and another update is coming rendering all the work to obsolete maybe crashing websites that has the plugin and updates elementor.

**Comment by dudaster** [comment]
I'll try to create a tutorial on how to use it in the future(haven't had much time later). but you can take a look at the porfolio css from elementor to get inspiration from.

**Comment by dudaster** [comment]
Ok guys. I could of sweare that this featured would be in EP 2.2. But it seems I was wrong. I don't think this year another big release of EP would see the light of day.

I will try as elegantly as I can to add support dynamic background.

Wish me luck!

**Comment by danielporto** [comment]
any update on this front or a quick workaround (image widget + css)??
looking forward.

**Comment by dudaster** [comment]
I managed only to make it work with the section element because there you can add attributes directly on the **_wrapper** on widgets and columns I needed something like **_inner_wrapper** filter to be available. 
For more details you can see the request #6287 I've made, but without success.  There is a workaround though, using javascript to grab attributes from **_wrapper** and add it to an **_inner_wrapper** .

Anyway I hope I'll find more time to make the javascript to make it work.

**Comment by danielporto** [comment]
When you realize that the possibilities and the relevance that this plugin has to elementor, at the same time the ignorance, lack of attention given to it by elementor team... the only possible explanation accepted would be if they are with a MUCH better solution ready to release.

Any other would be stupidity. 
Thanks again @dudaster .

**Comment by SirWellington** [comment]
@dudaster Did you ever figure out a workaround for this?

**Comment by WeAreHaus** [comment]
> I managed only to make it work with the section element because there you can add attributes directly on the **_wrapper**, on widgets and columns I needed something like **_inner_wrapper** filter to be available.
> For more details you can see the request [ #6287](https://github.com/pojome/elementor/issues/6287) I've made, but without success. There is a workaround though, using javascript to grab attributes from **_wrapper** and add it to an **_inner_wrapper** .
> 
> Anyway I hope I'll find more time to make the javascript to make it work.

@dudaster Should the current version of ele-custom-skin work with dynamic background images on sections?

Im trying to get it work, but it wont load any images... Not on columns and not on sections...

//Tim

**Comment by timsamuelsson** [comment]
@dudaster Should the current version of ele-custom-skin work with dynamic background images on sections?

Im trying to get it work, but it wont load any images... Not on columns and not on sections...

//Tim

**Comment by clement-menard** [comment]
Hi everyone !
On my side, with all the plugins up to date, background images are displayed. But I still have a problem ... All posts show the same image (the one of the last post). I use another dynamic background image in hover, and I have the same problem.
While all the other dynamic elements (texts, URLs) are good ...

An idea of the problem ?

**Comment by JeroenDerks** [comment]
Love the plugin, but facing the same problem where all the featured images are the same image.

**Comment by dudaster** [comment]
If you have some css knowledge take a look at this example: http://jsfiddle.net/wvzqpjaa/

If you don't, try to use Call to Action Widget.

**Comment by JeroenDerks** [comment]
One workaround that works for me:
1. Set the background container's ID to the Featured Image's File path
2. Set a class name for your container 
3. write a small script that sets the background image to the containers' id
4. run this script in the footer or after your Elementor Post widget

`<script>
    var containers = document.querySelectorAll(".myContainers");
    for(var i = 0; i < containers.length; i++){
        var imgUrl = containers[i].id;
        containers[i].style.backgroundImage = "url(" + imgUrl+ ")";
    }
    
</script>`

**Comment by dudaster** [comment]
Nice workaround!
I have a version working with background images for sections and columns but it's not behaving with scrolling effects :(. I'll roll it out this week.

**Comment by dudaster** [comment]
Now is out. Update the plugin!

**Comment by clement-menard** [comment]
Hi !
I update the latest version of Ele Plugin (1.1.2), but all posts show the same image again...

I can't use workaround by @JeroenDerks, because i need to use another image in :hover.

I don't understand...

**Comment by dudaster** [comment]
I'm sorry to hear it is not working for you. if you'll give me the website maybe I can take a look.

Make sure you have the latest elementor and elementor pro and it is from official places.

**Comment by clement-menard** [comment]
Thanks @dudaster !

I send you an email with access 😀

**Comment by dudaster** [comment]
I think the problem was because you had 2 loops with the same name

**Comment by clement-menard** [comment]
I did not notice... I did several tests, so I could have duplicated the loop "Display Welcomers Posts". I see only one now, have you removed the duplicate loop? Unfortunately, that did not solve the problem on my side...

**Comment by dudaster** [comment]
where can I change the 2nd featured image for each article?

**Comment by clement-menard** [comment]
It's an ACF Field. You may need to enable it in "Screen options" when editing post.

**Comment by dudaster** [comment]
Ok I think I know what the problem is:

I'm adding the css to the content hook where as archive doesn't have a content.

Let me think what hook can I use to put the css in, and it would solve the problem.

**Comment by dudaster** [comment]
This would be fixed in the next version. If you want a workaround try using a Single Page instead of an archive page for now.

**Comment by clement-menard** [comment]
Thank you very much for your feedback!
Okay, I'll try to create a single page.
