### ISSUE TITLE
Previously used ECS Pro. Need to install again but HOW

### ISSUE THREAD

**Issue by hoohum** [dudaster/ele-custom-skin#500]
I have a licence for Pro but I cannot find it. I have installed the free plug in but all attempts to click to 'go pro' end up with a page to buy it. Nothing to log into to view previous purchases, licenses, downloads etc. I must be missing something simple here because this should be super easy. Can you help please.

**Comment by dudaster** [comment]
Search for the email from gumroad. If you don’t find it please use the contact from the website to resend it to you.

**Comment by hoohum** [comment]
Fantastic. That was quick and gumroad was the missing link. All done. 

Many thanks,
Barry.



On 21 May 2021, at 17:25, Liviu Duda ***@***.***> wrote:


Search for the email from gumroad. If you don’t find it please use the contact from the website to resend it to you.
