### ISSUE TITLE
Same height option not working

### ISSUE THREAD

**Issue by ursula-webeolia** [dudaster/ele-custom-skin#503]
Hi,
I have a problem with the same height option. It doesn't work at all here on this page : https://microsailing.ablop.com/ I can't say if it was working before because i just started to use the pro version of this plugin. And i took the pro version because of that option.

I'm using elementor pro and the Hello theme.

What can i do for resolving this problem ?

Thanks for your help !

**Comment by dudaster** [comment]
Can you tell me where should I look on that page?
