### ISSUE TITLE
Is it possible to change the skin of WooCommerce Upsells?

### ISSUE THREAD

**Issue by ghost** [dudaster/ele-custom-skin#505]
Hi, me again!

I've been searching for hours to see if this is possible.

Elementor has an upsells widget enabled when WooCommerce is installed. However, there is no option to choose a skin when using this widget.

Do you know a way I can have a list of posts which use a custom skin created with this plugin and pull through WooCommerce Upsells / Cross-sells?

Many Thanks :)

**Comment by dudaster** [comment]
Currently not. But you can try make a custom query: https://developers.elementor.com/custom-query-filter/

**Comment by Dudeney95** [comment]
@dudaster I have found a solution! I hope this helps someone else like me!

Stick this in functions.php:

`add_action( 'elementor/query/upsell_products', function( $query ) {
	
	// Get WooCommerce Global
	global $woocommerce;

	$upsells = get_post_meta( get_the_ID(), '_upsell_ids',true);

    if(empty($upsells)){
        return;
    }

	$query->set( 'post__in', $upsells );

});`

Then, in the posts widget, select your custom skin and make the source Manual Selection. The Query ID must be upsell_products.
A solution for cross sells can be found here: https://github.com/elementor/elementor/issues/8071#issuecomment-826659463

**Comment by ghost** [comment]
> Currently not. But you can try make a custom query: https://developers.elementor.com/custom-query-filter/

I have resolved the issue and created a custom query filter, I hope this helps someone else!:
`add_action( 'elementor/query/upsell_products', function( $query ) {
                // Get WooCommerce Global
                global $woocommerce;
                $upsells = get_post_meta( get_the_ID(), '_upsell_ids',true);
    if(empty($upsells)){
        return;
    }
                $query->set( 'post__in', $upsells );
});`
In the post widget, you must set the Source as Manual Selection and the Query ID as upsell_products.
