### ISSUE TITLE
No option to set a padding between loop items in Elmentor's Archive Posts widget

### ISSUE THREAD

**Issue by formulaclick** [dudaster/ele-custom-skin#51]
Hi

I'm Pro user.

If I use "Archive Posts" widget and select "Classic" skin, then in "Style" tab I can set a vertical and horizontal padding, as you can see here:

![Captura](https://user-images.githubusercontent.com/2376672/64011282-abe55600-cb1b-11e9-8166-2e78bb2c8ad2.PNG)

But if select "Custom" skin and select one created by me with your plugin, then in "Style" tab there are no options to set paddings, they are missing and I can't set the padding:

![Captura2](https://user-images.githubusercontent.com/2376672/64011691-81e06380-cb1c-11e9-979c-0350e292c802.PNG)

I know I could set a margin in each loop item, but it's not the same, I want a real grid padding.

If I use "Posts" widget instead of "Archive Posts" option is not missing, but I need to use "Archive Posts" widget.

Is this a bug? How can I solve it?

Thanks

**Comment by dudaster** [comment]
Yes it is a bug that I’m working on it. A workaround is to use Posts Widget with “current query” set.

**Comment by dudaster** [comment]
I issued an update that should solve this problem. Let me know if it is ok!

**Comment by formulaclick** [comment]
> I issued an update that should solve this problem. Let me know if it is ok!

Seems to work fine. Thanks!
