### ISSUE TITLE
ACF color picker issue

### ISSUE THREAD

**Issue by broutelee** [dudaster/ele-custom-skin#514]
Hi !

In my loop, I use a button and an hover effect background with an ACF color picker field. Both don't work in my archive page template .
Any solutions to make it works  ?

Thanks for your help,

Regards,

**Comment by dudaster** [comment]
This sounds like a JS issue. Can you copy paste the JS error here? You can find it in console when you inspect element.

**Comment by broutelee** [comment]
Thanks for your Help !
I found a solution at last. It was an issue with archive template display condition in my elementor theme builder and the template section I used for.
Now it works.

regards,
