### ISSUE TITLE
Ability to specify number of posts shown.

### ISSUE THREAD

**Issue by amit-kumar-patel** [dudaster/ele-custom-skin#52]
Hi,

I remember there used to be an option to set how many posts show for a widget but I can no longer see this. Is this a pro only feature or can I still do this?

Thanks,
Amit

**Comment by dudaster** [comment]
Scroll down it should be there. The pro version is to add things not to move things there. 

The free version will also get new cool stuff also.

**Comment by amit-kumar-patel** [comment]
![elementor-post-amount](https://user-images.githubusercontent.com/31771517/64043058-43b66480-cb5b-11e9-80c5-e18c5e357cd3.gif)

Attached a gif of what I can see. Am I looking in the wrong place?

**Comment by michaelearley1** [comment]
I agree with original poster. 
It is no longer an option to specify how many posts show per page.

**Comment by dudaster** [comment]
it is definitely a bug. I'm working on it.

**Comment by dudaster** [comment]
DO you guys all have Elementor Version 2.7.0-beta1 ?

**Comment by michaelearley1** [comment]
This bug is showing up for me in a site running Elementor version 2.6.8 and Elementor Pro version 2.6.4

**Comment by dudaster** [comment]
Ok thanks!

**Comment by dudaster** [comment]
Found the issue. I'll release an update ASAP.

**Comment by dudaster** [comment]
The update is out. Let me know if it is ok now!

**Comment by michaelearley1** [comment]
I just updated and everything seems to be working smoothly now. The Posts per page option is now available again. Thanks much for the speedy fix! It is a great plugin

**Comment by dudaster** [comment]
Thank you guys for pointing this out!
