### ISSUE TITLE
Keeping Images The Same Size

### ISSUE THREAD

**Issue by philthebass** [dudaster/ele-custom-skin#529]
Hi,

Is there a way we can keep the image dimensions the same in a grid?

User's will be uploading images of different sizes and aspect ratio so we want to keep the image display the same.

![image](https://user-images.githubusercontent.com/13836637/124781451-51995580-df3b-11eb-9306-8bb499d17363.png)

We can do this with the standard Elementor grid by setting the image ratio etc.

![image](https://user-images.githubusercontent.com/13836637/124782036-ccfb0700-df3b-11eb-9002-a158f404efc1.png)

How do we achieve this with Ele Skin Pro?

Thanks

**Comment by dudaster** [comment]
Use custom size of the image in image widget

**Comment by philthebass** [comment]
Thanks!
