### ISSUE TITLE
Posts per page not working - Archive Posts Widget

### ISSUE THREAD

**Issue by amit-kumar-patel** [dudaster/ele-custom-skin#53]
Hi,

Thanks for quick fix on the previous issue, I can now see the posts per page option but changing the value doesn't seem to affect anything. This is only for the archive posts widget, the regular posts widget works fine.

Thanks,
Amit

**Comment by dudaster** [comment]
You are right... from the Archive Posts I need to remove post per page. The query cannot be set in Archive Posts. The same is for the other skins too.

**Comment by dudaster** [comment]
To change it there you need to go to Wordpress dashboard settings reading and set it there

**Comment by amit-kumar-patel** [comment]
ah, thanks for the info 👍🏽

**Comment by dudaster** [comment]
And let me explain why:

Archive Posts Widget is basically Posts Wigets with "Current query" selected. That means the all the values is getting form $wp_query global var which contains also the pagination info so it would not override it in any way. 

Also if you use Posts Widget in "Current query" mode it will behave the same so be carefull.

If you want to change the pagination, go to  Settings > Reading > Blog pages show at most and enter the number you want there.

**Comment by dudaster** [comment]
I removed post per page on Archive Post Widget.
