### ISSUE TITLE
Grid Issues

### ISSUE THREAD

**Issue by philthebass** [dudaster/ele-custom-skin#533]
Hi,

I have set up my custom grid and created the alternating background colours.

That works fine for the first rows, but then when loading more, the background is restricted

https://www.dropbox.com/s/cwhbknnauew7rk6/Screenshot%202021-07-09%20at%2009.53.18.png?dl=0T

Also, I get an empty grid row at the bottom

https://www.dropbox.com/s/l0g8gda60z6tg3j/Screenshot%202021-07-09%20at%2010.08.43.png?dl=0

How can I fix those?

Thanks

Phil

**Comment by dudaster** [comment]
Try using 0 padding. The extra row is for the html to close properly.

**Comment by philthebass** [comment]
Padding on the section? If so, it is set to 0 but still have both issues

**Comment by dudaster** [comment]
the issue was the margin added to the Post Item Widget
