### ISSUE TITLE
Sorry, the content area was not found in your page.

### ISSUE THREAD

**Issue by lyledg** [dudaster/ele-custom-skin#539]
HI there

I have a brand new WP and basic install, with only Elementor and Ele Custom Skin installed, can cannot create my first loop. No other pages have been created.

When I try and create the fist loop, I get the error above.. are there any compatibility issues with Elementor 3.3.1?

**Comment by dudaster** [comment]
Doublicate #535

**Comment by lyledg** [comment]
Sorry it is not a duplicate, I have no other Elementor plugins that can affect this! How can you close this without investigating?

**Comment by lyledg** [comment]
<img width="960" alt="loop" src="https://user-images.githubusercontent.com/60354807/126482371-8c366e60-b659-4a91-8f35-6ca30ba4caa5.png">

**Comment by dudaster** [comment]
This error or is not caused by other plugins. It got mixed with other issue.

One question: can you create a single template?
