### ISSUE TITLE
Sorry, the content area was not found in your page.

### ISSUE THREAD

**Issue by lyledg** [dudaster/ele-custom-skin#540]
Please do not close this without investigating the issue

I have a CLEAN WP build with Only Elementor and Pro installed (No other Elementor enhancement Plugins )

See the attached screenshot, everytime I try and edit loop for the first time, I get the error above

I have read your other posts (Happy Addons etc) being the cause, in this case it is a vanilla build and still seeing issues
<img width="960" alt="loop" src="https://user-images.githubusercontent.com/60354807/126482640-72ecd0d8-3582-4f3c-8dd6-2db8f7a846c0.png">

**Comment by lyledg** [comment]
Even If I change the instances to 'Posts' I still see the same error

**Comment by dudaster** [comment]
It is weird that I see only one template and it says you have 2 of them.

**Comment by lyledg** [comment]
<img width="794" alt="other" src="https://user-images.githubusercontent.com/60354807/126483054-23f808bc-111c-494f-bf56-d0d39d961ece.png">

**Comment by lyledg** [comment]
The other is just the default kit. I have a video too of the setup

https://user-images.githubusercontent.com/60354807/126483115-db41430a-3016-4310-aab0-d62a7c730333.mp4

**Comment by dudaster** [comment]
Try this two things: 

create a single template and another loop template.

let me know if it works!

**Comment by lyledg** [comment]
Same result

**Comment by lyledg** [comment]
<img width="775" alt="loop1" src="https://user-images.githubusercontent.com/60354807/126483636-165122b5-38a0-4967-a680-c952814c9571.png">

**Comment by lyledg** [comment]
I'm going to blow the box away and start again....see if I am doing anything weird.

**Comment by dudaster** [comment]
And set the singular template to all posts instead of all singular. Still the same?

**Comment by dudaster** [comment]
Use the chat on dudaster.com

**Comment by lyledg** [comment]
Issue resolved, created a Single Post type first, then the Loop and it worked then.
<img width="918" alt="loop2" src="https://user-images.githubusercontent.com/60354807/126484649-5fb7fb1e-916c-4e9f-8390-6e5d8c05c414.png">

**Comment by dudaster** [comment]
Great! You can close it if you want.
