### ISSUE TITLE
Upgrade to lifetime subscription

### ISSUE THREAD

**Issue by ironwiller** [dudaster/ele-custom-skin#543]
Hi. Thank you for your plugun. I've purchased last week your annual subscription and i would like to upgrade to lifetime. Whats the process in order to do so? in gubroad there is no option upgrade. Thanks.

**Comment by dudaster** [comment]
Yes it is possible. Go to dudaster.com and use a contact method (form or chat) to the request along with your purchase email.

**Comment by ironwiller** [comment]
I did, but no one has responded to me. its been 4-5 days. 
I've send again to messenger chat. thanks.
