### ISSUE TITLE
Wordpress White Page

### ISSUE THREAD

**Issue by rodrigoardilha** [dudaster/ele-custom-skin#548]
When I enable the Ele Custom Skin, the wordpress only returns a blank page.
The moment I disable the plugin, the site works again, but obviously without the plugin elements. 

What can I do to solve this problem?
I already tried to reinstall Ele Custom Skin + Ele Custom Skin Pro

**Comment by dudaster** [comment]
Go to Elementor > System Info > Error Log and get the last php errors

**Comment by rodrigoardilha** [comment]
I got support via Facebook Messenger. Someone checked my website and realize that it was some code error. Inconsistency between PHP 8 and the plugin code. They fixed and released the update already.

Thank you.
