### ISSUE TITLE
Critical Error with Elementor Pro

### ISSUE THREAD

**Issue by hoffmanash** [dudaster/ele-custom-skin#549]
When Ele Custom Skin is enabled, I get a critical error when trying to view posts:
There has been a critical error on this website.

Learn more about debugging in WordPress.

I have the pro version of Ele Custom Skin.
The website is https://www.stmartinschamberchoir.org/
An example of a post is https://www.stmartinschamberchoir.org/american-renaissance
If it loads correctly and you see the page, it means I have disabled ele custom skin. Whether or not Ele Custom Skin pro is enabled or not doesn't seem to make a difference.

**Comment by hoffmanash** [comment]
I am disappointed that paying for a pro account does not lead to quick, personalized support.

**Comment by dudaster** [comment]
Go to elementor > system info > error log and check the error log from php. And paste here the last error.

**Comment by hoffmanash** [comment]
Why is this closed? I did not close this issue

**Comment by hoffmanash** [comment]
PHP: 2020-10-02 11:03:19 [error X 1][/services/webpages/s/t/stmartinschamberchoir.org/public/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::259] Uncaught Error: Call to a member function update_meta() on null in /services/webpages/s/t/stmartinschamberchoir.org/public/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:259
Stack trace:
#0 /services/webpages/s/t/stmartinschamberchoir.org/public/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(180): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(4846, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /services/webpages/s/t/stmartinschamberchoir.org/public/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /services/webpages/s/t/stmartinschamberchoir.org/public/wp-includes/class-wp-hook.php(287): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /services/webpages/s/t/stmartinschamberchoir.org/public/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array)
#5 /services/webpages/s/t/stmartinschamberchoir.org/public/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#6 /services/webpages/s/t/stmartinschamberchoir.org/public/wp-admin/admin-ajax.php(175): do_action('wp_ajax_element...')
#7 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-10-02 11:03:51 [notice X 45][/services/webpages/s/t/stmartinschamberchoir.org/public/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-10-02 11:08:52 [error X 3][/services/webpages/s/t/stmartinschamberchoir.org/public/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::259] Uncaught Error: Call to a member function update_meta() on boolean in /services/webpages/s/t/stmartinschamberchoir.org/public/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:259
Stack trace:
#0 /services/webpages/s/t/stmartinschamberchoir.org/public/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(180): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(NULL, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /services/webpages/s/t/stmartinschamberchoir.org/public/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /services/webpages/s/t/stmartinschamberchoir.org/public/wp-includes/class-wp-hook.php(287): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /services/webpages/s/t/stmartinschamberchoir.org/public/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array)
#5 /services/webpages/s/t/stmartinschamberchoir.org/public/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#6 /services/webpages/s/t/stmartinschamberchoir.org/public/wp-admin/admin-ajax.php(175): do_action('wp_ajax_element...')
#7 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-12-15 15:58:15 [error X 3][/services/webpages/s/t/stmartinschamberchoir.org/public/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::281] Uncaught Error: Call to a member function update_meta() on boolean in /services/webpages/s/t/stmartinschamberchoir.org/public/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:281
Stack trace:
#0 /services/webpages/s/t/stmartinschamberchoir.org/public/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(162): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(NULL, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /services/webpages/s/t/stmartinschamberchoir.org/public/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /services/webpages/s/t/stmartinschamberchoir.org/public/wp-includes/class-wp-hook.php(287): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /services/webpages/s/t/stmartinschamberchoir.org/public/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array)
#5 /services/webpages/s/t/stmartinschamberchoir.org/public/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#6 /services/webpages/s/t/stmartinschamberchoir.org/public/wp-admin/admin-ajax.php(175): do_action('wp_ajax_element...')
#7 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-12-18 16:00:05 [error X 7][/services/webpages/s/t/stmartinschamberchoir.org/public/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::281] Uncaught Error: Call to a member function update_meta() on boolean in /services/webpages/s/t/stmartinschamberchoir.org/public/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:281
Stack trace:
#0 /services/webpages/s/t/stmartinschamberchoir.org/public/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(162): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(NULL, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /services/webpages/s/t/stmartinschamberchoir.org/public/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /services/webpages/s/t/stmartinschamberchoir.org/public/wp-includes/class-wp-hook.php(287): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /services/webpages/s/t/stmartinschamberchoir.org/public/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array)
#5 /services/webpages/s/t/stmartinschamberchoir.org/public/wp-includes/plugin.php(484): WP_Hook->do_action(Array)
#6 /services/webpages/s/t/stmartinschamberchoir.org/public/wp-admin/admin-ajax.php(184): do_action('wp_ajax_element...')
#7 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-12-18 17:26:41 [error X 1][/services/webpages/s/t/stmartinschamberchoir.org/public/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::281] Uncaught Error: Call to a member function update_meta() on null in /services/webpages/s/t/stmartinschamberchoir.org/public/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:281
Stack trace:
#0 /services/webpages/s/t/stmartinschamberchoir.org/public/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(162): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(5367, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /services/webpages/s/t/stmartinschamberchoir.org/public/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /services/webpages/s/t/stmartinschamberchoir.org/public/wp-includes/class-wp-hook.php(287): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /services/webpages/s/t/stmartinschamberchoir.org/public/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array)
#5 /services/webpages/s/t/stmartinschamberchoir.org/public/wp-includes/plugin.php(484): WP_Hook->do_action(Array)
#6 /services/webpages/s/t/stmartinschamberchoir.org/public/wp-admin/admin-ajax.php(184): do_action('wp_ajax_element...')
#7 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-12-18 19:07:03 [notice X 2][/services/webpages/s/t/stmartinschamberchoir.org/public/wp-content/plugins/elementor-pro/modules/posts/skins/skin-content-base.php::248] Trying to get property of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-02-20 16:03:01 [notice X 1][/www/stmartinschamberchoirorg_702/public/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::162] Undefined index: editor_post_id [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-07-28 16:11:51 [error X 7][/www/stmartinschamberchoirorg_702/public/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::281] Uncaught Error: Call to a member function update_meta() on bool in /www/stmartinschamberchoirorg_702/public/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:281
Stack trace:
#0 /www/stmartinschamberchoirorg_702/public/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(162): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(NULL, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /www/stmartinschamberchoirorg_702/public/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /www/stmartinschamberchoirorg_702/public/wp-includes/class-wp-hook.php(287): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /www/stmartinschamberchoirorg_702/public/wp-includes/class-wp [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-07-29 10:14:14 [error X 2][/www/stmartinschamberchoirorg_702/public/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::281] Uncaught Error: Call to a member function update_meta() on null in /www/stmartinschamberchoirorg_702/public/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:281
Stack trace:
#0 /www/stmartinschamberchoirorg_702/public/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(162): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions(4607, Array)
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions(Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#2 /www/stmartinschamberchoirorg_702/public/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func(Array, Array, Object(Elementor\Core\Common\Modules\Ajax\Module))
#3 /www/stmartinschamberchoirorg_702/public/wp-includes/class-wp-hook.php(287): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request('')
#4 /www/stmartinschamberchoirorg_702/public/wp-includes/class-wp [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-07-29 10:51:57 [warning X 1][/www/stmartinschamberchoirorg_702/public/wp-content/plugins/elementor/modules/safe-mode/module.php::124] rmdir(/www/stmartinschamberchoirorg_702/public/wp-content/mu-plugins): Directory not empty [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2021-07-30 15:55:06 [notice X 101][/www/stmartinschamberchoirorg_702/public/wp-content/plugins/elementor-pro/modules/dynamic-tags/acf/tags/acf-text.php::33] Undefined offset: 1 [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

**Comment by dudaster** [comment]
It is weird because I don’t see any error from today. Is it possible to turn debug mode on so I can see the error on that page?

**Comment by hoffmanash** [comment]
Okay, it's on now
Take a look:

Recoverable fatal error: Object of class WP_Post could not be converted to string in /www/stmartinschamberchoirorg_702/public/wp-includes/kses.php on line 1644

**Comment by dudaster** [comment]
I think this is the same issue https://wordpress.org/support/topic/critical-fatal-error-on-loop-templates-after-trash-recover/#post-14719775

**Comment by hoffmanash** [comment]
I don't understand, though... I did not select a taxonomy that no longer exists. I have already chosen one that exists.

**Comment by hoffmanash** [comment]
I don't believe it is the same error, because I can no longer view posts directly from the post list, either. It doesn't have anything to do with their dynamic links. If I disable ele custom skin, however, I can see them again.

**Comment by hoffmanash** [comment]
Okay, I completely rebuilt the post template, and it seems to be loading now. Thanks for your help.

**Comment by hoffmanash** [comment]
Nope, still happening.

**Comment by hoffmanash** [comment]
Okay, I believe I resolved this. For anyone having a similar issue, the problem was that I had multiple templates applied to the same post category. I deleted the old templates and things have been much smoother.
