### ISSUE TITLE
Deleted loop templates still shown in the template dropdown

### ISSUE THREAD

**Issue by jess8bit** [dudaster/ele-custom-skin#55]
With ECS Pro, I have created 3 Loop templates in Elementor Pro.
Then I trashed 2 of them (Wordpress Bin).

In the Elementor Posts Widget, after selecting Custom in "Skin" Dropdown, when I want to select a Loop template from the "Select a default template" dropdown, 
I can still see the 2 I have removed.

Please see the image:
![image](https://user-images.githubusercontent.com/31023191/64132284-97a39200-cd83-11e9-8ecd-a647416a6553.png)

Could this be improved to hide templates that are in the Bin?

**Comment by dudaster** [comment]
Yes. It's already in the works.

Thanks for pointing this out!

**Comment by dudaster** [comment]
Issue fixed. Update ECS!
