### ISSUE TITLE
Lost titles in loop

### ISSUE THREAD

**Issue by Lysannew** [dudaster/ele-custom-skin#552]
Hi!

For our site, we have set up a loop for the blog. From one specific blog, all the H1 titles disappear. When the loop was set up, the titles were there. Does anyone know how this can be solved?

![image](https://user-images.githubusercontent.com/88382384/128013291-11541e58-75bf-448f-b4ec-60a148b1b7b9.png)

Thanks!

**Comment by dudaster** [comment]
make sure you didn't selected the hide title of the respective posts.
![Screenshot 2021-08-06 153701](https://user-images.githubusercontent.com/8319178/128511473-45a34a2b-9454-4ada-8d52-80b19b7286a0.png)

**Comment by Lysannew** [comment]
Thanks, it worked!
