### ISSUE TITLE
Column drop shadow not displaying

### ISSUE THREAD

**Issue by the-stew** [dudaster/ele-custom-skin#56]
Any drop shadow styles added to columns are no longer displaying in the loops. I've tested this with a few different installs with the same result.

Reverting back to 1.2.1 fixes the issue.

**Comment by dudaster** [comment]
I'll take a look.

**Comment by dudaster** [comment]
Issue fixed. Update ECS!

**Comment by the-stew** [comment]
You work quick! Thanks mate :-)
