### ISSUE TITLE
Margin top on button

### ISSUE THREAD

**Issue by sadeghmirkis** [dudaster/ele-custom-skin#563]
Hi,

after the recent elementor update elementor custom skin seems to be adding extra margin on top of "read more" button.

I have contacted Elementor support and they said:

> Thank you for reporting this to us.
> I've managed to reproduce the issue on both your staging and my testing website.
> It seems that the problem is coming from Elementor Custom skin. The plugin is adding padding to the button that acts as "Read more".
> 
> We have added a "Load more" function in the Elementor PRO 3.4, and it seems it's messing up with their code.
> Unfortunately, we don't have access to their code base, so I would advise you to write to them and ask if they can fix this from their end.
> All the other buttons seem to be loading just fine, except this one.

Thought I let you know, and hopfully you will fix this :)

**Comment by dudaster** [comment]
Thanks! I will take a look.

**Comment by dudaster** [comment]
To quickly fix the issue use this CSS:

```
.elementor-widget-posts .ecs-posts .elementor-button-wrapper {
    margin-top: 0;
}
```

**Comment by dudaster** [comment]
The update is up.
