### ISSUE TITLE
I want to sort loop posts by ACF Date picker field in ASC order

### ISSUE THREAD

**Issue by SAJID12345678** [dudaster/ele-custom-skin#565]
I have a custom post type named "admission" in which posts contain a custom date field (date picker by ACF Plugin), I have created a custom posts loop with Elementor pro & Ele Skin. I want to display posts in the loop (created with ele skin) in ASCENDING order of the dates available in the "ACF date picker" field but I can not do so. I am bound to display posts in loop by ASC/DEC order by the post created date. Help me in this regard so that I can display my events in loop which are nearly going to happen & so on

**Comment by muazzami** [comment]
@SAJID12345678  It is not clear if you are using Posts Widget or Archive Posts Widget. I have achieved the same by following methods.

1. If using Posts Widget
Go to Query and assign a query ID ( make sure its unique )
![image](https://user-images.githubusercontent.com/3307602/132122509-69d3a9f5-62a8-4a62-8267-aef91179ddda.png)

Then you need to add an action either in your theme's functions.php or a custom plugin

```php
add_action( 'elementor/query/my_order_query', function( $query ) {
   //set order by meta value num 
   $query->set('orderby','meta_value_num');
   //set meta key to your ACF date field start_date is just example
    $query->set('meta_key', 'start_date');
    //Set the order ASC or DESC
    $query->set('order', 'ASC');
} );
```

That is it, it will sort the query by your ACF custom field in ascending order. 
Please note my_order_query is the same ID which is given to the widget.

2. If using Archive Posts Widget
In this case, you do not have option to assign custom query id however we can use `pre_get_posts` hook.

```php
add_action( 'pre_get_posts', function($query) {
//make sure it applies to your custom post type and its main query only
  if (is_post_type_archive( 'admission' ) && $query->is_main_query()) {
  //rest is same as last function

   //set order by meta value num 
   $query->set('orderby','meta_value_num');
   //set meta key to your ACF date field start_date is just example
    $query->set('meta_key', 'start_date');
    //Set the order ASC or DESC
    $query->set('order', 'ASC');

  }

} );
```

Note: I am not linked to dudaster, just trying to help.

**Comment by SAJID12345678** [comment]
> @SAJID12345678 It is not clear if you are using Posts Widget or Archive Posts Widget. I have achieved the same by following methods.
> 
> 1. If using Posts Widget
>    Go to Query and assign a query ID ( make sure its unique )
>    ![image](https://user-images.githubusercontent.com/3307602/132122509-69d3a9f5-62a8-4a62-8267-aef91179ddda.png)
> 
> Then you need to add an action either in your theme's functions.php or a custom plugin
> 
> ```
> add_action( 'elementor/query/my_order_query', function( $query ) {
>    //set order by meta value num 
>    $query->set('orderby','meta_value_num');
>    //set meta key to your ACF date field start_date is just example
>     $query->set('meta_key', 'start_date');
>     //Set the order ASC or DESC
>     $query->set('order', 'ASC');
> } );
> ```
> 
> That is it, it will sort the query by your ACF custom field in ascending order.
> Please note my_order_query is the same ID which is given to the widget.
> 
> 1. If using Archive Posts Widget
>    In this case, you do not have option to assign custom query id however we can use `pre_get_posts` hook.
> 
> ```
> add_action( 'pre_get_posts', function($query) {
> //make sure it applies to your custom post type and its main query only
>   if (is_post_type_archive( 'admission' ) && $query->is_main_query()) {
>   //rest is same as last function
> 
>    //set order by meta value num 
>    $query->set('orderby','meta_value_num');
>    //set meta key to your ACF date field start_date is just example
>     $query->set('meta_key', 'start_date');
>     //Set the order ASC or DESC
>     $query->set('order', 'ASC');
> 
>   }
> 
> } );
> ```
> 
> Note: I am not linked to dudaster, just trying to help.

Dear thank you but I'm unable to understand. I will like you to contact me directly via any social media platform like Facebook/WhatsApp. Here's my WhatsApp number please drop me a message 
+923017059018
I am a Youtuber with 32K+ SUBSCRIBERs & 300K Monthly visitors. I will like to help you as well.
Thanks

**Comment by SAJID12345678** [comment]
> @SAJID12345678 It is not clear if you are using Posts Widget or Archive Posts Widget. I have achieved the same by following methods.
> 
> 1. If using Posts Widget
>    Go to Query and assign a query ID ( make sure its unique )
>    ![image](https://user-images.githubusercontent.com/3307602/132122509-69d3a9f5-62a8-4a62-8267-aef91179ddda.png)
> 
> Then you need to add an action either in your theme's functions.php or a custom plugin
> 
> ```
> add_action( 'elementor/query/my_order_query', function( $query ) {
>    //set order by meta value num 
>    $query->set('orderby','meta_value_num');
>    //set meta key to your ACF date field start_date is just example
>     $query->set('meta_key', 'start_date');
>     //Set the order ASC or DESC
>     $query->set('order', 'ASC');
> } );
> ```
> 
> That is it, it will sort the query by your ACF custom field in ascending order.
> Please note my_order_query is the same ID which is given to the widget.
> 
> 1. If using Archive Posts Widget
>    In this case, you do not have option to assign custom query id however we can use `pre_get_posts` hook.
> 
> ```
> add_action( 'pre_get_posts', function($query) {
> //make sure it applies to your custom post type and its main query only
>   if (is_post_type_archive( 'admission' ) && $query->is_main_query()) {
>   //rest is same as last function
> 
>    //set order by meta value num 
>    $query->set('orderby','meta_value_num');
>    //set meta key to your ACF date field start_date is just example
>     $query->set('meta_key', 'start_date');
>     //Set the order ASC or DESC
>     $query->set('order', 'ASC');
> 
>   }
> 
> } );
> ```
> 
> Note: I am not linked to dudaster, just trying to help.

Thank You, Dear.
It really worked for me but I don't want to display events with past dates. I want that only upcoming events can be displayed there. Please change the code accordingly so that I can get desired results. I really appreciate your help. People like you are rare.
