### ISSUE TITLE
Custom Grid: _content_template is Deprecated in Elementor Since Version 2.9.0

### ISSUE THREAD

**Issue by kwsim539** [dudaster/ele-custom-skin#567]
When using your Custom Grid and drag in my Loop Item it is returning a Deprecation error, (Screenshot: [https://www.dropbox.com/s/z1ttlvg7kyvf3fw/deprecated.jpg?dl=0](url) ). Please update your code.

**Comment by paulo-carvajal** [comment]
Solve this, please!!! Debugging is a nightmare.

**Comment by dudaster** [comment]
On it.

**Comment by dudaster** [comment]
It will be available in next version

**Comment by kwsim539** [comment]
Awesome! Thank you.
