### ISSUE TITLE
I can't edit my loops

### ISSUE THREAD

**Issue by drkhg** [dudaster/ele-custom-skin#575]
Hi everyone,
I'm working on a new website that has 3 loops and 3 different custom grids for the different post types. Yesterday night I wasn't able (suddenly) to edit my loops with Elementor. I have since had  the typical 'The content area was not found in your page' message. And I get the same message if I want to create a new one. I executed all the troubleshooting methods without any success. I disabled Ele Custom Skins. I deleted it than installed it again. My loops have no instance, the database of the site is not empty. Do you have any idea what happened? Thanks,
drkhg

**Comment by dudaster** [comment]
Have read #201 ?

**Comment by drkhg** [comment]
Sorry, no.  I've searched the FAQ, but I missed this post. Thank you, that solved the problem. :)
