### ISSUE TITLE
custom post type archive template

### ISSUE THREAD

**Issue by mmjaeger** [dudaster/ele-custom-skin#580]
Hello
I've created a Elementor archive template and a loop template - the posts are showing up as they are supposed to - however when clicking on a term on the CPT archive page the term page still shows all the posts not just only the posts for that specific term - I have assigned the CPT archive template to all the term pages of that specific CPT as well - is there a way to adjust the query dynamically so it would only pull the posts for a specific term or do I need to copy the CPT template for every term and adjust the query??

**Comment by dudaster** [comment]
User Archive Posts Widget or Posts Widget with Current  Query

**Comment by kwsim539** [comment]
Post Per Page no longer works when the Current Query is selected. Even though I have selected 1 in the Post Per Page it stills lists all the posts.
