### ISSUE TITLE
Infinite load does not work!

### ISSUE THREAD

**Issue by dionisis17** [dudaster/ele-custom-skin#583]
User with active PRO license.
I notice that when I install the custom skin plugin the "posts" widget loses the infinite scroll option that I had enable and active before install ECS. Despite that I tried to use that option from ECS but in doesn't work at all. Please help...

**Comment by dudaster** [comment]
please leave an url to take a look!

**Comment by dionisis17** [comment]
https://smartmarker.gr

**Comment by dudaster** [comment]
It seems your js is broken. I think is because of the minifying it. can you disable the minify js and try again?

**Comment by dionisis17** [comment]
I use nitropack.io. Ι disable it before send you the URL. I do not have any other plugin for cache-minification...

**Comment by dudaster** [comment]
can you please make it with load more button to see if it works that way?

**Comment by dionisis17** [comment]
I make it [here](https://smartmarker.gr/en/interactive-touch-screens/). Neither this work! No button shows up...

**Comment by dudaster** [comment]
You need to use custom skin for the pagination to work.

**Comment by dionisis17** [comment]
You mean that if I use the elementors skins (classic, cards, full content) I have this problem and I do not use them?

**Comment by dudaster** [comment]
Yes. Please make a custom skin and use it.

**Comment by dionisis17** [comment]
I understand that you gave me a half solution and I really appreciate your fast response and your time but **this is not the proper way** that the plugin must to work. I do not want to use ECS in this page. I use ECS in other page for making a posts slider. In this page I have had already elementor default posts widget and the infinite scroll that worked perfectly. When I uploaded ECS and made a loop for using it in a total different place this issue happen? 
Is it right to fix it? Am I wrong?

**Comment by dudaster** [comment]
All the functionalities are for the custom skin only.

**Comment by dionisis17** [comment]
Alright. Thanks again for your time and support. I appreciate it !
