### ISSUE TITLE
Support for latest elementor

### ISSUE THREAD

**Issue by pbaddock** [dudaster/ele-custom-skin#586]
Hi,
My developer is reporting that some errors editing archive page are caused by ele custom skin pro compatability with latest elementor 3.3.8.   Should I report these as bugs here or can you advise when an updated version compatible with elementor 3.3.8 will be available?  tks in advance.

**Comment by dudaster** [comment]
It is tested to the last elementor. Can you paste the error here?

**Comment by pbaddock** [comment]
![Screen Shot 2021-10-07 at 5 10 34 pm](https://user-images.githubusercontent.com/68455443/136355288-15f98f77-8125-46fc-b65f-054bdee01de8.png)

Error when trying to edit single post template on this page:
https://wordpress-235684-2110159.cloudwaysapps.com/news-media/

....the JS errors seem to be preventing from editing various elements on the screen.

**Comment by votanmy** [comment]
Here is the compatibility alert:

![elementor-compatibility-issue](https://user-images.githubusercontent.com/32262083/136362880-20ae3a8d-6518-45c3-99a3-59f744cf4cb8.jpg)

**Comment by dudaster** [comment]
If you disable the ECS Pro is it working?

Tested version is just a header in the main plugin file, is not a testing routine on behalf of Elementor.

**Comment by pbaddock** [comment]
Actually testing again now - pro doesn't seem to be the issue - it's the the non-pro ELE Custom Skin plugin.
If that is enabled the JS errors / inability to edit the single-post template occur - if I disable, they are gone and I can edit as expected.

**Comment by dudaster** [comment]
try dudaster@gmail.com

**Comment by pbaddock** [comment]
Cheers, thanks - it seems its working now - I'm not quite sure why or what the fix was, but now re-enabling the plugins seems to have the page be able to be edited ok.   Thanks for your responses and support - appreciate it!
