### ISSUE TITLE
can't select default template

### ISSUE THREAD

**Issue by ghost** [dudaster/ele-custom-skin#59]
I try to select a default template, I see it but I can't select it. Hope you can help me out.

tia Edwin

<img width="292" alt="Schermafbeelding 2019-09-05 om 18 00 19" src="https://user-images.githubusercontent.com/7997108/64377105-fee27000-d029-11e9-9bce-c29ecaef07a5.png">

**Comment by dudaster** [comment]
Please search for issues before posting. See #50 .

**Comment by ghost** [comment]
Yes sorry, saw it to late.

Thanks
