### ISSUE TITLE
A lot of NOTICE send NGINX in 502 Error 

### ISSUE THREAD

**Issue by socrates77** [dudaster/ele-custom-skin#6]
This message was printed a lot in error log:

PHP message: PHP Notice: Elementor\Controls_Manager::add_control_to_stack was called incorrectly. Cannot redeclare control with same name. "custom_read_more_typography_letter_spacing_tablet"

Can you give me some clue to try to fix it?

In Nginx with php-fpm it cause this error: upstream sent too big header while reading response header from upstream. 

P.S. I forget to say I have __elementor__ and __elementor pro__ installed and it happens when i have more than one loop template.

**Comment by dudaster** [comment]
I was unable to reproduce this... but I'll still looking.

**Comment by socrates77** [comment]
Hi I'm sorry but I've been in hurry and find a different solution including the box directly with some shortcode magic.
It may be that some system configuration we use make this happen.

**Comment by bryanbartow** [comment]
I'm getting a bunch of similar errors after installing and activating the plugin.
<img width="1448" alt="screen shot 2018-10-20 at 12 29 35 pm" src="https://user-images.githubusercontent.com/867678/47258647-e3976200-d463-11e8-8de3-9c95ac2fa826.png">

**Comment by nicomollet** [comment]
Hello
I am having too many (many) PHP notices like:

`PHP Notice:  Undefined offset: XXX in /home/html/samba/thalassosaintmalo/wp-content/plugins/ele-custom-skin/skins/skin-custom.php on line 116`

` PHP Notice:  Elementor\Controls_Manager::add_control_to_stack est appelée de la mauvaise manière. Cannot redeclare control with same name "custom_columns"`

Elementor 2.2.7
Elementor Pro 2.1.11
Ele Custom Skin 1.0.5
I created an Elementor Archive Template, that calls a Loop Template.

**Comment by dudaster** [comment]
You guys are using linux/windows? Please give me stats of your system. I realy want to help but I seem not to be able to reproduce it.

Thanks!

**Comment by bryanbartow** [comment]
I'm running an instance on WPEngine. I know it's Linux, but not sure of any particulars.

**Comment by dudaster** [comment]
Try using Posts widget instead of Archive Posts widgets and let me know if it does the same. (Select current query in query section to behave like Archve Posts widget)

**Comment by nicomollet** [comment]
Same errors with Posts widget (current query) as with Archive Posts.

All errors disappear after desabling Ele Custom Skin.

I am not Debian / Nginx.

**Comment by dudaster** [comment]
Good news! I managed to replicate the problem. Working on a fix.

Keep tight!

**Comment by dudaster** [comment]
The issue was addressed and the update is up.

**Comment by nicomollet** [comment]
It seems to work, thank you ;)
