### ISSUE TITLE
Custom skin breaks leaving 1 empty element

### ISSUE THREAD

**Issue by axeldelat** [dudaster/ele-custom-skin#60]
When I create a Custom Skin and use it inside elementor builder everything works as show in the image below
[Image 1](https://ibb.co/KsQtS3v)

But when the result turns out to be different, 
[Image 2](https://ibb.co/8P5KZdt)

It seems to break the whole layout leaving 1 empty element before the posts and removing the style of the loop.

**Comment by dudaster** [comment]
This happens every time or it’s a certain case?

**Comment by axeldelat** [comment]
I had an error in my custom post type configuration.
