### ISSUE TITLE
Post Per Page no longer works when the Current Query is selected

### ISSUE THREAD

**Issue by kwsim539** [dudaster/ele-custom-skin#600]
Post Per Page no longer works when the Current Query is selected. Even though I have selected 1 in the Post Per Page it stills lists all the posts.

**Comment by dudaster** [comment]
Try disable ECS and see if it does the same!

**Comment by kwsim539** [comment]
What is ECS?

**Comment by dudaster** [comment]
Abbreviation for EleCustomSkin

**Comment by kwsim539** [comment]
UGH! Looks like an Elementor issue. Getting the same results from the regular Posts widget.

**Comment by dudaster** [comment]
Try using query Id to fix it or change the number of posts from the wp settings but is a general setting

**Comment by kwsim539** [comment]
Yeah, that won't work. Trying to add a feature post at the top and post list underneath for the category page, (screenshot attached). This is defiantly an issue with the Elementor widget and I am letting them know about it. Thanks for the recommendation though.

![Screenshot 2021-11-02 142845](https://user-images.githubusercontent.com/8410150/139937089-26b396e9-ddfa-41c3-9271-e0ea8e6e0f76.jpg)

**Comment by dudaster** [comment]
https://developers.elementor.com/custom-query-filter/

**Comment by kwsim539** [comment]
Got it. Thanks
