### ISSUE TITLE
Support contact & license questions:D?

### ISSUE THREAD

**Issue by fafarafiel** [dudaster/ele-custom-skin#61]
Hello

How can i reach someone from marketing support team to check my license and confirm its lifetime unlimited ( bought while back ) and its the same as present perpetual? I would like to confirm this before LTD is gone??

**Comment by dudaster** [comment]
Send me an email and I'll check it out. If you bought the first package (first 100 promo) I can confirm is Unlimited and it's the same as the current Perpetual.

**Comment by fafarafiel** [comment]
try m.f.majer@gmail.com or mfmajer@gmail.com please

**Comment by dudaster** [comment]
Yes it is unlimited and it's on the gmail one. Please do not put your email public. Thanks!

**Comment by fafarafiel** [comment]
I know - had no time to email you in private:) so basically its perpetual yes? and dont have to upgrade my license?

**Comment by dudaster** [comment]
That's correct!

**Comment by dudaster** [comment]
Early bird get's the worm.

**Comment by fafarafiel** [comment]
looks like:) risked and looks like to gonna save my life today, but first of all need to learn how to use it:P

**Comment by fafarafiel** [comment]
and one more silly question:) do i need to use free if i have pro already? any reason/necessity to do such? or no need and pro only is ok?

**Comment by fafarafiel** [comment]
btw appsumo offers lifeagent ltd:) you should add it, looks more pro to get any contact on your page:)

**Comment by dudaster** [comment]
It is like Elementor with Elementor Pro. ECS Pro goes along with the free version and adds more functionality.

**Comment by dudaster** [comment]
Thanks! I'll keep that in mind.

**Comment by fafarafiel** [comment]
sure:) btw - check your email:) just shoot you there a pm :)
