### ISSUE TITLE
No Invoice and no License Key

### ISSUE THREAD

**Issue by JayTee2312** [dudaster/ele-custom-skin#62]
Hi,
I don't know how to get an invoice for my license of Elementor Custom Skin Pro - Unlimited

I can't find the license Key from my Installation, in Elementor settings there's only the text "The license is valid." and a button Deactivate License. No E-Mail has been sent to my Mailbox. What can I do?

I baught a second license for my company, there I got an e-mail with the licensing information and a link to create an invoice.

Yours
Jürgen

**Comment by dudaster** [comment]
The purchase is made from gumroad. Please check your email and your junk folder!

You can login with your gumroad account and get an invoice from there.

Also you can write me an email with the email of the purchase to be sure everything is ok.

**Comment by JayTee2312** [comment]
I don’t know which email address I used for the purchase I think that's the problem. Where can I find the license number, so I can send it to you.

**Comment by dudaster** [comment]
Please send me an email, so we can talk there!
