### ISSUE TITLE
Strategies for a featured post in the loop?

### ISSUE THREAD

**Issue by jess8bit** [dudaster/ele-custom-skin#63]
Hi, I'm looking for ideas/suggestions to be able to have a skin template specific to a given post in the loop.

Typically, I would like to render the first one differently than all others - like a featured post - but this could be also extended to specific posts (in a more advanced configuration, but this not what I'm looking for right now).

I looked into the alternating feature but it seems to be meant only to alternate indefinitely between Nth posts (which is the point, no offense ;) ).

But I wish I could at least designed the first one in the loop differently ("Featured"), and for that using a dedicated skin.

Any chance ECS Pro will offer such possibility in the future? Or, would you suggest a workaround maybe?

thanks :)

**Comment by dudaster** [comment]
Everything is limited to your imagination. Try to see what is available and how can you use it for your purpose.

Let's take your example: Featured
1. First drag and drop a Post widget use your desired skin to it and select Post per Page to 1.
2. Drag a second Post widget and in query go to Exclude and enter 1 to Offset to skip the first post which was used in the previous Post widget.

What you can use Alternative Templates for?

I think this is the holy grail of a dynamic website. Imagine you can design a homepage being completely dynamic looking like someone design it by hand, and your client needs only to enter new posts/info without a need to explain how Elementor works. How cool is that?

I plan to make some templates/examples/tutorials in the future , until then you can check some of the Elementor Post widget tutorials on Youtube and learn a few tricks from there.

**Comment by jess8bit** [comment]
Thanks for the imagination booster, I needed it and it made my day :) 

Also, I was afraid {{index}} would be re-indexed when you offset the loop, but it doesn't, so the second Posts Widget can start at index "2", perfect!

closing it :)

**Comment by jess8bit** [comment]
Might have spoken too fast.

The {{index}} is not reindexed while in Elementor editor, but it seems to be in the running frontend. Bummer!

Tried to trick it by doing {{index+1}} but no luck.

**Comment by jess8bit** [comment]
So, I looked into your code to get some inspiration and find out how {{index}} works., which led me to a solution, by using the ecs_vars filter:

Since the {{index}} is based on the $ecs_index global variable, I reused it in the filter, in order to create a custom variable that returns an incremented index, like this.

```
add_filter( 'ecs_vars', function ( $custom_vars ) {
	global $ecs_index;
    $custom_vars['index-offset-1']=$ecs_index+1;
    return $custom_vars;
});
```

so in my second Posts Widget's skin (with a +1 offset), I use {{index-offset-1}} of instead {{index}} and then it starts counting from 2.
Works!

But please tell me what you think of my solution. Is it sustainable? I'm asking because it relies on the naming of the global var taken from your code. It would break if you decide to change this naming...

**Comment by dudaster** [comment]
Great find! Go for it!
