### ISSUE TITLE
Same height doesn't work

### ISSUE THREAD

**Issue by digitalerach** [dudaster/ele-custom-skin#630]
Hi guys, I have a problem with the plugin.

The function same height do not work on my website.

Here is the link: https://bit.ly/3pDPSit

Let me know what I can change to fix that. Thanks.

**Comment by heikkiwaan** [comment]
did you get it fixed?

**Comment by alex-ardour** [comment]
Hi, I have the same problem also. Did you ever get a reply from @dudaster? I have tried contacting on other channels also and haven't had a response... I've only just paid for the pro version so it's a bit annoying when things don't work and there is no support provided.

**Comment by kingfisher64** [comment]
I'm having a similar issue with the PRO version for woocommerce products.
Asked months ago now no reply. It certainly looks like support isn't being offered for paying customers. Maybe the sheer amount of requests has been overwhelming? But it doesn't look good.

**Comment by dudaster** [comment]
We are having issues with live support. Due to winter holidays the technical support is slow.

**Comment by alex-ardour** [comment]
@dudaster Thanks for your reply and most customers will be understanding/forgiving of the delays. Do you have any idea of when you will be able to clear the backlog? I have customers depending on some of the functionality that your plugin provides and have built a solution around it... the delays on your side will result in delays on our side and we need some form of indication of timelines.

**Comment by puregraphx** [comment]
@dudaster 
Almost 2 months after original post, current version 3.2.1 still does not display equal height. Masonry and Slider in the same settings box both work. Equal Height does nothing.

**Comment by dudaster** [comment]
I’m was not able to reproduce it on my side.Could be a CSS conflict somewhere. Can you provide an url with an example so I can see what the issue might be?

**Comment by puregraphx** [comment]
> I’m was not able to reproduce it on my side.Could be a CSS conflict somewhere. Can you provide an url with an example so I can see what the issue might be?

I'd be happy to, https://wordpress-559334-2316514.cloudwaysapps.com/nieuws/
For your convenience, I have disabled all plugins except Elementor, Elementor Pro and your Free and Pro plugins and switched to the TwentyTwentyTwo theme.

I've also found a similar article from August 2021 #550 with a very complex workaround that indeed cannot be used as final fix.

**Comment by dudaster** [comment]
Can you please edit the page with the posts widget and desable and save it and than re-enable it and save it. Let me know. If it is not going to work it means this fix was not released and I will release it ASAP.

**Comment by puregraphx** [comment]
I tried your steps, it did not fix it. Edited the page with your Free and Pro plugins both disabled and enabled. Equal Heights still does not work.
In fact, the solution could be a stupid simple line of css. As each loop template will always start with an Elementor Section.
`/* Fix - Elementor Custom Skin Equal Height */
.ecs-post-loop .elementor > .elementor-section {height:100%}`

Your CSS already has ".ecs-post-loop .elementor" set to height:100% and indeed, that sets the div type=loop to 100%, but if you have a border or a shadow set to the loop template, then that is applied to the section WITHIN div type=loop.

**Comment by joelinit1** [comment]
Thanks @puregraphx - this fixed it for me

**Comment by gustavovitor** [comment]
Same problem here.
