### ISSUE TITLE
Display mode doesn't show any options

### ISSUE THREAD

**Issue by ncasedk** [dudaster/ele-custom-skin#652]
Display mode doesn't show options for Masonry or same height. How do I turn that on. Elementor Version 3.5.3 and Elementor Pro Version 3.5.

<img width="1729" alt="Skærmbillede 2022-01-06 kl  15 54 06" src="https://user-images.githubusercontent.com/10637883/148401953-923908d2-8c16-4326-a667-7f58d23c7e9e.png">
2

**Comment by dudaster** [comment]
Try to reinstall both free and pro ECS plugins

**Comment by ncasedk** [comment]
Thank you for your quick reply. 
It didn't work.

**Comment by dudaster** [comment]
Is there a way you can try it on another server, to see if it works?

**Comment by ncasedk** [comment]
If I install it on another site (same server) that has an old version of WordPress and also Elementor that hasn't been updated for a while, it works fine. Could this be a matter of not being compatible with a new version?
<img width="1535" alt="Skærmbillede 2022-01-07 kl  09 17 29" src="https://user-images.githubusercontent.com/10637883/148513512-fb5c866a-49bb-4866-a958-17f33181b6f1.png">

**Comment by ncasedk** [comment]
I found out that it only didn't work on the archive-page I was working on. It worked well on other pages, so I have just copied it over. Don't know exactly what was up, but I'm guessing it might be because the first widget was created before I installed the Pro plugin.
