### ISSUE TITLE
Returns + Custom Posts

### ISSUE THREAD

**Issue by granddigital** [dudaster/ele-custom-skin#662]
Hi, 

Great plugin. I'm interested in purchasing Ele Custom Skin Pro but I'm not 100% it has the functionality I need. So I have a few questions: 

1 - If I purchase it but it doesn't do what I need it to, can I get a refund? 

2 - I have a custom post type called "Programs". I am creating a Loop for this custom post type. Each post in the loop will need to include: 

A) A featured image (taken from the standard WP functionality)
B) A logo (which I presume I'll need to setup with with ACF)
C) Excerpt (which I can currently do in regular Ele Custom Skin)
C) A program title (for some reason I can't currently do this with regular Ele Custom Skin)

Will Ele Custom Skin PRO allow me to do this? 

Thanks

**Comment by dudaster** [comment]
You should be able to do all of the points with the free version.

**Comment by granddigital** [comment]
Thankyou
