### ISSUE TITLE
Update Error, please help!

### ISSUE THREAD

**Issue by aimkbe** [dudaster/ele-custom-skin#67]
Getting an error when trying to update the ele custom skin pro plugin

![image](https://user-images.githubusercontent.com/3734267/65262490-4ef81280-dabf-11e9-99c2-1214ab1c4e9c.png)

**Comment by dudaster** [comment]
I'm on it!

**Comment by dudaster** [comment]
Try now!

**Comment by aimkbe** [comment]
Whatever you did…. Worked like a charm!

Abraham Kim
Founder & Owner – Truvi
Cell: 818-307-7055
Email: abraham@truvi.co
Skype: aimkbe
Website: https://www.truvi.co

**Comment by dudaster** [comment]
I made the archive in linux and for some reason some servers like only windows made zip archives. Re uploaded the archive and it works. It happend before with archives made on MacOS and I thought it was only a MacOS issue but... it seems windows it is the right way to archive it.
