### ISSUE TITLE
Is this plugin abandoned?

### ISSUE THREAD

**Issue by kaspergram** [dudaster/ele-custom-skin#688]
Bought a license last year. Wrote to support, but never heard back. It seems all the issues for the last couple of months are still open and there are no replies from the developer.

Maybe he stopped supporting the plugin?

**Comment by dudaster** [comment]
It is still supported.

`/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php](http://investkon.dk/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php)`
on line
1271

usually appears when a dynamic value is not there. Make sure you didn’t change it.

**Comment by kaspergram** [comment]
Hi. I did not change it. When working within the loop template, it's working fine

https://imgur.com/a/ZuRAiPa

But when used in an archive on a page it's not working.

Tried changing the number in the post and saving again. Did not help.

**Comment by dudaster** [comment]
If you remove that from the template the error disappears?

**Comment by kaspergram** [comment]
Yes. The error disappears.

Removing the widget and adding it again creates the same error code.

**Comment by dudaster** [comment]
And if you are using a heading widget with the same value it works ok?

**Comment by kaspergram** [comment]
Yes - https://imgur.com/a/39HaPsy

**Comment by dudaster** [comment]
It is a long shot but try using it with a fallback value of any kind.

**Comment by kaspergram** [comment]
Good idea, but unfortunately it did not help.

**Comment by dudaster** [comment]
Let’s try with dynamic everywhere: instead of dynamic value just add {{name-of-field}} and don’t forget to check the box in posts widget

**Comment by kaspergram** [comment]
It seems you can only input numbers: https://imgur.com/a/19deUkv
But tried with a headline. Seems it's not replacing {{andele_solgt}} with a number. Maybe it needs some php-code to the theme file? But it seems the progress bar widget does not accept dynamic everywhere in the percentage field.

**Comment by dudaster** [comment]
The progress bar widget is from Elementor pro right?

**Comment by kaspergram** [comment]
Yes. Already wrote elementor. This is their answer







I can see you have used third party addon plugin called 'Ele Custom Skin' to extend the functionality of elementor such as templates inside a loop, add templates in the post widget etc.

I hope you understand functionalities are not controlled by us and not some thing that we can help as you are using there features here: https://i.imgur.com/xW8NhbC.jpg.

Also, this might be happen due to a compatibility issue within there code, so I recommend you reporting the issue to the plugin author cause as most of the time compatibility issues are out of our hand and the author of the plugin/theme needs to resolve it as we are not aware of their codes and functionality and also, here we don't provide support for the theme or plugin conflicts- [Support Scope](https://docs.elementor.com/article/169-do-i-get-special-support#whatwesupport).

If the plugin needs any help they can contact us with our [Github account](https://github.com/pojome/elementor/issues) where these types of issues are handled.

**Comment by dudaster** [comment]
I will try to reproduce it on my end. Thanks for the info!

**Comment by kaspergram** [comment]
Thanks. Let me know if you need a login.

I've just created a test post. Now the post with errors is displaying fine. It's only the first post in the loop that is producing an error.

**Comment by kaspergram** [comment]
Hi. Did you figure it out? I am still having the same issue.

**Comment by kaspergram** [comment]
Hi. I  just tried updating. I am still having the same issue. Is there a fix coming or should I abandon the plugin? I really need to get this issue solved.

**Comment by dudaster** [comment]
Still working on a fix.

**Comment by kaspergram** [comment]
Alright. Looking forward to hearing from you.

**Comment by kaspergram** [comment]
Hi. Sorry to bother you again, but the customer is poking me? If you're not able to find the bug I'd like to know so I can use choose another plugin from another developer.

**Comment by kaspergram** [comment]
Hi. Any news? It's OK if you cannot solve the issue. I'd just like to know.
