### ISSUE TITLE
Same height - content not properly aligned (see screenshot)

### ISSUE THREAD

**Issue by djaysan** [dudaster/ele-custom-skin#702]
Hello, I am facing an issue where 'same height' is activated on my loop but not properly aligning my content with 'space between'.

see the screenshot below:

![Screenshot 2022-03-04 at 13 56 37](https://user-images.githubusercontent.com/12181193/156767502-32e98b85-c91a-42d0-9e12-270cf01b998e.png)

Any fix for this?
thank you in advance.
the link i need help with: https://bit.ly/34gmIza

**Comment by djaysan** [comment]
Attached is another example: 

I would like to get my title aligned on top, buttons aligned on bottom and whatever is between just centered.
![Screenshot 2022-03-04 at 14 01 20](https://user-images.githubusercontent.com/12181193/156768345-fbb9a308-1a86-4f2b-a4c3-2f53adaaf142.png)

**Comment by adjoyrune** [comment]
<img width="2226" alt="Skjermbilde 2022-03-04 kl  14 39 45" src="https://user-images.githubusercontent.com/100946380/156774495-3ae9f146-fcf7-4874-931f-9add9844ec09.png">

**Comment by djaysan** [comment]
@adjoyrune this is not the same problem. this is only due to the fact that you have either 2 rows or a inner section in your template. Please check other post - i fixed it by using only 1 section and no inner sections. (see my screenshot above and you will see its not the same issue.

Cheers.

**Comment by ghost** [comment]
@djaysan ok thx

**Comment by djaysan** [comment]
@dudaster is there any ways to get premium support with your pro version of this plugin?
