### ISSUE TITLE
Same Height Work-around (possible temporary fix)

### ISSUE THREAD

**Issue by alex-ardour** [dudaster/ele-custom-skin#706]
Hi Everyone, 

I know there are a few topics on here now regarding the same-height function. 

So I just thought I'd share a solution I've managed to get working in one of my clients sites. Its a bit bulky (uses https://www.elementpack.pro/demo/element/widget-equal-height/) but does the trick for now. 

It seems that the issue comes from loop templates that have multiple sections in them that could vary in height, then the 'same height' toggle doesn't seem to be able to balance multiple varied rows etc or know which element to make the same height so breaks the whole loop. 

Anyway, if you wrap the section you know is most likely to vary in height i.e. the excerpt of a post within an 'inner section' in your loop template:

<img width="237" alt="Screenshot 2022-03-08 at 12 44 29" src="https://user-images.githubusercontent.com/96419666/157240721-6be30b68-b389-485d-9b86-f37a474d776c.png">

Then give it a css class in the advanced tab:
 
<img width="452" alt="Screenshot 2022-03-08 at 12 44 44" src="https://user-images.githubusercontent.com/96419666/157240888-822098d4-815f-4ba2-bb98-5b8cade3e736.png">

Now move to the page you're using the loop on and on the section that the loop is used in activate  this plugin: https://www.elementpack.pro/demo/element/widget-equal-height/ then target the css class in custom selector. (note, it doesn't work in the elementor preview but does in the live environment. 

<img width="331" alt="Screenshot 2022-03-08 at 12 49 07" src="https://user-images.githubusercontent.com/96419666/157241539-4f16dfa2-b267-4753-a891-439e708c4c12.png">

I'm not encouraging everyone to do this but if you're desperate it might work. It could also help to provide a solution for the main plugin? Hopefully this helps the community and @dudaster identify what the main glitch is.

**Comment by djaysan** [comment]
Thank you so much @alex-ardour it worked for me. even with another plugin called 'the plus' for elementor :)

**Comment by dudaster** [comment]
The fix is almost ready.

**Comment by raediant** [comment]
Is this fix live? i have the latest version am have the same issuee
