### ISSUE TITLE
Elementor post widget panel is empty

### ISSUE THREAD

**Issue by OlivierPaudex** [dudaster/ele-custom-skin#71]
Hi,

Just try your skin widget, but it doesn't work. As I already search on Google, it seems that you already had this problem 10 month ago and provide a fix

Version I tried : 1.3.2
Elementor 2.7.3
Elementor Pro : 2.7

I tried to rollback elementor pro to 2.6.5, but not better.
I tried to start again from a fresh WP with no other plugin than those 3.
Hope we can have a fix

Thanks

![image](https://user-images.githubusercontent.com/52828701/65531047-5a04d580-def9-11e9-8fc0-55f6a06fe019.png)

**Comment by dudaster** [comment]
You selected Custom Skin? If you deactivate ECS is it working?

**Comment by dudaster** [comment]
It seems others experience this but I cannot reproduce it :(. What is you eviroment? Can you provide me with more details? I'll appreciate.

**Comment by dudaster** [comment]
If you delete de widget from page and add it again the issue persists?

**Comment by OlivierPaudex** [comment]
Hi,

Yes, I tried to deactivate ECS and Elementor Pro posts widgets works again. Reactivate it and crash. The bug really comes from your plugin.

I have Wordpress 5.2.3, Elementor Pro 2.7, Elementor 2.7.3
I run the "Hello Elementor" theme

I will try an older version of your plugin

Thanks

**Comment by OlivierPaudex** [comment]
> If you delete de widget from page and add it again the issue persists?

Yes

**Comment by dudaster** [comment]
Do you have an error? Some people complained they get an javascript error. You can check the error in console that you can see it by right clicking on the content and select "Inspect Element"

**Comment by dudaster** [comment]
What Theme are you using?

**Comment by dudaster** [comment]
Also can you provide me with the link of the issue 10 month ago?

**Comment by OlivierPaudex** [comment]
Are you speaking about the inspector element of Firefox ? No error there

I'm using "Hello Elementor" theme

The link you asked for : https://wordpress.org/support/topic/post-content-widget-not-showing-when-elementor-custom-skin-plugin-is-activated/

and...version 1.1.0 works fine :-)

**Comment by dudaster** [comment]
at 1.2.5 it breaks? you can download it here: https://wordpress.org/plugins/ele-custom-skin/advanced/

**Comment by dudaster** [comment]
I will also appreciate if you go to Elementor > System Info > Copy & Paste Info

**Comment by OlivierPaudex** [comment]
1.2.5 works too !! and in french, for me

**Comment by OlivierPaudex** [comment]
here you are 
[system-info-www.fuyens.ch-24-09-2019.txt](https://github.com/dudaster/ele-custom-skin/files/3648663/system-info-www.fuyens.ch-24-09-2019.txt)

I have to go....see you tommorrow. Hope you will found a solution.
Thanks
Olivier

**Comment by dudaster** [comment]
If you want we can talk on skype and solve this ASAP.

**Comment by dbaruchel** [comment]
hello! Same problem here.

I do indeed get a javascript error when I try to edit the Post widget: 
![image](https://user-images.githubusercontent.com/6543134/65536660-2aa79600-df04-11e9-8faa-37211944902c.png)

The panel works when I deactivate ECS
I tried to rollback Ele Custom Skin: latest working version is 1.1.4 (but without the feature I need)

Using Astra Theme
Wordpress 5.2.3
Elementor - 2.7.3
Elementor Pro - 2.7.0

**Comment by dudaster** [comment]
1.2.5 is not working for you @dbaruchel .

**Comment by dbaruchel** [comment]
nope

**Comment by dudaster** [comment]
can you provide me a sandbox where I can check what is going on? I cannot replicate it :(

**Comment by dudaster** [comment]
I was able to replicate the problem. It seems the french language ECS  is not working properly. I'll research to see why is this happening.
Do you guys have other languages installed and having this issues?

**Comment by dudaster** [comment]
Ok I found the where the bug lies. It is a translation issue:
https://translate.wordpress.org/projects/wp-plugins/ele-custom-skin/dev/fr/default/?page=3

To many curly brackets in there. I made a correction but I guess it needs to be reviewed to be effective. If you can help I'll appreciate.

**Comment by dudaster** [comment]
Never mind I'll patch it tomorrow to many mistakes in other languages too. It needs to stop.

Thanks guy! You are the best!

**Comment by OlivierPaudex** [comment]
Thanks to you
Let us know when the new version is available

**Comment by dudaster** [comment]
The update is out. Let me know if it fixes the issue.

**Comment by dbaruchel** [comment]
Hey @dudaster it works now ! Thanks a lot for your help and reactivity !

**Comment by dudaster** [comment]
Glad to help!
