### ISSUE TITLE
Cannot select custom skin anymore since 1.3.3

### ISSUE THREAD

**Issue by ericfettweis** [dudaster/ele-custom-skin#72]
In the Elementor Pro Posts Widget, When I try to select the loop template I made, though the template appears in the select popup, nothing happens. The select template field remains empty.
![after-selected-skin](https://user-images.githubusercontent.com/30296736/65588667-39379100-df88-11e9-9eb2-9f44d4f1a342.png)
![before-selecting-skin](https://user-images.githubusercontent.com/30296736/65588668-39379100-df88-11e9-8ae9-0c9ff0e3037e.png)

**Comment by dudaster** [comment]
what browser are you using?

**Comment by ericfettweis** [comment]
Safari 12.0.1

**Comment by dudaster** [comment]
Add create another template and try again

**Comment by ericfettweis** [comment]
First, let me say that the problem is not present with Firefox 69.0

With Safari, it works when I create another template.
It seems that it fails only when just one template exists…
Thanks for your help

**Comment by dudaster** [comment]
It is a selector issue (the js library that Elementor is using). I was hoping that a blank record will solve this issue but it seems not. I'll do some digging.

Thanks for the heads up!
