### ISSUE TITLE
Ele Custom Pro - License Missing

### ISSUE THREAD

**Issue by TeamowBee** [dudaster/ele-custom-skin#73]
Hey Dudaster,

i purchased the pro version an September 17th but never recieved an e-mail with an invoice or license key and i cant find a login section or something. Can you help?

**Comment by dudaster** [comment]
Search your email for emails from gumroad.com
Also please use this form: https://dudaster.com/contact/ to contact me and I'll resend them to you ASAP

**Comment by dudaster** [comment]
The Login Section is in the works and it will be available next month.

**Comment by dudaster** [comment]
Have you received the the receipt?

**Comment by TeamowBee** [comment]
I didnt have a receipt. I sent an email via contact form - but didnt get an answer?

**Comment by dudaster** [comment]
Just sent you an email, please reply!

**Comment by TeamowBee** [comment]
Check

**Comment by dudaster** [comment]
Have you received an email from Gumroad ? Check the spam folder too.
