### ISSUE TITLE
Do the devs even check these support tickets?

### ISSUE THREAD

**Issue by elliotmersch** [dudaster/ele-custom-skin#736]
I've had an issue that I posted about over 2+ weeks ago and I also submitted a contact form on their site but no response.

Why TF am I paying for the premium version when so many core features are broken and the devs seemingly don't care? Getting really frustrated with this plugin.

**Comment by dudaster** [comment]
Yes I do. For your issue you can fiddle with custom query. https://developers.elementor.com/docs/hooks/custom-query-filter/

The issue is because between page one and page two the website doesn’t remember what was shown or not.
