### ISSUE TITLE
Updated to Pro, still dont have pro features 

### ISSUE THREAD

**Issue by mcoleman44** [dudaster/ele-custom-skin#74]
I just updated to pro and purchased the $59 option. I installed the plugin, activated it, and put the license in under settings. Ele custom skin is still activated alongside Ele pro. I tried deactivating both and reactivating, still no luck.

Thanks!

**Comment by dudaster** [comment]
Hi! Would you like to have a skype call?

**Comment by dudaster** [comment]
Also make sure you have the latest version of ECS alongside ECS Pro.

**Comment by mcoleman44** [comment]
I have ECS 1.3.3 and ECS Pro 1.3.1

I would do skype but I dont have a mic.  I trust you though. We can screen share, can we still do that through skype?

**Comment by mcoleman44** [comment]
I have Log me in too if that would work better

**Comment by dudaster** [comment]
please use this contact form and send me your skype id: https://dudaster.com/contact/

**Comment by dudaster** [comment]
Thanks for the heads up. It seems the ECS plugin doesn't detect ecs-pro init function. I need to find the reason why this is happening and how we can work around it.
