### ISSUE TITLE
Problem with elementor container background image being repeated in loop 

### ISSUE THREAD

**Issue by paulieokay** [dudaster/ele-custom-skin#747]
Hello I have created a loop (card that includes and image, text and link) using the new flexbox container but the background image repeats if i use the loop as a slideshow or blog series, any easy fix?

**Comment by mediadolphin** [comment]
I have the sam issue. Any updates here?

**Comment by umm-wdc** [comment]
@paulieokay  I'm facing the same issue, did you find a fix  ?

**Comment by mediadolphin** [comment]
Unfortunately not. Very disappointing.

Sent via mobile device.

Am 16.05.2022 um 16:58 schrieb UMM Digital - WDC ***@***.***>:

﻿

@paulieokay<https://github.com/paulieokay> I'm facing the same issue, did you find a fix ?

**Comment by dudaster** [comment]
The fix is released. Please update!
