### ISSUE TITLE
Link section loop template

### ISSUE THREAD

**Issue by sigersmit** [dudaster/ele-custom-skin#75]
Hi,
I created a Loop template in Elementor, and would like the complete section to be a Dynamic Link (to the post or custom URL), so when on the frontend you click the whole postblock to go to the post (or the custom url field). 
Is it possible to implement this?
Thank you.

**Comment by dudaster** [comment]
It is in the plans for future release. Until then...
There is a plugin but it doesn't work in Archive Posts Widget only in Posts Widget. It is called make every column a link or something like that. Search the Wordpress plugin repository!

**Comment by dudaster** [comment]
Forget that. Is not working anymore. I'll try to roll out this feature this week. So sit tight!

**Comment by sigersmit** [comment]
Great! Thank you.

**Comment by gb3000** [comment]
Hi @dudaster ! Great plugin, many thanks for doing and maintaining it. Is there any update on this?
Best,
Gustavo

**Comment by dudaster** [comment]
I spent a week on it and it’s harder then it looks. But I’ll keep trying.

**Comment by gb3000** [comment]
Thanks man!
