### ISSUE TITLE
BuddyPress makes warning of Ele Custom Skin

### ISSUE THREAD

**Issue by xwonorb** [dudaster/ele-custom-skin#76]
After activating of BuddyPress v. 5.0.0 Wordpress displays :
Warning: Invalid argument supplied for foreach() in /home/thingbooro/yakumo/wp-content/plugins/ele-custom-skin/includes/ecs-dependencies.php on line 12.

Ele Custom Skin v. 1.3.3
My Wordpress installation is NOT a multisite one.
When I deactivate the BuddyPress the problem disappeares.

**Comment by dudaster** [comment]
Please upgrade to the newest version and let me know if you still experience this issue.

**Comment by xwonorb** [comment]
Yes, it works now.
Thanks

śr., 2 paź 2019 o 14:48 Liviu Duda <notifications@github.com> napisał(a):
