### ISSUE TITLE
Loop  option is not showing 

### ISSUE THREAD

**Issue by Alihaider19** [dudaster/ele-custom-skin#761]
Loop template option is not showing in the elementor templates how can I fix this issue 

![image](https://user-images.githubusercontent.com/102358685/165859934-c9243b8f-cdde-453d-8eb3-b013601e72f8.png)

**Comment by murrinmedia** [comment]
This is happening for me as well - no loop tab

**Comment by Alihaider19** [comment]
The issue is resolved for me. I was using pro element plugin from github thats why the loop option is not working. Now I replace the plugin with elementor pro after that all the options are working .

**Comment by murrinmedia** [comment]
What do you mean exactly?
I'm not using the github elementor.... I'm using Elementor Pro. Not working though

**Comment by Alihaider19** [comment]
> This is happening for me as well - no loop tab

you must have elementor pro installed for this

**Comment by murrinmedia** [comment]
I have. It's been installed the whole time

**Comment by Alihaider19** [comment]
> What do you mean exactly? I'm not using the github elementor.... I'm using Elementor Pro. Not working though

go to theme builder option and click on add new from there you will add loop option to templates

**Comment by Alihaider19** [comment]
> I have. It's been installed the whole time

ah1034299@gmail.com email me the credentials for website let me check once if its ok with you

**Comment by murrinmedia** [comment]
All good, I have fixed now, uninstalled and reinstalled the Ele Custom Skin plugins
