### ISSUE TITLE
Featured image background using flex container not working in loop 

### ISSUE THREAD

**Issue by umm-wdc** [dudaster/ele-custom-skin#777]
Featured image used as container background in a loop template is not working, it repeats the same image for all posts.

**Comment by umm-wdc** [comment]
@dudaster  https://ummdigital.in/umm/case-studies/    sample content with featured image setup as bg and also as an image element, the image element is working fine but the background is not working

**Comment by umm-wdc** [comment]
@dudaster  this is impacting a lot of our client sites, any quick fix for this ?

**Comment by dudaster** [comment]
Try adding a fallback image. Also make sure your featured image works by
adding a test image widget with the featured image

**Comment by umm-wdc** [comment]
@dudaster yes the fallback image is set.. and yes tested the featured image by adding an image widget it works, only the container bg not working ,, pls chk by demo  link https://ummdigital.in/umm/case-studies/

**Comment by umm-wdc** [comment]
@dudaster  same issue reported by others too pls chk https://github.com/dudaster/ele-custom-skin/issues/747

**Comment by umm-wdc** [comment]
Its taking the first post featured image and repeating it for all the posts

**Comment by umm-wdc** [comment]
@dudaster  any update on this ?

**Comment by dudaster** [comment]
@umm-wdc I'm unable to reproduce it on my end unfortunately. Is there a way you can set me up a test version (admin rights) so I can see why this happens?

You can use the contact form to send me the credentials. Thanks!

**Comment by umm-wdc** [comment]
@dudaster  just sent the admin detail over contact form. apologies mentioned git issue #778 instead of #777

**Comment by dudaster** [comment]
I think is behaving like this because of the container (instead of section). I'll see if I can reproduce it on my side with the container also.

**Comment by mediadolphin** [comment]
We are facing the same issue here: https://avenue.digital-avenue.de Solution is urgently needed.

**Comment by dudaster** [comment]
I'm on it.

**Comment by dudaster** [comment]
meanwhile try to use the good old sections to make it work.

**Comment by PXLEY** [comment]
I'm having the same issue also, this only occurs when building out the post loops using the new container system, the image widget works fine but this issue occurs when setting the background to featured image.

**Comment by dudaster** [comment]
The fix is released. Please update!
