### ISSUE TITLE
Issue after update

### ISSUE THREAD

**Issue by kridenour** [dudaster/ele-custom-skin#78]
After I updated ECS Pro and Elementor Pro, all of my loops are now displaying with a very large padding and a white background.

**Comment by dudaster** [comment]
make sure same height is not enabled. For the same height to function properly all the content must be inside one section.

**Comment by kridenour** [comment]
Same height is not enabled, and all of the content is inside the same section in the same column.

**Comment by dudaster** [comment]
Can you provide a link to take a look?

**Comment by kridenour** [comment]
https://www.strategic-sbe.com/speakers/

**Comment by dudaster** [comment]
Is because of Astra theme that has that padding added over... 
I don't know how Astra theme puts the classes in the loop but you can fix it by adding this to your Post Widget/Archive Post Widget Advanced > Custom CSS :  

```
selector .ast-separate-container .ast-article-single{
    padding:0;
}
```

**Comment by kridenour** [comment]
Thank you. That seemed to work. Thanks again for your help.

**Comment by dudaster** [comment]
If you want it to make it global rule add in your theme style.css:

```
article .ast-separate-container .ast-article-single{
    padding:0;
}
```

**Comment by kridenour** [comment]
Thats what I ended up doing. Thanks again for your help.
