### ISSUE TITLE
Fatal error when inserting imported template that uses imported loop item that doesn't match original post_ID

### ISSUE THREAD

**Issue by ToneseekerMusical** [dudaster/ele-custom-skin#780]
I'm working on transferring a few items from my development site and main site. I exported the loop, which had a `post_ID` of 685 on the dev site, and imported it into my production site, where it has a `post_ID` of 293. I have 8 different pages that use this loop and they're all throwing the same fatal error:
```
[17-May-2022 19:16:00 UTC] PHP Fatal error:  Uncaught Error: Call to a member function is_built_with_elementor() on bool in /home3/tonesker/dev.toneseeker.com/wp-content/plugins/ele-custom-skin/includes/admin-bar-menu.php:34
Stack trace:
#0 /home3/tonesker/dev.toneseeker.com/wp-content/plugins/ele-custom-skin/skins/skin-custom.php(42): ECS_Admin_Bar_Menu::add_document('685')
#1 /home3/tonesker/dev.toneseeker.com/wp-content/plugins/ele-custom-skin/skins/skin-custom.php(393): ElementorPro\Modules\Posts\Skins\Skin_Posts_ECS->admin_bar_menu()
#2 /home3/tonesker/dev.toneseeker.com/wp-content/plugins/ele-custom-skin/skins/skin-custom.php(575): ElementorPro\Modules\Posts\Skins\Skin_Posts_ECS->render_loop_footer()
#3 /home3/tonesker/dev.toneseeker.com/wp-content/plugins/elementor/includes/base/skin-base.php(79): ElementorPro\Modules\Posts\Skins\Skin_Posts_ECS->render()
#4 /home3/tonesker/dev.toneseeker.com/wp-content/plugins/elementor/includes/base/widget-base.php(607): Elementor\Skin_Base->render_by_mode()
#5 /home3/tonesker/dev.toneseeker.com/wp-content/plugi in /home3/tonesker/dev.toneseeker.com/wp-content/plugins/ele-custom-skin/includes/admin-bar-menu.php on line 34
```

**Comment by dudaster** [comment]
https://developers.elementor.com/v3-2-planned-deprecations/

From elementor 3.6.0 `is_built_with_elementor()` function is deprecated and is replaced with `Plugin::$instance->documents->get( $post_id )->is_built_with_elementor()`

make sure you have a newer Elementor version then 3.6.0 first and than activate Ele Custom Skin

**Comment by ToneseekerMusical** [comment]
> https://developers.elementor.com/v3-2-planned-deprecations/
> 
> From elementor 3.6.0 `is_built_with_elementor()` function is deprecated and is replaced with `Plugin::$instance->documents->get( $post_id )->is_built_with_elementor()`
> 
> make sure you have a newer Elementor version then 3.6.0 first and than activate Ele Custom Skin

Everything seems to work properly after forcing an update on Ele Custom Skin. Thanks!
