### ISSUE TITLE
Archive Loading Weird

### ISSUE THREAD

**Issue by simea-simea** [dudaster/ele-custom-skin#79]
I have an Issue on multiple sites. When the archive of loops is loading, it displays weirdly and then it loads the right interface. How can I change that? Is that a reported issue?

**Comment by dudaster** [comment]
It's more of an elementor issue. I've reported more than 2 years ago: https://github.com/elementor/elementor/issues/1404

But try use Autoptimize and see if it solves you'r problem. I'm trying to find a solution maybe the latest dev kit allows me to do this.

**Comment by dudaster** [comment]
The new update should take care of the problem.
