### ISSUE TITLE
Sorry the content area was not found 

### ISSUE THREAD

**Issue by madbradjohnson** [dudaster/ele-custom-skin#8]
![capture](https://user-images.githubusercontent.com/36671673/47918372-135b5680-deb5-11e8-94eb-4f8130c0bb5f.JPG)
Hi

I had this issue with the initial install. But found that there was an issue with Elementor Addons. Disabled and it worked. 

Now I have the same issue again. Elementor Addons has been removed from my site.

**Comment by dudaster** [comment]
What theme do you use?

**Comment by madbradjohnson** [comment]
Astra

 

Regards,

Brad Johnson

IT, PR, Marketing, Admin

+27 72 993 1832

+27 11 425 0348

Click on image to view our websites.

 <http://www.mariselaveludo.com/>  <http://www.passion4fashion.co.za/> 

brad@passion4fashion.co.za <mailto:brad@passion4fashion.co.za>  

www.passion4fashion.co.za <http://www.passion4fashion.co.za/> 

www.mariselaveludo.com <http://www.mariselaveludo.com/> 

http://boutique.passion4fashion.co.za <http://boutique.passion4fashion.co.za/>  

 

Please ensure you have read our  <http://www.passion4fashion.co.za/terms---conditions.html> terms and conditions. (http://www.passion4fashion.co.za/terms--conditions.html)

**Comment by madbradjohnson** [comment]
Just changed to 2017 theme and now its working. Changed back to Astra and the issue persists.

 

 

Regards,

Brad Johnson

IT, PR, Marketing, Admin

+27 72 993 1832

+27 11 425 0348

Click on image to view our websites.

 <http://www.mariselaveludo.com/>  <http://www.passion4fashion.co.za/> 

brad@passion4fashion.co.za <mailto:brad@passion4fashion.co.za>  

www.passion4fashion.co.za <http://www.passion4fashion.co.za/> 

www.mariselaveludo.com <http://www.mariselaveludo.com/> 

http://boutique.passion4fashion.co.za <http://boutique.passion4fashion.co.za/>  

 

Please ensure you have read our  <http://www.passion4fashion.co.za/terms---conditions.html> terms and conditions. (http://www.passion4fashion.co.za/terms--conditions.html)

**Comment by madbradjohnson** [comment]
Astra. Changed to 2017.

**Comment by madbradjohnson** [comment]
Just changed to 2017 theme and now its working. Changed back to Astra and the issue persists.

**Comment by dudaster** [comment]
I’ll test it with astra and let YOU know.

**Comment by madbradj** [comment]
its fine
