### ISSUE TITLE
Carousel doesn't works ok

### ISSUE THREAD

**Issue by loremipsumejant** [dudaster/ele-custom-skin#801]
Hi!

I buy the pro version.

In homepage i'm trying to include a carousel of products of a custom post type.

I choose 3 products to show, but only show 1 and without arrows or bullets.

https://drive.google.com/file/d/1frtSn986fx930B_gFCfROWmy665OvewH/view?usp=sharing

What i have to do?

I bought this plugin this morning and i have 2 problems yet.

Please, responde me fast my client is waiting for the work.

Thank you very much!

**Comment by dudaster** [comment]
You have to choose number of slides instead of columns

**Comment by loremipsumejant** [comment]
Yes, i tried but nothing happens... only 1 product is shown

https://drive.google.com/file/d/1k8sPDPlisHvVNs5oN0GcWQW-DogabMcU/view?usp=sharing

**Comment by loremipsumejant** [comment]
Hello? i'm developing the website of my client.

I need a solution please!

Thank you!

**Comment by loremipsumejant** [comment]
Hey! what can i do? some solution or something? i can't finish project!
