### ISSUE TITLE
ACF and Broken Pages

### ISSUE THREAD

**Issue by Shooin** [dudaster/ele-custom-skin#81]
Hello, I purchased the pro to try out the same height with the image field and it puts a lot of space between each row. Any idea why?

**Comment by dudaster** [comment]
Try add all the content in one section.

**Comment by Shooin** [comment]
so do I create a section template and drop the post widget there and set it to custom. I just tried it and that did not work. Well, it worked as they show up, but the same height creates a huge gap between each row.

**Comment by dudaster** [comment]
Create a Loop template > When editing the loop template add one parent section because it doesn’t know what to stretch if you put more parent sections.

Can you provide a link?

**Comment by Shooin** [comment]
Here is what I did. 
1.I create a loop template
2. I added the Title
3. I added the Featured Image
4. I added 2 Text Boxes.
5. Published the template
6. Created a new page
7. Added a post widget
8. Set it to my new skin
9. Changed the query

It looks fine, don't get me wrong but the image heights don't match like the default post widget. Therefore, I purchased the pro 5 license and clicked the same height widget button and it adds a bunch of space. Masonry does not do anything as well. 

**Links below**
**Same Height Button Clicked** -  [LINK](https://sommervillefuneralservice.com/dev1/tuesday-memorial-copy/)
**Default Settings** - [LINK](https://sommervillefuneralservice.com/dev1/tuesday-memorial/)

**Comment by Shooin** [comment]
ok I see that it sets the height of the bounding box to be the same height. Not the image.

**Comment by dudaster** [comment]
please go to navigator when you are editing the Loop Template. You should see only one root section. Not two.

**Comment by dudaster** [comment]
Also please send me a screenshot of the entire page with the navigator opened when you edit the Loop Template.

**Comment by Shooin** [comment]
Dudaster, thanks! Now I see what you mean by 1 parent section. That fixed the giant space. Is there a way to create same size images? Like the original post widget? Do I create a loop inside of a loop?

**Comment by dudaster** [comment]
For the same hight images you can you can use the image as a background image of a innersection with a spacer inside.

**Comment by Shooin** [comment]
Ahhh but the results may vary depending on the size of the image that the user uploads. Is that correct?

**Comment by dudaster** [comment]
set background size to cover and center it.

**Comment by Shooin** [comment]
WOW! That Did it! Amazing - Just simply amazing, Now I think I can style this thing

**Comment by dudaster** [comment]
Well done!

**Comment by dudaster** [comment]
Also don't forget to remove the title of the page by going to settings inside the elementor editor and check Hide Title.

**Comment by Shooin** [comment]
Ok, Thanks!  is there a way to round the corners with the background image?

**Comment by dudaster** [comment]
ofcourse you can just select the section that has the image as background go to Style>Border>Border Radius

**Comment by Shooin** [comment]
I had the background image on the inner section so it was acting dumb. It is working now. Thanks again my friend.

**Comment by dudaster** [comment]
You’re welcome!
