### ISSUE TITLE
Ele Custom Skin (free version) breaks Elementor Pro

### ISSUE THREAD

**Issue by mvultgmr** [dudaster/ele-custom-skin#834]
I'm running Elementor 3.7.0, Elementor Pro 3.7.3, and Ele Custom Skin 3.1.6.

While Ele Custom Skin is activated, the features of Elementor Pro are inaccessible.  In other words, the interface is acting as if I do not have a license for Elementor Pro, which I do.

What other information can I send to help you debug this issue?

**Comment by dddmark** [comment]
Yep! I also have trouble. 
Does not save the page after copying and pasting the text style or cell or container.

https://user-images.githubusercontent.com/12506519/184331021-6183a9a6-4ec6-41ed-8364-ea6421ac09de.mp4

**Comment by cristiansimion** [comment]
Same here. A lot of errors in the console and it breaks with Elementor Pro version 3.7.0 and up.

**Comment by mvultgmr** [comment]
It looks like this has been resolved. The only thing that has changed is my base Elementor plugin upgraded to 3.7.1, so maybe that was it.
