### ISSUE TITLE
No Loop tab on Theme Builder

### ISSUE THREAD

**Issue by omrigonen** [dudaster/ele-custom-skin#84]
Hi,

I have activated the theme, and it says that my license is valid, but yet when I am going into the theme builder.

Omri

**Comment by dudaster** [comment]
What theme did you activated? Have you installed the ECS Pro plugin? If you did you need ECS core plugin to be installed: https://wordpress.org/plugins/ele-custom-skin/

**Comment by omrigonen** [comment]
Thanks.
I didn't know I needed both to be installed.

Great Plugin!

**Comment by dudaster** [comment]
Thank you!
