### ISSUE TITLE
Adding 10px padding since elementor + ele custom skin last updates

### ISSUE THREAD

**Issue by clement-menard** [dudaster/ele-custom-skin#86]
Hi,

I've updated Elementor and Ele Custom Skin plugins, and now, on my custom archive pages, i've got a 10px padding on my loop items...

<img width="1680" alt="Capture d’écran 2019-10-22 à 11 55 33" src="https://user-images.githubusercontent.com/9642015/67275444-ea1b4800-f4c2-11e9-939a-2fd46e1ab019.png">

**Comment by dudaster** [comment]
Edit the Loop Template and select the main section and in Layout Tab select Columns Gap: No Gap.

It should fix the problem.

**Comment by clement-menard** [comment]
You rock ! Thank you
