### ISSUE TITLE
Latest Update Breaks ability to save

### ISSUE THREAD

**Issue by ghost** [dudaster/ele-custom-skin#87]
Hello,

I have been using the Ele Custom Skin plugin with excellent results. However, it seems in the last update, things have broken. Any instance where I use a Dynamic Image field, the layout is broken and any changes I make in the editor are not applied. If I change image size dimensions, it does not apply the update, if I edit margins, etc and click publish, when I reload my page once, the changes take effect but if I refresh a second time, it reverts to these default settings. I'm using the latest version of WP, Ele Custom Skin, Elementor and Elementor Pro.

**Comment by dudaster** [comment]
Does this thing happens with Hello Theme Elementor?

**Comment by dudaster** [comment]
Also try to apply a featured image to the page which contains the Post Widget.

**Comment by ghost** [comment]
No, I'm using WP Astra. It was working great until the last update, if I could revert to previous version, I would to test it. You wouldn't happen to have a ZIP file available for the previous version of your plugin? I would just like to troubleshoot on my side since we are actively doing development, and I'm 90% sure this is due to the latest plugin update but cannot be 100% certain.

**Comment by dudaster** [comment]
Try saving Loop template without any conditions. And also you have in
Advanced section of plugin’s page on Wordpress.org older versions.

**Comment by ghost** [comment]
It already is being applied with no conditions. Ok great, let me try
reverting to older version and if issue persists then it's related to a
different item. Thank you very much for your help.

**Comment by Kamaniszi** [comment]
I have same issue as Dreamsreal7. Additionaly layout doesn't work on Firefox. (after last update)

**Comment by dudaster** [comment]
Can you provide a link? This last update loads the template’s css in head. This is the only change.

I would like to see if there is a caching issue Or something else.

**Comment by ghost** [comment]
I don't currently have any caching enabled on the site. Is there a private
method I can send details? Our site is behind a login screen due to
development so I'd have to provide temporary login credentials.

**Comment by ghost** [comment]
I reverted the plugin to V1.3.4 and this has corrected the issue. Therefore it seems something in the latest version was causing a problem.

**Comment by dudaster** [comment]
Several people had this issue and the problem was with setting their https in website url in their Wordpress settings
