### ISSUE TITLE
Adding var to custom_vars

### ISSUE THREAD

**Issue by omrigonen** [dudaster/ele-custom-skin#88]
Hi,

I have added the following code to the functions.php:

`/**
 * Get the user's role (single)
 * @since 1.0.0
 */
function get_current_user_roles() {
 if( is_user_logged_in() ) {
 $user = wp_get_current_user();
 $roles = ( array ) $user->roles;
 //return $roles; // This returns an array
 // Use this to return a single value
  return $roles[0];
 } else {
 return array();
 }
 
//Add to Custom Element Condition - User Role 
add_filter( 'ecs_vars', function ( $custom_vars ) {
    $custom_vars['user_role']=get_current_user_roles(); //adding the terms name to the dynamic everywhere
    return $custom_vars;
});
`

And used the following condition: {{user_role}}==admin

And it does not work - any idea why? ({{user_role}}==null does show the element)

Tnx
Omri

**Comment by dudaster** [comment]
You added a custom var to the ECS Pro for Ele Conditions you need to add filter to eleconditions_vars not ecs_vars .

Hopefully it make sense.

**Comment by omrigonen** [comment]
Works great!

Thanks.

**Comment by dudaster** [comment]
Welcome!
