### ISSUE TITLE
Excerpt is missing when using Loop template

### ISSUE THREAD

**Issue by rickardm** [dudaster/ele-custom-skin#89]
Hi! Sorry for the interruption and thank you for this good plugin.

The problem I am having is that I'm creating a custom skin using Elementor Custom Skins 1.3.6. Everything goes great but I **cannot get the excerpt to show up** all the time.

The excerpt shows up if it was manually typed in the Custom Excerpt box. But not when it should take the first few words of the post.

I put together this sample page that shows the problem:

[https://auri2.pounce.one/xyz-bug-report/](https://auri2.pounce.one/xyz-bug-report/)

(If you get a password prompt, try "cornfield".)

In the sample page above, I'm using Elementor Posts widget, and I have it loop over the same five posts using three different skins. The standard skins from Elementor show the excerpt. The custom skin from Elementor Custom skins does not show an excerpt.

I'm adding two images that show what it looks like when editing the Loop template and trying to add the excerpt.

![20191025-step_1-adding_the_excerpt](https://user-images.githubusercontent.com/2256928/67596360-1996b280-f758-11e9-8436-9e12c3b0d183.png)

![20191025-step_2-editing_the_excerpt](https://user-images.githubusercontent.com/2256928/67596379-21eeed80-f758-11e9-93cd-2af37ef309aa.png)

I am new to Elementor and Elementor Custom Skins, so it is possible I am missing something.

I have seen a problem similar to this in WordPress. When loading up posts outside of the loop, needing to pass the ID of the post into get_the_excerpt(). Just an idea.

`get_the_excerpt( get_the_ID() );`

**Comment by dudaster** [comment]
Please use text widget with dynamic value. For some reason those widgets work only in single templates.

**Comment by rickardm** [comment]
Okay I tried with a text widget, dynamic value.

Setting the dynamic value to "Post Excerpt" still did not work but setting it to "Post Summary" did work. I'm not sure how these two are different, but I'm happy to have the excerpt finally showing up.

The excerpt put in this way is not ellipsized, but maybe I can solve that with CSS. Thank you for the quick response. I think this is solved enough.
