### ISSUE TITLE
CSS Issues

### ISSUE THREAD

**Issue by madbradjohnson** [dudaster/ele-custom-skin#9]
Issue with custom cards and CSS. See attached screenshot. (Tested Incognito) In Elementor, posts display 100%. 

After publishing and viewing (NO CACHE)  The Page displays fine for a second and reverts to the screenshot attached.
![capture](https://user-images.githubusercontent.com/36671673/47937312-f771a800-dee8-11e8-8fd6-a7a7f1f01eec.JPG)

Let me know if you need any further info.

**Comment by madbradjohnson** [comment]
Any news on this?

**Comment by dudaster** [comment]
Try contacting me in private and give me access to your website to see what could be the problem.

I can’t replicate the problem.

**Comment by dudaster** [comment]
Ok I think the problem is this:

1. Go and edit the loop template
2. Select the main section of the content
3. Make sure "Stretch Section" is "no" (appears grey), if it is blue and says "yes" for sure this is the issue.
