### ISSUE TITLE
Latest update partially break my layout

### ISSUE THREAD

**Issue by DavidCaum** [dudaster/ele-custom-skin#91]
Hello,

Since I update from V1.3.4 to V1.3.6, I have a layout problem with my 4 loop templates (created for custom posts grids). 
I'm using the latest version of WP, Ocean WP, Ele Custom Skin, Elementor, Elementor Pro and WP Rocket (I deactivated this last one to make my tests).
I tried to revert to older versions of Elementor and E Pro, clean the cache, etc Nothing changed.
I test to revert to V1.3.4 and the issue disappeared.
The issue: It seems to create padding to some elements or widgets. You can see the website with V1.3.4 (https://www.nicolas-devillard.fr) and a screenshot of the issue with V1.3.6 (https://www.nicolas-devillard.fr/wp-content/uploads/2019/11/bad.png).
Comparing the two you can notice padding around the title, the picture (which is shrinked) and some text elements (which create white spaces around).
I also tried to make any minor change in a template. When I refresh the frontend page, everything appears good (non padding). But when I refresh a second time this page, the issue comes back again.
I also have a look with the dev tools and it seems it make a change at .elementor-column-gap-default>.elementor-row>.elementor-column>.elementor-element-populated by adding a padding of 10px.

Any idea to fix this?
Best,

**Comment by dudaster** [comment]
Please go to loop template and select for each section no gap option

**Comment by DavidCaum** [comment]
It works fine. But I don't understand. Did your update changed anything for I have to do this?

**Comment by dudaster** [comment]
To put it in few words: before was wrong now it is how it was supposed to.
