### ISSUE TITLE
Custom Post Type Posts Per Page Breaks

### ISSUE THREAD

**Issue by BradShoemaker** [dudaster/ele-custom-skin#92]
I am using the Free version right now to evaluate it and I feel I could really use this moving forward; however, I am running into an issue where I have Posts Per Page set to 1. In Elementor it shows up correctly but on the live site it is showing all posts.

I am using the Theme Sonaar (a podcast related theme). If i choose "Posts" as the content type it works perfectly. If I choose "Podcasts" as the Custom Content Type it shows all posts on one page.

Here is the page I am talking about. I have 2 instances of ELE Custom Skin running. The first is at the top in the green-ish area (below the header). This is where it is supposed to only show one post per page.

Directly below that it shows the rest of the posts using another ELE Custom Skin and the same thing happens there. I have them set to offset by 1 and only show 12 via 3 column layout. It shows all of them and does not offset the posts by 1.

**Comment by BradShoemaker** [comment]
Forgot the URL: https://cultcinemacavalcade.com

**Comment by dudaster** [comment]
It behaves the same with classic skin?

**Comment by BradShoemaker** [comment]
Yes I just switched it to classic.

**Comment by dudaster** [comment]
So the issue persists with other than ECS?

**Comment by BradShoemaker** [comment]
The issue persists when the Classic Skin in ECS is activated.

**Comment by BradShoemaker** [comment]
In the Elementor design window, it shows up like it should. On the live site it shows every post in that particular Custom Post Type.

**Comment by dudaster** [comment]
Do you have other custom posts types you can test it on?

**Comment by BradShoemaker** [comment]
Just tried 3 different custom post types and it appears it only happens when the audio player is present (so Podcast Post Type and Playlist Post Type).

**Comment by BradShoemaker** [comment]
My apologies for doing this here as it is clearly a Sonaar theme issues.

**Comment by dudaster** [comment]
No worries. We’ll help as we can.
