### ISSUE TITLE
Same image when using dynamic image on flipbox

### ISSUE THREAD

**Issue by pless84** [dudaster/ele-custom-skin#93]
I'm trying to use the flipbox widget in a template but the result is that each box gets the same image.
This is my loop on the frontpage:
![loop](https://user-images.githubusercontent.com/324145/68220388-f980b200-ffe7-11e9-9970-7820acb2dccd.png)

**Comment by dudaster** [comment]
I’ll take a look. But try this for now: save the loop template without any conditions.

**Comment by pless84** [comment]
I have no conditions on the template already

**Comment by dudaster** [comment]
can I have a link to your project? I want to inspect element it.

**Comment by pless84** [comment]
sorry it's local only, but I have worked around it by using the call to action and just fade the image/text for now.

**Comment by dudaster** [comment]
Fixed with the latest update.
