### ISSUE TITLE
Elementor Installed But Seeing: Ele Custom Skin needs Elementor and Elementor Pro to work

### ISSUE THREAD

**Issue by AdventurouslySocial** [dudaster/ele-custom-skin#95]
Installed Versions:
Elementor Free Version 2.7.5
Elementor Pro Version 2.7.2
Ele Custom Skins Version 1.3.6

I have everything installed. I have deactivated all plugins except for these three. No idea why I'm seeing this notice.

I have tried an older version of Ele Custom Skins Version 1.3.2 because it is working on another site which is running the following combination: 

Elementor Free Version 2.7.4
Elementor Pro Version 2.6.5
Ele Custom Skins Version 1.3.2

Thoughts? Input? Suggestions?

**Comment by dudaster** [comment]
Make sure the folder elementor pro is installed is elementor-pro

**Comment by AdventurouslySocial** [comment]
Will do. That could be the culprit. I do sometimes version out the folder names.

**Comment by AdventurouslySocial** [comment]
You hit a home run first time at the plate. Thank you. The issue was indeed that the folder for elementor-pro was actually elementor-pro-version-xxx

**Comment by dudaster** [comment]
Welcome! I’ll try in the future to ignore the folder.

**Comment by AdventurouslySocial** [comment]
Just fyi, Truly useful & amazing plugin dudaster. It's well designed, well programmed, and a must have. I really love this thing.
