### ISSUE TITLE
Dynamic Everywhere with links to PODS related post types?

### ISSUE THREAD

**Issue by Guang0404** [dudaster/ele-custom-skin#96]
I noticed it just returns "Array" when using dynamic content for Relational Fields. It also doesn't return the Related Post URL.

Will this be a feature implemented in the future?

Thanks again for this wonderful plugin, I am a proud user!

**Comment by dudaster** [comment]
I'll keep in mind for the future.

**Comment by dudaster** [comment]
can you please check this issue here and see if this answers your question?

https://github.com/pods-framework/pods/issues/5165#issuecomment-560099818
