### ISSUE TITLE
Loops Need To Be Saved As Templates Before being Selectable

### ISSUE THREAD

**Issue by hoohum** [dudaster/ele-custom-skin#97]
I’ve just bought the pro version of your Elementor Custom Skin plugin. I created 2 loops. One with a post featured image in a left hand column and text in the right, and one with that order reversed, to show alternately underneath each other in a  full width page like rows with 2 columns.

I did not assign them anywhere. When I chose ‘custom’ in the posts element editor I could see my two loops but could not select them. For no particular reason I saved one as a template (I can’t remember how I was offered that choice) and then I could select it in the custom list and everything works. But now I have a duplicate of it in my templates list. Do I need to save loops as templates therefore and have lots of duplicates. It seems an odd thing to need to do or is there a fault. 

Also, when I created the second loop, I initially cloned the first one to save time but it set it as a ‘page’ not a loop and I could not see how to change it to loop after creating it so I had to delete it and create one manually. Why did this happen and can I stop cloning from changing the type of template from loop to page?

**Comment by dudaster** [comment]
You need to create a Loop Template if you save it as another template you'll not be able to see it in the default template select.

I didn't encounter this behavour before. Is it because of ECS Pro, or doesn't matter?

**Comment by dudaster** [comment]
Also if you use safari you'll not be able to select one template you need to have 2 at least.

**Comment by hoohum** [comment]
Understood. Thanks for the quick response.
