### ISSUE TITLE
Ability to create custom overal template without loop

### ISSUE THREAD

**Issue by tiagoefreitas** [dudaster/ele-custom-skin#98]
Hi, Is there a possibility of using a custom shortcode that can use all the posts at the same time, instead of having a loop template that only sees one post at a time?

I have a function that outputs a graph to compare all the posts (in this case product attributes)

Otherwise I would have to create a custom elementor widget that is a copy of the posts widget but uses my code, that needs an array with all the posts.

**Comment by dudaster** [comment]
You mean post widget inside post widget? Tried a few months again didn’t worked but you can try it again maybe it works.

**Comment by tiagoefreitas** [comment]
No, I mean in the render function (that you currently do not override) instead of having a loop that calls the template for each post, this global template has access to all posts and gets called only once.

So I could use a shortcode inside the posts widget that can access the query and use all posts at the same time.

**Comment by tiagoefreitas** [comment]
Because currently I have no way of doing this I think....if I add a shortcode to the elementor page template, I can't access the WP_Query from the posts widget from inside the shortcode

**Comment by dudaster** [comment]
Let me know where you want to add_filter.
