### ISSUE TITLE
Image Gallery Widget (get from ACF) not working

### ISSUE THREAD

**Issue by aquaminh** [dudaster/ele-custom-skin#99]
Hi,

I have issue when getting ACF gallery field value for Elementor Gallery Widget in the loop. The gallery is not displayed on the frontend.

I've set no conditions to the loop and am using ECS Pro (and Ele Pro).

Could you please investigating the issue?

Thanks.

**Comment by dudaster** [comment]
Try to make sure the gallery is there and it is working in other elementor templates like single template.

Here is a working example: https://www.streethome.ro/en/news/

**Comment by dudaster** [comment]
Is it working?
